export interface TraditionalColor { name: string; hex: string; pinyin?: string; }

export const CHINESE_COLORS: TraditionalColor[] = [
  { name: '胭脂', hex: '#9d2933', pinyin: 'yānzhī' }, { name: '朱砂', hex: '#ff461f', pinyin: 'zhūshā' },
  { name: '火红', hex: '#ff2d51', pinyin: 'huǒhóng' }, { name: '朱红', hex: '#ff4c00', pinyin: 'zhūhóng' },
  { name: '丹', hex: '#ff4e20', pinyin: 'dān' }, { name: '彤', hex: '#f35336', pinyin: 'tóng' },
  { name: '绛紫', hex: '#8c4356', pinyin: 'jiàngzǐ' }, { name: '妃色', hex: '#ed5736', pinyin: 'fēisè' },
  { name: '品红', hex: '#f00056', pinyin: 'pǐnhóng' }, { name: '桃红', hex: '#f47983', pinyin: 'táohóng' },
  { name: '海棠红', hex: '#db5a6b', pinyin: 'hǎitánghóng' }, { name: '石榴红', hex: '#f20c00', pinyin: 'shíliuhóng' },
  { name: '樱桃色', hex: '#c93756', pinyin: 'yīngtáosè' }, { name: '银红', hex: '#f05654', pinyin: 'yínhóng' },
  { name: '大红', hex: '#ff2121', pinyin: 'dàhóng' }, { name: '绛红', hex: '#c45a65', pinyin: 'jiànghóng' },
  { name: '绯红', hex: '#c83c23', pinyin: 'fēihóng' }, { name: '酡红', hex: '#dc3023', pinyin: 'tuóhóng' },
  { name: '鹅黄', hex: '#fff143', pinyin: 'éhuáng' }, { name: '鸭黄', hex: '#faff72', pinyin: 'yāhuáng' },
  { name: '樱草色', hex: '#eaff56', pinyin: 'yīngcǎosè' }, { name: '杏黄', hex: '#ffa631', pinyin: 'xìnghuáng' },
  { name: '杏红', hex: '#ff8c31', pinyin: 'xìnghóng' }, { name: '橘黄', hex: '#ff8936', pinyin: 'júhuáng' },
  { name: '橙黄', hex: '#ffa400', pinyin: 'chénghuáng' }, { name: '橘红', hex: '#ff7500', pinyin: 'júhóng' },
  { name: '姜黄', hex: '#ffc773', pinyin: 'jiānghuáng' }, { name: '缃色', hex: '#f0c239', pinyin: 'xiāngsè' },
  { name: '橙色', hex: '#fa8c35', pinyin: 'chéngsè' }, { name: '茶色', hex: '#b35c44', pinyin: 'chásè' },
  { name: '驼色', hex: '#a88462', pinyin: 'tuósè' }, { name: '昏黄', hex: '#c89b40', pinyin: 'hūnhuáng' },
  { name: '栗色', hex: '#60281e', pinyin: 'lìsè' }, { name: '棕色', hex: '#b25d25', pinyin: 'zōngsè' },
  { name: '棕绿', hex: '#827100', pinyin: 'zōnglǜ' }, { name: '棕黑', hex: '#7c4b00', pinyin: 'zōnghēi' },
  { name: '棕红', hex: '#9b4400', pinyin: 'zōnghóng' }, { name: '棕黄', hex: '#ae7000', pinyin: 'zōnghuáng' },
  { name: '赤金', hex: '#f2be45', pinyin: 'chìjīn' }, { name: '金色', hex: '#eacd76', pinyin: 'jīnsè' },
  { name: '竹青', hex: '#789262', pinyin: 'zhúqīng' }, { name: '葱青', hex: '#0eb83a', pinyin: 'cōngqīng' },
  { name: '青葱', hex: '#0aa344', pinyin: 'qīngcōng' }, { name: '油绿', hex: '#00bc12', pinyin: 'yóulǜ' },
  { name: '绿沈', hex: '#0c8918', pinyin: 'lǜshěn' }, { name: '碧色', hex: '#1bd1a5', pinyin: 'bìsè' },
  { name: '碧绿', hex: '#2add9c', pinyin: 'bìlǜ' }, { name: '青碧', hex: '#48c0a3', pinyin: 'qīngbì' },
  { name: '翡翠色', hex: '#3de1ad', pinyin: 'fěicuìsè' }, { name: '草绿', hex: '#40de5a', pinyin: 'cǎolǜ' },
  { name: '青色', hex: '#00e09e', pinyin: 'qīngsè' }, { name: '青翠', hex: '#00e079', pinyin: 'qīngcuì' },
  { name: '松柏绿', hex: '#21a675', pinyin: 'sōngbǎilǜ' }, { name: '松花绿', hex: '#057748', pinyin: 'sōnghuālǜ' },
  { name: '石青', hex: '#1685a9', pinyin: 'shíqīng' }, { name: '靛青', hex: '#177cb0', pinyin: 'diànqīng' },
  { name: '靛蓝', hex: '#065279', pinyin: 'diànlán' }, { name: '花青', hex: '#003472', pinyin: 'huāqīng' },
  { name: '宝蓝', hex: '#4b5cc4', pinyin: 'bǎolán' }, { name: '蓝灰色', hex: '#a1afc9', pinyin: 'lánhuīsè' },
  { name: '藏青', hex: '#2e4e7e', pinyin: 'zàngqīng' }, { name: '藏蓝', hex: '#3b2e7e', pinyin: 'zànglán' },
  { name: '黛', hex: '#4a4266', pinyin: 'dài' }, { name: '黛绿', hex: '#426666', pinyin: 'dàilǜ' },
  { name: '黛蓝', hex: '#425066', pinyin: 'dàilán' }, { name: '黛紫', hex: '#574266', pinyin: 'dàizǐ' },
  { name: '紫色', hex: '#8d4bbb', pinyin: 'zǐsè' }, { name: '紫酱', hex: '#815463', pinyin: 'zǐjiàng' },
  { name: '酱紫', hex: '#815476', pinyin: 'jiàngzǐ' }, { name: '紫檀', hex: '#4c221b', pinyin: 'zǐtán' },
  { name: '绀青', hex: '#003371', pinyin: 'gànqīng' }, { name: '紫棠', hex: '#56004f', pinyin: 'zǐtáng' },
  { name: '青莲', hex: '#801dae', pinyin: 'qīnglián' }, { name: '群青', hex: '#4c8dae', pinyin: 'qúnqīng' },
  { name: '雪白', hex: '#f0fcff', pinyin: 'xuěbái' }, { name: '月白', hex: '#d6ecf0', pinyin: 'yuèbái' },
  { name: '缟', hex: '#f2ecde', pinyin: 'gǎo' }, { name: '素', hex: '#e0f0e9', pinyin: 'sù' },
  { name: '荼白', hex: '#f3f9f1', pinyin: 'túbái' }, { name: '霜色', hex: '#e9f1f6', pinyin: 'shuāngsè' },
  { name: '花白', hex: '#c2ccd0', pinyin: 'huābái' }, { name: '鱼肚白', hex: '#fcefe8', pinyin: 'yúdùbái' },
  { name: '莹白', hex: '#e3f9fd', pinyin: 'yíngbái' }, { name: '灰色', hex: '#808080', pinyin: 'huīsè' },
  { name: '牙色', hex: '#eedeb0', pinyin: 'yásè' }, { name: '铅白', hex: '#f0f0f4', pinyin: 'qiānbái' },
  { name: '玄色', hex: '#622a1d', pinyin: 'xuánsè' }, { name: '玄青', hex: '#3d3b4f', pinyin: 'xuánqīng' },
  { name: '乌色', hex: '#725e82', pinyin: 'wūsè' }, { name: '乌黑', hex: '#392f41', pinyin: 'wūhēi' },
  { name: '漆黑', hex: '#161823', pinyin: 'qīhēi' }, { name: '墨色', hex: '#50616d', pinyin: 'mòsè' },
  { name: '墨灰', hex: '#758a99', pinyin: 'mòhuī' }, { name: '黑色', hex: '#000000', pinyin: 'hēisè' },
];

export const JAPANESE_COLORS: TraditionalColor[] = [
  { name: '桜色', hex: '#fef4f4' }, { name: '薄桜', hex: '#fdeff2' }, { name: '桜鼠', hex: '#e9dfe5' },
  { name: '鴇色', hex: '#f4b3c2' }, { name: '虹色', hex: '#f6bfbc' }, { name: '珊瑚色', hex: '#f5b1aa' },
  { name: '一斤染', hex: '#f5b199' }, { name: '宍色', hex: '#f2a0a1' }, { name: '紅梅色', hex: '#f2a0a1' },
  { name: '薔薇色', hex: '#e9546b' }, { name: '韓紅花', hex: '#e95464' }, { name: '銀朱', hex: '#c85554' },
  { name: '赤紅', hex: '#c53d43' }, { name: '紅緋', hex: '#e83929' }, { name: '真朱', hex: '#ec6d51' },
  { name: '朱色', hex: '#eb6101' }, { name: '金赤', hex: '#ea5506' }, { name: '赤橙', hex: '#ea5506' },
  { name: '照柿', hex: '#eb6238' }, { name: '柿色', hex: '#ed6d3d' }, { name: '黄丹', hex: '#ee7948' },
  { name: '人参色', hex: '#ec8254' }, { name: '橙色', hex: '#ee7800' }, { name: '蜜柑色', hex: '#f08300' },
  { name: '金茶', hex: '#f39800' }, { name: '萱草色', hex: '#f8b500' }, { name: '山吹色', hex: '#f8b500' },
  { name: '黄檗色', hex: '#fef263' }, { name: '蒲公英色', hex: '#ffd900' }, { name: '黄色', hex: '#ffd900' },
  { name: '中黄', hex: '#ffea00' }, { name: '菜の花色', hex: '#ffec47' }, { name: '刈安色', hex: '#f5e56b' },
  { name: '黄緑', hex: '#b8d200' }, { name: '若草色', hex: '#c3d825' }, { name: '若葉色', hex: '#b9d08b' },
  { name: '若竹色', hex: '#68be8d' }, { name: '青竹色', hex: '#7ebeab' }, { name: '常磐色', hex: '#007b43' },
  { name: '千歳緑', hex: '#316745' }, { name: '深緑', hex: '#00552e' }, { name: '青緑', hex: '#00a497' },
  { name: '浅葱色', hex: '#00a3af' }, { name: '水色', hex: '#bce2e8' }, { name: '空色', hex: '#a0d8ef' },
  { name: '勿忘草色', hex: '#89c3eb' }, { name: '露草色', hex: '#38a1db' }, { name: '青', hex: '#0095d9' },
  { name: '薄藍', hex: '#698aab' }, { name: '縹色', hex: '#2792c3' }, { name: '紺碧', hex: '#007bbb' },
  { name: '瑠璃色', hex: '#1e50a2' }, { name: '群青色', hex: '#4c6cb3' }, { name: '藍色', hex: '#165e83' },
  { name: '紺色', hex: '#223a70' }, { name: '紺青', hex: '#192f60' }, { name: '鉄紺', hex: '#17184b' },
  { name: '藤色', hex: '#bbbcde' }, { name: '藤紫', hex: '#a59aca' }, { name: '菫色', hex: '#7058a3' },
  { name: '紫', hex: '#884898' }, { name: '江戸紫', hex: '#745399' }, { name: '本紫', hex: '#65318e' },
  { name: '葡萄色', hex: '#522f60' }, { name: '茄子紺', hex: '#824880' }, { name: '牡丹色', hex: '#e7609e' },
  { name: '白', hex: '#ffffff' }, { name: '胡粉色', hex: '#fffffc' }, { name: '生成色', hex: '#fbfaf5' },
  { name: '灰白色', hex: '#e9e4d4' }, { name: '銀鼠', hex: '#afafb0' }, { name: '鼠色', hex: '#949495' },
  { name: '灰色', hex: '#7d7d7d' }, { name: '墨', hex: '#595857' }, { name: '黒', hex: '#2b2b2b' },
  { name: '漆黒', hex: '#0d0015' }, { name: '利休鼠', hex: '#888e7e' }, { name: '海松色', hex: '#726d40' },
  { name: '鶯色', hex: '#928c36' }, { name: '抹茶色', hex: '#c5c56a' }, { name: '若苗色', hex: '#c7dc68' },
  { name: '萌黄', hex: '#aacf53' }, { name: '松葉色', hex: '#687e52' }, { name: '苔色', hex: '#69821b' },
  { name: '鶸色', hex: '#d7cf3a' }, { name: '鬱金色', hex: '#fabf14' }, { name: '朽葉色', hex: '#917347' },
  { name: '丁子色', hex: '#efcd9a' }, { name: '狐色', hex: '#c38743' }, { name: '黄土色', hex: '#c39143' },
  { name: '琥珀色', hex: '#bf783a' }, { name: '飴色', hex: '#deb068' }, { name: '錆色', hex: '#6c3524' },
  { name: '栗色', hex: '#762f07' }, { name: '煉瓦色', hex: '#b55233' }, { name: '弁柄色', hex: '#8f2e14' },
  { name: '赤錆色', hex: '#8a3319' }, { name: '小豆色', hex: '#96514d' }, { name: '鳶色', hex: '#95483f' },
  { name: '海老茶', hex: '#773c30' }, { name: '肌色', hex: '#fce2c4' }, { name: '薄香', hex: '#f0cfa0' },
  { name: '砥粉色', hex: '#f4dda5' }, { name: '枯草色', hex: '#e4dc8a' }, { name: '亜麻色', hex: '#d6c6af' },
];
