export type ToolCategory = 'text' | 'json' | 'encoding' | 'color' | 'network' | 'math' | 'converter' | 'formatter' | 'image' | 'css' | 'misc';
export type Locale = 'en' | 'zh-cn' | 'zh-tw' | 'ja' | 'ko' | 'es' | 'fr' | 'de' | 'pt' | 'ru';

export interface ToolMeta {
  slug: string;
  icon: string;
  category: ToolCategory;
  enabled: boolean;
  featured?: boolean;
  supportedLocales: Locale[];
  name: Record<Locale, string>;
  description: Record<Locale, string>;
}

const ALL_LOCALES = ['en','zh-cn','zh-tw','ja','ko','es','fr','de','pt','ru'] as Locale[];
function p3(slug: string, icon: string, category: ToolCategory, en: string, zhcn: string, den: string, dzhcn: string): ToolMeta {
  return { slug, icon, category, enabled: true, supportedLocales: ALL_LOCALES, name: { en, 'zh-cn': zhcn, 'zh-tw': zhcn, ja: en, ko: en, es: en, fr: en, de: en, pt: en, ru: en }, description: { en: den, 'zh-cn': dzhcn, 'zh-tw': dzhcn, ja: den, ko: den, es: den, fr: den, de: den, pt: den, ru: den } };
}

const P3_TOOLS: ToolMeta[] = [
  p3('json-tree','🌳','json','JSON Tree Viewer','JSON 树形查看器','Collapsible tree view of JSON data','可折叠的 JSON 树形视图'),
  p3('json-random','🎲','json','JSON Random Generator','JSON 随机生成器','Generate random JSON data','生成随机 JSON 数据'),
  p3('json-cleaner','🧹','json','JSON Cleaner','JSON 清理工具','Remove comments and trailing commas','移除注释和尾逗号'),
  p3('json-querystring','🔗','json','JSON ↔ Query String','JSON 查询字符串互转','Convert between JSON and query strings','JSON 与查询字符串互转'),
  p3('json-highlight','🎨','json','JSON Syntax Highlight','JSON 语法高亮','JSON syntax highlighting','JSON 语法着色高亮'),
  p3('json-editor','✏️','json','JSON Editor','JSON 在线编辑器','Online JSON editor with validation','在线 JSON 编辑器'),
  p3('escape-encoder','🔐','encoding','JS Escape/Unescape','JS 转义编码','JavaScript escape and unescape','JavaScript 转义/反转义'),
  p3('base32-encoder','🔑','encoding','Base32/58/62 Encoder','Base32/58/62 编码','Base32, Base58, Base62 encode/decode','Base32/Base58/Base62 编码解码'),
  p3('bcrypt-tool','🔒','encoding','Bcrypt Hash Tool','Bcrypt 哈希工具','Bcrypt hash generation and verification','Bcrypt 哈希生成与验证'),
  p3('morse-code','📡','encoding','Morse Code','摩斯密码转换','Text ↔ Morse code conversion','文本与摩斯密码互转'),
  p3('gzip-tool','📦','encoding','Gzip Compress','Gzip 压缩解压','Gzip compress and decompress','Gzip 压缩和解压缩'),
  p3('htpasswd-gen','🔧','encoding','htpasswd Generator','htpasswd 生成器','Generate htpasswd entries','生成 htpasswd 条目'),
  p3('file-hash','📁','encoding','File Hash Calculator','文件哈希计算器','Calculate file hashes via Web Crypto','文件哈希计算'),
  p3('native-ascii','🔤','encoding','Native/ASCII Converter','Native/ASCII 互转','Native ↔ \\uXXXX ASCII conversion','Native 与 ASCII 互转'),
  p3('rsa-tool','🔐','encoding','RSA Key Tool','RSA 密钥工具','RSA key pair generation and encrypt/decrypt','RSA 密钥对生成与加解密'),
  p3('hex-url','🌐','encoding','URL Hex Encoding','URL 十六进制编码','URL hex encoding and decoding','URL 十六进制编码解码'),
  p3('utf8-tool','📝','encoding','UTF-8 Byte Viewer','UTF-8 字节查看器','View UTF-8 byte sequences','查看 UTF-8 字节序列'),
  p3('email-encode','📧','encoding','Email Encoder','邮箱地址加密','Anti-scraping email encoding','邮箱地址防采集编码'),
  p3('cert-gen','📜','encoding','Certificate Generator','证书生成器','Self-signed certificate generator (coming soon)','自签名证书生成器（即将推出）'),
  p3('js-obfuscate','🔒','encoding','JS Obfuscator','JS 混淆工具','Basic JS variable name obfuscation','基本 JS 变量名混淆'),
  p3('scrypt-tool','🔑','encoding','Scrypt Hash','Scrypt 哈希','Scrypt hash tool (coming soon)','Scrypt 哈希工具（即将推出）'),
  p3('cookie-formatter','🍪','formatter','Cookie Formatter','Cookie 格式化','Cookie string to key-value table','Cookie 字符串转键值表'),
  p3('header-formatter','📋','formatter','HTTP Header Formatter','HTTP Header 格式化','HTTP header to key-value table','HTTP 头部转键值表'),
  p3('url-params','🔗','formatter','URL Params Editor','URL 参数编辑器','URL query params to editable table','URL 查询参数编辑'),
  p3('c-formatter','💻','formatter','C/C# Formatter','C/C# 格式化','Basic C/C# code formatting','基本 C/C# 代码格式化'),
  p3('ruby-formatter','💎','formatter','Ruby Formatter','Ruby 格式化','Basic Ruby/Perl code formatting','基本 Ruby/Perl 代码格式化'),
  p3('sql-quotes','📝','formatter','SQL Quotes Tool','SQL 引号处理','Add/remove double quotes in SQL','SQL 标识符引号处理'),
  p3('hex-text','🔢','converter','Hex ↔ Text','十六进制与文本互转','Hex string ↔ text conversion','十六进制字符串与文本互转'),
  p3('fullwidth-halfwidth','全','converter','Fullwidth ↔ Halfwidth','全角半角互转','Fullwidth ↔ halfwidth conversion','全角与半角字符互转'),
  p3('geo-coords','🗺️','converter','Geo Coordinate Converter','地图坐标转换','WGS-84/GCJ-02/BD-09 conversion','WGS-84/GCJ-02/BD-09 坐标转换'),
  p3('dms-converter','📐','converter','DMS Converter','度分秒转换','Decimal degrees ↔ DMS conversion','十进制度与度分秒互转'),
  p3('short-url','🔗','converter','Short URL Encoder','短地址编码','Short URL Base62 encoding simulation','短地址 Base62 编码模拟'),
  p3('html-ubb','📝','converter','HTML ↔ BBCode','HTML/UBB 互转','HTML ↔ BBCode/UBB conversion','HTML 与 BBCode 互转'),
  p3('doc-to-pdf','📄','converter','Doc to PDF','文档转 PDF','HTML/Markdown to PDF (coming soon)','文档转 PDF（即将推出）'),
  p3('si-units','📏','converter','SI Unit Converter','国际单位制转换','SI unit conversion (force, energy, etc.)','国际单位制转换'),
  p3('ip-to-int','🌐','converter','IP ↔ Integer','IP 地址转整数','IPv4 ↔ integer conversion','IPv4 与整数互转'),
  p3('matrix-json','📊','converter','Matrix ↔ JSON','矩阵与 JSON 互转','Matrix ↔ JSON 2D array conversion','矩阵与 JSON 二维数组互转'),
  p3('cookie-to-js','🍪','converter','Cookie → JS','Cookie 转 JS','Cookie string to JS code','Cookie 字符串转 JS 代码'),
  p3('richtext-markdown','📝','converter','Rich Text → Markdown','富文本转 Markdown','Rich text HTML to Markdown','富文本 HTML 转 Markdown'),
  p3('video-to-mp3','🎵','converter','Video → MP3','视频转 MP3','Video to audio extraction (coming soon)','视频转音频（即将推出）'),
  p3('video-trim','✂️','converter','Video Trim','视频裁剪','Video trimming (coming soon)','视频裁剪（即将推出）'),
  p3('video-crop','🖼️','converter','Video Crop','视频画面裁剪','Video crop (coming soon)','视频画面裁剪（即将推出）'),
  p3('pdf-compress','📦','converter','PDF Compress','PDF 压缩','PDF compression (coming soon)','PDF 压缩（即将推出）'),
  p3('pdf-editor','✏️','converter','PDF Editor','PDF 编辑器','PDF editor (coming soon)','PDF 编辑器（即将推出）'),
  p3('php-session','🐘','converter','PHP Session Parser','PHP Session 解析','PHP session data parser','PHP Session 数据解析'),
  p3('currency-uppercase','💰','converter','Currency Uppercase','货币大写转换','Number to multi-currency uppercase','数字转多国货币大写'),
  p3('js-eval','🔧','encoding','JS Eval Encrypt','JS Eval 加密','JS eval encrypt/decrypt','JS Eval 加密解密'),
  p3('thunder-url','⚡','encoding','Thunder URL Decode','迅雷链接解码','Thunder/FlashGet URL decode','迅雷/快车链接解码'),
  p3('torrent-magnet','🧲','encoding','Torrent → Magnet','种子转磁力链','Torrent to magnet link (coming soon)','种子转磁力链（即将推出）'),
  p3('html-js-convert','🔄','converter','HTML ↔ JS String','HTML/JS 互转','HTML ↔ JS string conversion','HTML 与 JS 字符串互转'),
  p3('lunar-calendar','📅','misc','Lunar Calendar','公历农历互转','Gregorian ↔ Lunar calendar conversion','公历与农历互转'),
  p3('php-session-data','🐘','converter','PHP Session Data','PHP Session 数据转换','PHP session data conversion','PHP Session 数据转换'),
  p3('text-reverse','🔄','text','Text Reverse','文本翻转','Text and line reverse','文本/行翻转'),
  p3('text-find-replace','🔍','text','Find & Replace','查找替换','Find and replace with regex support','支持正则的查找替换'),
  p3('line-numbers','🔢','text','Line Numbers','行号工具','Add/remove line numbers','添加/移除行号'),
  p3('string-count','📊','text','String Counter','字符串计数','Count string occurrences','统计字符串出现次数'),
  p3('ascii-art','🎨','text','ASCII Art','ASCII 艺术字','ASCII art text generator','ASCII 艺术字生成器'),
  p3('number-sum','➕','text','Number Sum','数值求和','Sum numbers from multi-line input','多行数值求和'),
  p3('text-shuffle','🔀','text','Text Shuffle','文本打乱','Randomly shuffle lines','随机打乱行顺序'),
  p3('sequence-gen','🔢','text','Sequence Generator','序列号生成器','Sequence number generator','序列号生成器'),
  p3('vertical-text','📝','text','Vertical Text','竖排文字','Vertical text layout','文字竖排生成'),
  p3('text-spacer','⬜','text','Text Spacer','文字间隔','Insert characters between each character','在每个字符间插入字符'),
  p3('random-chinese','🀄','text','Random Chinese','随机汉字','Random Chinese character generator','随机汉字生成器'),
  p3('text-column','📊','text','Text Column Extract','文本按列截取','Column-based text extraction','按列截取文本'),
  p3('text-length-filter','📏','text','Text Length Filter','文本长度过滤','Filter lines by length','按长度过滤文本行'),
  p3('hanzi-stroke','✍️','text','Hanzi Stroke Order','汉字笔画顺序','Chinese character stroke order','汉字笔画顺序查询'),
  p3('hanzi-stroke-count','📊','text','Hanzi Stroke Count','汉字笔画统计','Chinese character stroke count','汉字笔画数统计'),
  p3('color-text','🌈','text','Color Text','彩色文字','Colorful/rainbow text HTML generator','彩色/彩虹文字生成'),
];

export const TOOL_REGISTRY: ToolMeta[] = [
  {
    slug: 'json-formatter',
    icon: '{}',
    category: 'json',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Formatter',
      'zh-cn': 'JSON 格式化',
      'zh-tw': 'JSON 格式化',
      'ja': 'JSON フォーマッター',
      'ko': 'JSON 포매터',
      'es': 'Formateador JSON',
      'fr': 'Formateur JSON',
      'de': 'JSON-Formatierer',
      'pt': 'Formatador JSON',
      'ru': 'Форматировщик JSON',
    },
    description: {
      'en': 'Format and validate JSON data with syntax highlighting',
      'zh-cn': '格式化并验证 JSON 数据，支持语法高亮',
      'zh-tw': '格式化並驗證 JSON 資料，支援語法高亮',
      'ja': 'JSONデータをフォーマットして検証し、シンタックスハイライトを表示',
      'ko': '구문 강조와 함께 JSON 데이터를 포맷하고 유효성 검사',
      'es': 'Formatea y valida datos JSON con resaltado de sintaxis',
      'fr': 'Formatez et validez des données JSON avec coloration syntaxique',
      'de': 'JSON-Daten formatieren und validieren mit Syntaxhervorhebung',
      'pt': 'Formate e valide dados JSON com destaque de sintaxe',
      'ru': 'Форматирование и проверка данных JSON с подсветкой синтаксиса',
    },
  },
  {
    slug: 'base64',
    icon: '🔐',
    category: 'encoding',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Base64 Encoder/Decoder',
      'zh-cn': 'Base64 编码解码',
      'zh-tw': 'Base64 編碼解碼',
      'ja': 'Base64 エンコード/デコード',
      'ko': 'Base64 인코더/디코더',
      'es': 'Codificador/Decodificador Base64',
      'fr': 'Encodeur/Décodeur Base64',
      'de': 'Base64-Encoder/Decoder',
      'pt': 'Codificador/Decodificador Base64',
      'ru': 'Кодировщик/Декодировщик Base64',
    },
    description: {
      'en': 'Encode and decode text using Base64 with URL-safe variant support',
      'zh-cn': '使用 Base64 对文本进行编码和解码，支持 URL 安全变体',
      'zh-tw': '使用 Base64 對文字進行編碼和解碼，支援 URL 安全變體',
      'ja': 'Base64でテキストをエンコード・デコード、URLセーフ変換対応',
      'ko': 'Base64로 텍스트를 인코딩 및 디코딩, URL 안전 변환 지원',
      'es': 'Codifica y decodifica texto usando Base64 con soporte de variante segura para URL',
      'fr': 'Encodez et décodez du texte en Base64 avec prise en charge de la variante URL-safe',
      'de': 'Text mit Base64 kodieren und dekodieren, mit URL-sicherer Variante',
      'pt': 'Codifique e decodifique texto usando Base64 com suporte a variante segura para URL',
      'ru': 'Кодирование и декодирование текста в Base64 с поддержкой URL-безопасного варианта',
    },
  },
  {
    slug: 'word-counter',
    icon: 'Aa',
    category: 'text',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Word Counter',
      'zh-cn': '字符统计',
      'zh-tw': '字元統計',
      'ja': '文字カウンター',
      'ko': '단어 카운터',
      'es': 'Contador de palabras',
      'fr': 'Compteur de mots',
      'de': 'Wortzähler',
      'pt': 'Contador de palavras',
      'ru': 'Счётчик слов',
    },
    description: {
      'en': 'Count characters, words, and lines in your text',
      'zh-cn': '统计文本中的字符数、单词数和行数',
      'zh-tw': '統計文字中的字元數、單詞數和行數',
      'ja': 'テキストの文字数、単語数、行数をカウント',
      'ko': '텍스트의 문자 수, 단어 수, 줄 수를 계산',
      'es': 'Cuenta caracteres, palabras y líneas en tu texto',
      'fr': 'Comptez les caractères, mots et lignes dans votre texte',
      'de': 'Zeichen, Wörter und Zeilen in Ihrem Text zählen',
      'pt': 'Conte caracteres, palavras e linhas no seu texto',
      'ru': 'Подсчёт символов, слов и строк в тексте',
    },
  },
  {
    slug: 'url-encoder',
    icon: '🔗',
    category: 'encoding',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'URL Encoder/Decoder',
      'zh-cn': 'URL 编码解码',
      'zh-tw': 'URL 編碼解碼',
      'ja': 'URLエンコード/デコード',
      'ko': 'URL 인코더/디코더',
      'es': 'Codificador/Decodificador URL',
      'fr': 'Encodeur/Décodeur URL',
      'de': 'URL-Encoder/Decoder',
      'pt': 'Codificador/Decodificador URL',
      'ru': 'Кодировщик/Декодировщик URL',
    },
    description: {
      'en': 'Encode and decode URLs with encodeURIComponent and encodeURI modes',
      'zh-cn': '使用 encodeURIComponent 和 encodeURI 模式对 URL 进行编码和解码',
      'zh-tw': '使用 encodeURIComponent 和 encodeURI 模式對 URL 進行編碼和解碼',
      'ja': 'encodeURIComponentとencodeURIモードでURLをエンコード・デコード',
      'ko': 'encodeURIComponent 및 encodeURI 모드로 URL 인코딩 및 디코딩',
      'es': 'Codifica y decodifica URLs con modos encodeURIComponent y encodeURI',
      'fr': 'Encodez et décodez des URLs avec les modes encodeURIComponent et encodeURI',
      'de': 'URLs mit encodeURIComponent- und encodeURI-Modi kodieren und dekodieren',
      'pt': 'Codifique e decodifique URLs com modos encodeURIComponent e encodeURI',
      'ru': 'Кодирование и декодирование URL с режимами encodeURIComponent и encodeURI',
    },
  },
  {
    slug: 'timestamp',
    icon: '⏰',
    category: 'converter',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Unix Timestamp Converter',
      'zh-cn': 'Unix 时间戳转换',
      'zh-tw': 'Unix 時間戳轉換',
      'ja': 'Unixタイムスタンプ変換',
      'ko': 'Unix 타임스탬프 변환',
      'es': 'Convertidor de marca de tiempo Unix',
      'fr': 'Convertisseur de timestamp Unix',
      'de': 'Unix-Zeitstempel-Konverter',
      'pt': 'Conversor de timestamp Unix',
      'ru': 'Конвертер временных меток Unix',
    },
    description: {
      'en': 'Convert between Unix timestamps and human-readable dates with timezone support',
      'zh-cn': '在 Unix 时间戳和可读日期之间互转，支持时区选择',
      'zh-tw': '在 Unix 時間戳和可讀日期之間互轉，支援時區選擇',
      'ja': 'Unixタイムスタンプと日付を相互変換、タイムゾーン対応',
      'ko': 'Unix 타임스탬프와 날짜 간 변환, 시간대 지원',
      'es': 'Convierte entre marcas de tiempo Unix y fechas legibles con soporte de zona horaria',
      'fr': 'Convertissez entre les timestamps Unix et les dates lisibles avec prise en charge des fuseaux horaires',
      'de': 'Konvertieren Sie zwischen Unix-Zeitstempeln und lesbaren Daten mit Zeitzonen-Unterstützung',
      'pt': 'Converta entre timestamps Unix e datas legíveis com suporte a fuso horário',
      'ru': 'Конвертация между временными метками Unix и читаемыми датами с поддержкой часовых поясов',
    },
  },
  {
    slug: 'json-minify',
    icon: '📦',
    category: 'json',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Minify & Escape',
      'zh-cn': 'JSON 压缩与转义',
      'zh-tw': 'JSON 壓縮與轉義',
      'ja': 'JSON圧縮・エスケープ',
      'ko': 'JSON 압축 및 이스케이프',
      'es': 'Minificar y escapar JSON',
      'fr': 'Minifier et échapper JSON',
      'de': 'JSON-Minifizierung & Escape',
      'pt': 'Minificar e escapar JSON',
      'ru': 'Минификация и экранирование JSON',
    },
    description: {
      'en': 'Minify, escape, and unescape JSON data',
      'zh-cn': '压缩、转义和反转义 JSON 数据',
      'zh-tw': '壓縮、轉義和反轉義 JSON 資料',
      'ja': 'JSONデータの圧縮・エスケープ・アンエスケープ',
      'ko': 'JSON 데이터 압축, 이스케이프 및 언이스케이프',
      'es': 'Minifica, escapa y desescapa datos JSON',
      'fr': 'Minifiez, échappez et désechappez des données JSON',
      'de': 'JSON-Daten minifizieren, escapen und unescapen',
      'pt': 'Minifique, escape e unescape dados JSON',
      'ru': 'Минификация, экранирование и деэкранирование данных JSON',
    },
  },
  {
    slug: 'uuid-generator',
    icon: '🆔',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'UUID/GUID Generator',
      'zh-cn': 'UUID/GUID 生成器',
      'zh-tw': 'UUID/GUID 產生器',
      'ja': 'UUID/GUIDジェネレーター',
      'ko': 'UUID/GUID 생성기',
      'es': 'Generador UUID/GUID',
      'fr': 'Générateur UUID/GUID',
      'de': 'UUID/GUID-Generator',
      'pt': 'Gerador UUID/GUID',
      'ru': 'Генератор UUID/GUID',
    },
    description: {
      'en': 'Generate UUID v4 with batch and format options',
      'zh-cn': '生成 UUID v4，支持批量生成和格式选项',
      'zh-tw': '產生 UUID v4，支援批次產生和格式選項',
      'ja': 'UUID v4を生成、一括生成とフォーマットオプション対応',
      'ko': 'UUID v4 생성, 일괄 생성 및 형식 옵션 지원',
      'es': 'Genera UUID v4 con opciones de lote y formato',
      'fr': 'Générez des UUID v4 avec options de lot et de format',
      'de': 'UUID v4 generieren mit Batch- und Formatoptionen',
      'pt': 'Gere UUID v4 com opções de lote e formato',
      'ru': 'Генерация UUID v4 с пакетными и форматными опциями',
    },
  },
  {
    slug: 'hash-calculator',
    icon: '#️⃣',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Hash Calculator',
      'zh-cn': '哈希计算器',
      'zh-tw': '雜湊計算器',
      'ja': 'ハッシュ計算機',
      'ko': '해시 계산기',
      'es': 'Calculadora de Hash',
      'fr': 'Calculateur de Hash',
      'de': 'Hash-Rechner',
      'pt': 'Calculadora de Hash',
      'ru': 'Калькулятор хешей',
    },
    description: {
      'en': 'Calculate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes',
      'zh-cn': '计算 MD5、SHA-1、SHA-256、SHA-384、SHA-512 哈希值',
      'zh-tw': '計算 MD5、SHA-1、SHA-256、SHA-384、SHA-512 雜湊值',
      'ja': 'MD5、SHA-1、SHA-256、SHA-384、SHA-512ハッシュを計算',
      'ko': 'MD5, SHA-1, SHA-256, SHA-384, SHA-512 해시 계산',
      'es': 'Calcula hashes MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'fr': 'Calculez les hachages MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'de': 'MD5-, SHA-1-, SHA-256-, SHA-384-, SHA-512-Hashes berechnen',
      'pt': 'Calcule hashes MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'ru': 'Вычисление хешей MD5, SHA-1, SHA-256, SHA-384, SHA-512',
    },
  },
  {
    slug: 'color-converter',
    icon: '🎨',
    category: 'color',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Color Converter',
      'zh-cn': '颜色格式转换',
      'zh-tw': '顏色格式轉換',
      'ja': 'カラーコンバーター',
      'ko': '색상 변환기',
      'es': 'Convertidor de Color',
      'fr': 'Convertisseur de Couleur',
      'de': 'Farbkonverter',
      'pt': 'Conversor de Cor',
      'ru': 'Конвертер цветов',
    },
    description: {
      'en': 'Convert between HEX, RGB, HSL, HSV, and CMYK color formats',
      'zh-cn': '在 HEX、RGB、HSL、HSV 和 CMYK 颜色格式之间转换',
      'zh-tw': '在 HEX、RGB、HSL、HSV 和 CMYK 顏色格式之間轉換',
      'ja': 'HEX、RGB、HSL、HSV、CMYKカラー形式を相互変換',
      'ko': 'HEX, RGB, HSL, HSV, CMYK 색상 형식 간 변환',
      'es': 'Convierte entre formatos de color HEX, RGB, HSL, HSV y CMYK',
      'fr': 'Convertissez entre les formats de couleur HEX, RGB, HSL, HSV et CMYK',
      'de': 'Zwischen HEX-, RGB-, HSL-, HSV- und CMYK-Farbformaten konvertieren',
      'pt': 'Converta entre formatos de cor HEX, RGB, HSL, HSV e CMYK',
      'ru': 'Конвертация между форматами цветов HEX, RGB, HSL, HSV и CMYK',
    },
  },
  {
    slug: 'radix-converter',
    icon: '🔢',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Radix Converter',
      'zh-cn': '进制转换',
      'zh-tw': '進制轉換',
      'ja': '基数変換',
      'ko': '진법 변환기',
      'es': 'Convertidor de Base',
      'fr': 'Convertisseur de Base',
      'de': 'Zahlensystem-Konverter',
      'pt': 'Conversor de Base',
      'ru': 'Конвертер систем счисления',
    },
    description: {
      'en': 'Convert between binary, octal, decimal, and hexadecimal',
      'zh-cn': '在二进制、八进制、十进制和十六进制之间转换',
      'zh-tw': '在二進制、八進制、十進制和十六進制之間轉換',
      'ja': '2進数、8進数、10進数、16進数を相互変換',
      'ko': '2진수, 8진수, 10진수, 16진수 간 변환',
      'es': 'Convierte entre binario, octal, decimal y hexadecimal',
      'fr': 'Convertissez entre binaire, octal, décimal et hexadécimal',
      'de': 'Zwischen Binär, Oktal, Dezimal und Hexadezimal konvertieren',
      'pt': 'Converta entre binário, octal, decimal e hexadecimal',
      'ru': 'Конвертация между двоичной, восьмеричной, десятичной и шестнадцатеричной системами',
    },
  },
  {
    slug: 'case-converter',
    icon: 'Aa',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Case Converter',
      'zh-cn': '大小写转换',
      'zh-tw': '大小寫轉換',
      'ja': '大文字小文字変換',
      'ko': '대소문자 변환기',
      'es': 'Convertidor de Mayúsculas',
      'fr': 'Convertisseur de Casse',
      'de': 'Groß-/Kleinschreibung',
      'pt': 'Conversor de Maiúsculas',
      'ru': 'Конвертер регистра',
    },
    description: {
      'en': 'Convert text between uppercase, lowercase, title case, and more',
      'zh-cn': '在大写、小写、标题大小写等格式之间转换文本',
      'zh-tw': '在大寫、小寫、標題大小寫等格式之間轉換文字',
      'ja': 'テキストを大文字、小文字、タイトルケースなどに変換',
      'ko': '텍스트를 대문자, 소문자, 제목 대소문자 등으로 변환',
      'es': 'Convierte texto entre mayúsculas, minúsculas, título y más',
      'fr': 'Convertissez le texte entre majuscules, minuscules, casse de titre et plus',
      'de': 'Text zwischen Groß-, Klein-, Titelschreibung und mehr konvertieren',
      'pt': 'Converta texto entre maiúsculas, minúsculas, título e mais',
      'ru': 'Конвертация текста между верхним, нижним регистром, заглавными и другими',
    },
  },
  {
    slug: 'password-generator',
    icon: '🔑',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Password Generator',
      'zh-cn': '随机密码生成器',
      'zh-tw': '隨機密碼產生器',
      'ja': 'パスワードジェネレーター',
      'ko': '비밀번호 생성기',
      'es': 'Generador de Contraseñas',
      'fr': 'Générateur de Mots de Passe',
      'de': 'Passwort-Generator',
      'pt': 'Gerador de Senhas',
      'ru': 'Генератор паролей',
    },
    description: {
      'en': 'Generate secure random passwords with customizable options',
      'zh-cn': '生成安全的随机密码，支持自定义选项',
      'zh-tw': '產生安全的隨機密碼，支援自訂選項',
      'ja': 'カスタマイズ可能なオプションで安全なランダムパスワードを生成',
      'ko': '사용자 정의 옵션으로 안전한 랜덤 비밀번호 생성',
      'es': 'Genera contraseñas aleatorias seguras con opciones personalizables',
      'fr': 'Générez des mots de passe aléatoires sécurisés avec des options personnalisables',
      'de': 'Sichere zufällige Passwörter mit anpassbaren Optionen generieren',
      'pt': 'Gere senhas aleatórias seguras com opções personalizáveis',
      'ru': 'Генерация безопасных случайных паролей с настраиваемыми параметрами',
    },
  },
  {
    slug: 'json-sort',
    icon: '🔤',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Sort',
      'zh-cn': 'JSON 排序',
      'zh-tw': 'JSON 排序',
      'ja': 'JSONソート',
      'ko': 'JSON 정렬',
      'es': 'Ordenar JSON',
      'fr': 'Tri JSON',
      'de': 'JSON-Sortierung',
      'pt': 'Ordenar JSON',
      'ru': 'Сортировка JSON',
    },
    description: {
      'en': 'Sort JSON object keys alphabetically in ascending or descending order',
      'zh-cn': '按字母顺序对 JSON 对象键进行升序或降序排序',
      'zh-tw': '按字母順序對 JSON 物件鍵進行升序或降序排序',
      'ja': 'JSONオブジェクトのキーをアルファベット順に昇順または降順でソート',
      'ko': 'JSON 객체 키를 알파벳순으로 오름차순 또는 내림차순 정렬',
      'es': 'Ordena las claves de objetos JSON alfabéticamente en orden ascendente o descendente',
      'fr': 'Triez les clés des objets JSON par ordre alphabétique croissant ou décroissant',
      'de': 'JSON-Objektschlüssel alphabetisch aufsteigend oder absteigend sortieren',
      'pt': 'Ordene as chaves de objetos JSON alfabeticamente em ordem crescente ou decrescente',
      'ru': 'Сортировка ключей объектов JSON по алфавиту в порядке возрастания или убывания',
    },
  },
  {
    slug: 'regex-tester',
    icon: '🔍',
    category: 'misc',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Regex Tester',
      'zh-cn': '正则表达式测试器',
      'zh-tw': '正規表達式測試器',
      'ja': '正規表現テスター',
      'ko': '정규식 테스터',
      'es': 'Probador de Regex',
      'fr': 'Testeur de Regex',
      'de': 'Regex-Tester',
      'pt': 'Testador de Regex',
      'ru': 'Тестер регулярных выражений',
    },
    description: {
      'en': 'Test regular expressions with real-time matching and highlighting',
      'zh-cn': '实时匹配和高亮显示测试正则表达式',
      'zh-tw': '即時匹配和高亮顯示測試正規表達式',
      'ja': 'リアルタイムマッチングとハイライトで正規表現をテスト',
      'ko': '실시간 매칭 및 하이라이트로 정규식 테스트',
      'es': 'Prueba expresiones regulares con coincidencia y resaltado en tiempo real',
      'fr': 'Testez des expressions régulières avec correspondance et surlignage en temps réel',
      'de': 'Reguläre Ausdrücke mit Echtzeit-Matching und Hervorhebung testen',
      'pt': 'Teste expressões regulares com correspondência e destaque em tempo real',
      'ru': 'Тестирование регулярных выражений с сопоставлением и подсветкой в реальном времени',
    },
  },
  {
    slug: 'qrcode',
    icon: '📱',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'QR Code Generator',
      'zh-cn': '二维码生成器',
      'zh-tw': 'QR Code 產生器',
      'ja': 'QRコードジェネレーター',
      'ko': 'QR 코드 생성기',
      'es': 'Generador de Código QR',
      'fr': 'Générateur de QR Code',
      'de': 'QR-Code-Generator',
      'pt': 'Gerador de QR Code',
      'ru': 'Генератор QR-кодов',
    },
    description: {
      'en': 'Generate QR codes from text with customizable size and colors',
      'zh-cn': '从文本生成二维码，支持自定义大小和颜色',
      'zh-tw': '從文字產生 QR Code，支援自訂大小和顏色',
      'ja': 'テキストからQRコードを生成、サイズと色のカスタマイズ対応',
      'ko': '텍스트에서 QR 코드 생성, 크기 및 색상 사용자 정의 지원',
      'es': 'Genera códigos QR desde texto con tamaño y colores personalizables',
      'fr': 'Générez des QR codes à partir de texte avec taille et couleurs personnalisables',
      'de': 'QR-Codes aus Text mit anpassbarer Größe und Farben generieren',
      'pt': 'Gere QR codes a partir de texto com tamanho e cores personalizáveis',
      'ru': 'Генерация QR-кодов из текста с настраиваемым размером и цветами',
    },
  },
  {
    slug: 'json-converter',
    icon: '🔄',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Converter',
      'zh-cn': 'JSON 格式互转',
      'zh-tw': 'JSON 格式互轉',
      'ja': 'JSON コンバーター',
      'ko': 'JSON 변환기',
      'es': 'Convertidor JSON',
      'fr': 'Convertisseur JSON',
      'de': 'JSON-Konverter',
      'pt': 'Conversor JSON',
      'ru': 'Конвертер JSON',
    },
    description: {
      'en': 'Convert between JSON, YAML, XML, TOML, and CSV formats',
      'zh-cn': '在 JSON、YAML、XML、TOML 和 CSV 格式之间互相转换',
      'zh-tw': '在 JSON、YAML、XML、TOML 和 CSV 格式之間互相轉換',
      'ja': 'JSON、YAML、XML、TOML、CSV形式を相互変換',
      'ko': 'JSON, YAML, XML, TOML, CSV 형식 간 변환',
      'es': 'Convierte entre formatos JSON, YAML, XML, TOML y CSV',
      'fr': 'Convertissez entre les formats JSON, YAML, XML, TOML et CSV',
      'de': 'Zwischen JSON-, YAML-, XML-, TOML- und CSV-Formaten konvertieren',
      'pt': 'Converta entre formatos JSON, YAML, XML, TOML e CSV',
      'ru': 'Конвертация между форматами JSON, YAML, XML, TOML и CSV',
    },
  },
  {
    slug: 'json-to-class',
    icon: '📝',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON to Class',
      'zh-cn': 'JSON 转实体类',
      'zh-tw': 'JSON 轉實體類',
      'ja': 'JSON → クラス変換',
      'ko': 'JSON → 클래스 변환',
      'es': 'JSON a Clase',
      'fr': 'JSON vers Classe',
      'de': 'JSON zu Klasse',
      'pt': 'JSON para Classe',
      'ru': 'JSON в класс',
    },
    description: {
      'en': 'Generate TypeScript, Java, Go, Python, and C# classes from JSON',
      'zh-cn': '从 JSON 生成 TypeScript、Java、Go、Python、C# 类型定义',
      'zh-tw': '從 JSON 產生 TypeScript、Java、Go、Python、C# 型別定義',
      'ja': 'JSONからTypeScript、Java、Go、Python、C#のクラスを生成',
      'ko': 'JSON에서 TypeScript, Java, Go, Python, C# 클래스 생성',
      'es': 'Genera clases TypeScript, Java, Go, Python y C# desde JSON',
      'fr': 'Générez des classes TypeScript, Java, Go, Python et C# à partir de JSON',
      'de': 'TypeScript-, Java-, Go-, Python- und C#-Klassen aus JSON generieren',
      'pt': 'Gere classes TypeScript, Java, Go, Python e C# a partir de JSON',
      'ru': 'Генерация классов TypeScript, Java, Go, Python и C# из JSON',
    },
  },
  {
    slug: 'jwt-decoder',
    icon: '🔓',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JWT Decoder',
      'zh-cn': 'JWT 解码器',
      'zh-tw': 'JWT 解碼器',
      'ja': 'JWT デコーダー',
      'ko': 'JWT 디코더',
      'es': 'Decodificador JWT',
      'fr': 'Décodeur JWT',
      'de': 'JWT-Decoder',
      'pt': 'Decodificador JWT',
      'ru': 'Декодер JWT',
    },
    description: {
      'en': 'Decode JWT tokens to view header, payload, and signature',
      'zh-cn': '解码 JWT Token，查看 Header、Payload 和 Signature',
      'zh-tw': '解碼 JWT Token，查看 Header、Payload 和 Signature',
      'ja': 'JWTトークンをデコードしてヘッダー、ペイロード、署名を表示',
      'ko': 'JWT 토큰을 디코딩하여 헤더, 페이로드, 서명 확인',
      'es': 'Decodifica tokens JWT para ver encabezado, carga útil y firma',
      'fr': 'Décodez les tokens JWT pour voir l\'en-tête, la charge utile et la signature',
      'de': 'JWT-Token dekodieren, um Header, Payload und Signatur anzuzeigen',
      'pt': 'Decodifique tokens JWT para ver cabeçalho, payload e assinatura',
      'ru': 'Декодирование JWT-токенов для просмотра заголовка, полезной нагрузки и подписи',
    },
  },
  {
    slug: 'json-schema',
    icon: '📋',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Schema Generator',
      'zh-cn': 'JSON Schema 生成器',
      'zh-tw': 'JSON Schema 產生器',
      'ja': 'JSON Schema ジェネレーター',
      'ko': 'JSON Schema 생성기',
      'es': 'Generador de JSON Schema',
      'fr': 'Générateur de JSON Schema',
      'de': 'JSON-Schema-Generator',
      'pt': 'Gerador de JSON Schema',
      'ru': 'Генератор JSON Schema',
    },
    description: {
      'en': 'Generate JSON Schema (Draft-07) from JSON data',
      'zh-cn': '从 JSON 数据自动生成 JSON Schema（Draft-07）',
      'zh-tw': '從 JSON 資料自動產生 JSON Schema（Draft-07）',
      'ja': 'JSONデータからJSON Schema（Draft-07）を自動生成',
      'ko': 'JSON 데이터에서 JSON Schema(Draft-07) 자동 생성',
      'es': 'Genera JSON Schema (Draft-07) a partir de datos JSON',
      'fr': 'Générez un JSON Schema (Draft-07) à partir de données JSON',
      'de': 'JSON Schema (Draft-07) aus JSON-Daten generieren',
      'pt': 'Gere JSON Schema (Draft-07) a partir de dados JSON',
      'ru': 'Генерация JSON Schema (Draft-07) из данных JSON',
    },
  },
  {
    slug: 'unicode-converter', icon: '🔤', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Unicode Converter', 'zh-cn': 'Unicode 转换', 'zh-tw': 'Unicode 轉換', 'ja': 'Unicode変換', 'ko': 'Unicode 변환기', 'es': 'Convertidor Unicode', 'fr': 'Convertisseur Unicode', 'de': 'Unicode-Konverter', 'pt': 'Conversor Unicode', 'ru': 'Конвертер Unicode' },
    description: { 'en': 'Convert between Unicode escape sequences and text', 'zh-cn': 'Unicode \\uXXXX 转义与文本互转', 'zh-tw': 'Unicode \\uXXXX 轉義與文字互轉', 'ja': 'Unicodeエスケープシーケンスとテキストを相互変換', 'ko': 'Unicode 이스케이프 시퀀스와 텍스트 간 변환', 'es': 'Convierte entre secuencias de escape Unicode y texto', 'fr': 'Convertissez entre séquences d\'échappement Unicode et texte', 'de': 'Zwischen Unicode-Escape-Sequenzen und Text konvertieren', 'pt': 'Converta entre sequências de escape Unicode e texto', 'ru': 'Конвертация между escape-последовательностями Unicode и текстом' },
  },
  {
    slug: 'symmetric-cipher', icon: '🔒', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'AES Encrypt/Decrypt', 'zh-cn': 'AES 加密解密', 'zh-tw': 'AES 加密解密', 'ja': 'AES暗号化/復号化', 'ko': 'AES 암호화/복호화', 'es': 'Cifrado/Descifrado AES', 'fr': 'Chiffrement/Déchiffrement AES', 'de': 'AES-Verschlüsselung/Entschlüsselung', 'pt': 'Criptografia/Descriptografia AES', 'ru': 'AES шифрование/дешифрование' },
    description: { 'en': 'Encrypt and decrypt text using AES-CBC with Web Crypto API', 'zh-cn': '使用 AES-CBC 和 Web Crypto API 加密解密文本', 'zh-tw': '使用 AES-CBC 和 Web Crypto API 加密解密文字', 'ja': 'Web Crypto APIを使用したAES-CBCテキスト暗号化/復号化', 'ko': 'Web Crypto API를 사용한 AES-CBC 텍스트 암호화/복호화', 'es': 'Cifra y descifra texto usando AES-CBC con Web Crypto API', 'fr': 'Chiffrez et déchiffrez du texte avec AES-CBC via Web Crypto API', 'de': 'Text mit AES-CBC über Web Crypto API verschlüsseln und entschlüsseln', 'pt': 'Criptografe e descriptografe texto usando AES-CBC com Web Crypto API', 'ru': 'Шифрование и дешифрование текста с помощью AES-CBC через Web Crypto API' },
  },
  {
    slug: 'html-escape', icon: '🏷️', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'HTML Escape/Unescape', 'zh-cn': 'HTML 转义', 'zh-tw': 'HTML 轉義', 'ja': 'HTMLエスケープ', 'ko': 'HTML 이스케이프', 'es': 'Escape/Unescape HTML', 'fr': 'Échappement HTML', 'de': 'HTML-Escape', 'pt': 'Escape HTML', 'ru': 'HTML экранирование' },
    description: { 'en': 'Encode and decode HTML entities like &lt; &gt; &amp;', 'zh-cn': 'HTML 实体编码解码（&lt; &gt; &amp; 等）', 'zh-tw': 'HTML 實體編碼解碼（&lt; &gt; &amp; 等）', 'ja': 'HTMLエンティティのエンコード・デコード（&lt; &gt; &amp;など）', 'ko': 'HTML 엔티티 인코딩/디코딩 (&lt; &gt; &amp; 등)', 'es': 'Codifica y decodifica entidades HTML como &lt; &gt; &amp;', 'fr': 'Encodez et décodez les entités HTML comme &lt; &gt; &amp;', 'de': 'HTML-Entitäten wie &lt; &gt; &amp; kodieren und dekodieren', 'pt': 'Codifique e decodifique entidades HTML como &lt; &gt; &amp;', 'ru': 'Кодирование и декодирование HTML-сущностей (&lt; &gt; &amp; и др.)' },
  },
  {
    slug: 'file-base64', icon: '📁', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'File to Base64', 'zh-cn': '文件转 Base64', 'zh-tw': '檔案轉 Base64', 'ja': 'ファイル→Base64変換', 'ko': '파일 → Base64 변환', 'es': 'Archivo a Base64', 'fr': 'Fichier vers Base64', 'de': 'Datei zu Base64', 'pt': 'Arquivo para Base64', 'ru': 'Файл в Base64' },
    description: { 'en': 'Convert files to Base64 and Data URI, or decode Base64 to file', 'zh-cn': '文件上传转 Base64 + Data URI，Base64 还原文件下载', 'zh-tw': '檔案上傳轉 Base64 + Data URI，Base64 還原檔案下載', 'ja': 'ファイルをBase64・Data URIに変換、Base64からファイルに復元', 'ko': '파일을 Base64 및 Data URI로 변환, Base64에서 파일 복원', 'es': 'Convierte archivos a Base64 y Data URI, o decodifica Base64 a archivo', 'fr': 'Convertissez des fichiers en Base64 et Data URI, ou décodez Base64 en fichier', 'de': 'Dateien in Base64 und Data URI konvertieren oder Base64 in Datei dekodieren', 'pt': 'Converta arquivos para Base64 e Data URI, ou decodifique Base64 para arquivo', 'ru': 'Конвертация файлов в Base64 и Data URI, или декодирование Base64 в файл' },
  },
  {
    slug: 'text-dedup', icon: '🔃', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Text Deduplicator', 'zh-cn': '文本去重', 'zh-tw': '文字去重', 'ja': 'テキスト重複削除', 'ko': '텍스트 중복 제거', 'es': 'Deduplicador de texto', 'fr': 'Dédoublonneur de texte', 'de': 'Text-Deduplizierer', 'pt': 'Deduplicador de texto', 'ru': 'Удаление дубликатов текста' },
    description: { 'en': 'Remove duplicate lines with case sensitive/insensitive options', 'zh-cn': '去除重复行，支持大小写敏感/不敏感，显示行数对比', 'zh-tw': '去除重複行，支援大小寫敏感/不敏感，顯示行數對比', 'ja': '重複行を削除、大文字小文字の区別オプション付き', 'ko': '중복 줄 제거, 대소문자 구분/무시 옵션 지원', 'es': 'Elimina líneas duplicadas con opciones de distinción de mayúsculas', 'fr': 'Supprimez les lignes en double avec options de sensibilité à la casse', 'de': 'Doppelte Zeilen entfernen mit Groß-/Kleinschreibungsoptionen', 'pt': 'Remova linhas duplicadas com opções de distinção de maiúsculas', 'ru': 'Удаление дублирующихся строк с учётом/без учёта регистра' },
  },
  {
    slug: 'text-sort', icon: '📊', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Text Sorter', 'zh-cn': '文本排序', 'zh-tw': '文字排序', 'ja': 'テキストソート', 'ko': '텍스트 정렬', 'es': 'Ordenador de texto', 'fr': 'Trieur de texte', 'de': 'Text-Sortierer', 'pt': 'Ordenador de texto', 'ru': 'Сортировка текста' },
    description: { 'en': 'Sort lines alphabetically, numerically, by length, or randomly', 'zh-cn': '按字母/数字/长度/随机排序文本行，支持升序降序', 'zh-tw': '按字母/數字/長度/隨機排序文字行，支援升序降序', 'ja': 'テキスト行をアルファベット順・数値順・長さ順・ランダムにソート', 'ko': '텍스트 줄을 알파벳/숫자/길이/랜덤으로 정렬', 'es': 'Ordena líneas alfabéticamente, numéricamente, por longitud o aleatoriamente', 'fr': 'Triez les lignes par ordre alphabétique, numérique, longueur ou aléatoire', 'de': 'Zeilen alphabetisch, numerisch, nach Länge oder zufällig sortieren', 'pt': 'Ordene linhas alfabeticamente, numericamente, por comprimento ou aleatoriamente', 'ru': 'Сортировка строк по алфавиту, числам, длине или случайно' },
  },
  {
    slug: 'text-trim', icon: '✂️', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Text Trimmer', 'zh-cn': '空行空白处理', 'zh-tw': '空行空白處理', 'ja': 'テキストトリマー', 'ko': '텍스트 트리머', 'es': 'Recortador de texto', 'fr': 'Nettoyeur de texte', 'de': 'Text-Trimmer', 'pt': 'Aparador de texto', 'ru': 'Очистка текста' },
    description: { 'en': 'Remove empty lines, trim whitespace, merge blank lines, or join to one line', 'zh-cn': '去空行、trim 空白、合并空行、合并为一行', 'zh-tw': '去空行、trim 空白、合併空行、合併為一行', 'ja': '空行削除、空白トリム、空行マージ、一行に結合', 'ko': '빈 줄 제거, 공백 제거, 빈 줄 병합, 한 줄로 합치기', 'es': 'Elimina líneas vacías, recorta espacios, fusiona líneas en blanco o une en una línea', 'fr': 'Supprimez les lignes vides, coupez les espaces, fusionnez les lignes blanches ou joignez en une ligne', 'de': 'Leere Zeilen entfernen, Leerzeichen trimmen, Leerzeilen zusammenführen oder in eine Zeile verbinden', 'pt': 'Remova linhas vazias, apare espaços, mescle linhas em branco ou junte em uma linha', 'ru': 'Удаление пустых строк, обрезка пробелов, объединение пустых строк или в одну строку' },
  },
  {
    slug: 'naming-converter', icon: '🐫', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Naming Converter', 'zh-cn': '变量命名转换', 'zh-tw': '變數命名轉換', 'ja': '命名規則変換', 'ko': '네이밍 변환기', 'es': 'Convertidor de nombres', 'fr': 'Convertisseur de nommage', 'de': 'Namenskonverter', 'pt': 'Conversor de nomes', 'ru': 'Конвертер именования' },
    description: { 'en': 'Convert between camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'zh-cn': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKE 互转', 'zh-tw': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKE 互轉', 'ja': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKEを相互変換', 'ko': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKE 간 변환', 'es': 'Convierte entre camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'fr': 'Convertissez entre camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'de': 'Zwischen camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE konvertieren', 'pt': 'Converta entre camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'ru': 'Конвертация между camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE' },
  },
  {
    slug: 'js-formatter', icon: '📄', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'JS/HTML Formatter', 'zh-cn': 'JS/HTML 格式化', 'zh-tw': 'JS/HTML 格式化', 'ja': 'JS/HTMLフォーマッター', 'ko': 'JS/HTML 포매터', 'es': 'Formateador JS/HTML', 'fr': 'Formateur JS/HTML', 'de': 'JS/HTML-Formatierer', 'pt': 'Formatador JS/HTML', 'ru': 'Форматировщик JS/HTML' },
    description: { 'en': 'Beautify and minify JavaScript and HTML code', 'zh-cn': 'JavaScript/HTML 代码格式化和压缩', 'zh-tw': 'JavaScript/HTML 程式碼格式化和壓縮', 'ja': 'JavaScript/HTMLコードの整形と圧縮', 'ko': 'JavaScript/HTML 코드 정리 및 압축', 'es': 'Embellece y minifica código JavaScript y HTML', 'fr': 'Embellissez et minifiez le code JavaScript et HTML', 'de': 'JavaScript- und HTML-Code verschönern und minifizieren', 'pt': 'Embeleze e minifique código JavaScript e HTML', 'ru': 'Форматирование и минификация кода JavaScript и HTML' },
  },
  {
    slug: 'css-formatter', icon: '🎨', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'CSS Formatter', 'zh-cn': 'CSS 格式化', 'zh-tw': 'CSS 格式化', 'ja': 'CSSフォーマッター', 'ko': 'CSS 포매터', 'es': 'Formateador CSS', 'fr': 'Formateur CSS', 'de': 'CSS-Formatierer', 'pt': 'Formatador CSS', 'ru': 'Форматировщик CSS' },
    description: { 'en': 'Beautify and minify CSS code', 'zh-cn': 'CSS 代码格式化和压缩', 'zh-tw': 'CSS 程式碼格式化和壓縮', 'ja': 'CSSコードの整形と圧縮', 'ko': 'CSS 코드 정리 및 압축', 'es': 'Embellece y minifica código CSS', 'fr': 'Embellissez et minifiez le code CSS', 'de': 'CSS-Code verschönern und minifizieren', 'pt': 'Embeleze e minifique código CSS', 'ru': 'Форматирование и минификация кода CSS' },
  },
  {
    slug: 'sql-formatter', icon: '🗃️', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'SQL Formatter', 'zh-cn': 'SQL 格式化', 'zh-tw': 'SQL 格式化', 'ja': 'SQLフォーマッター', 'ko': 'SQL 포매터', 'es': 'Formateador SQL', 'fr': 'Formateur SQL', 'de': 'SQL-Formatierer', 'pt': 'Formatador SQL', 'ru': 'Форматировщик SQL' },
    description: { 'en': 'Format SQL with keyword uppercasing and indentation', 'zh-cn': 'SQL 关键词大写 + 缩进格式化', 'zh-tw': 'SQL 關鍵詞大寫 + 縮排格式化', 'ja': 'SQLキーワード大文字化とインデント整形', 'ko': 'SQL 키워드 대문자화 및 들여쓰기 포맷', 'es': 'Formatea SQL con palabras clave en mayúsculas e indentación', 'fr': 'Formatez SQL avec mots-clés en majuscules et indentation', 'de': 'SQL mit Schlüsselwort-Großschreibung und Einrückung formatieren', 'pt': 'Formate SQL com palavras-chave em maiúsculas e indentação', 'ru': 'Форматирование SQL с заглавными ключевыми словами и отступами' },
  },
  {
    slug: 'xml-formatter', icon: '📰', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'XML Formatter', 'zh-cn': 'XML 格式化', 'zh-tw': 'XML 格式化', 'ja': 'XMLフォーマッター', 'ko': 'XML 포매터', 'es': 'Formateador XML', 'fr': 'Formateur XML', 'de': 'XML-Formatierer', 'pt': 'Formatador XML', 'ru': 'Форматировщик XML' },
    description: { 'en': 'Format and minify XML documents', 'zh-cn': 'XML 文档格式化和压缩', 'zh-tw': 'XML 文件格式化和壓縮', 'ja': 'XMLドキュメントの整形と圧縮', 'ko': 'XML 문서 정리 및 압축', 'es': 'Formatea y minifica documentos XML', 'fr': 'Formatez et minifiez des documents XML', 'de': 'XML-Dokumente formatieren und minifizieren', 'pt': 'Formate e minifique documentos XML', 'ru': 'Форматирование и минификация XML-документов' },
  },
  {
    slug: 'properties-yaml', icon: '⚙️', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Properties ↔ YAML', 'zh-cn': 'Properties 转 YAML', 'zh-tw': 'Properties 轉 YAML', 'ja': 'Properties ↔ YAML変換', 'ko': 'Properties ↔ YAML 변환', 'es': 'Properties ↔ YAML', 'fr': 'Properties ↔ YAML', 'de': 'Properties ↔ YAML', 'pt': 'Properties ↔ YAML', 'ru': 'Properties ↔ YAML' },
    description: { 'en': 'Convert between .properties and YAML formats with nested key support', 'zh-cn': '.properties 与 YAML 格式互转，支持嵌套键', 'zh-tw': '.properties 與 YAML 格式互轉，支援巢狀鍵', 'ja': '.propertiesとYAML形式を相互変換、ネストキー対応', 'ko': '.properties와 YAML 형식 간 변환, 중첩 키 지원', 'es': 'Convierte entre formatos .properties y YAML con soporte de claves anidadas', 'fr': 'Convertissez entre les formats .properties et YAML avec support des clés imbriquées', 'de': 'Zwischen .properties- und YAML-Formaten mit verschachtelten Schlüsseln konvertieren', 'pt': 'Converta entre formatos .properties e YAML com suporte a chaves aninhadas', 'ru': 'Конвертация между форматами .properties и YAML с поддержкой вложенных ключей' },
  },
  {
    slug: 'json-to-sql', icon: '💾', category: 'json', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'JSON to SQL', 'zh-cn': 'JSON 转 SQL', 'zh-tw': 'JSON 轉 SQL', 'ja': 'JSON → SQL変換', 'ko': 'JSON → SQL 변환', 'es': 'JSON a SQL', 'fr': 'JSON vers SQL', 'de': 'JSON zu SQL', 'pt': 'JSON para SQL', 'ru': 'JSON в SQL' },
    description: { 'en': 'Convert JSON arrays to SQL INSERT statements', 'zh-cn': 'JSON 数组转 SQL INSERT 语句', 'zh-tw': 'JSON 陣列轉 SQL INSERT 語句', 'ja': 'JSON配列をSQL INSERT文に変換', 'ko': 'JSON 배열을 SQL INSERT 문으로 변환', 'es': 'Convierte arrays JSON a sentencias SQL INSERT', 'fr': 'Convertissez des tableaux JSON en instructions SQL INSERT', 'de': 'JSON-Arrays in SQL INSERT-Anweisungen konvertieren', 'pt': 'Converta arrays JSON em instruções SQL INSERT', 'ru': 'Конвертация массивов JSON в SQL INSERT-запросы' },
  },
  {
    slug: 'diff-viewer', icon: '📊', category: 'misc', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Diff Viewer', 'zh-cn': '文本对比', 'zh-tw': '文字對比', 'ja': 'テキスト差分ビューア', 'ko': '텍스트 비교', 'es': 'Visor de diferencias', 'fr': 'Visualiseur de différences', 'de': 'Diff-Viewer', 'pt': 'Visualizador de diferenças', 'ru': 'Просмотр различий' },
    description: { 'en': 'Side-by-side text comparison with color-coded differences', 'zh-cn': '并排文本对比，颜色标注差异', 'zh-tw': '並排文字對比，顏色標註差異', 'ja': 'テキストを並べて比較、色分けで差異を表示', 'ko': '텍스트를 나란히 비교하고 색상으로 차이 표시', 'es': 'Comparación de texto lado a lado con diferencias codificadas por color', 'fr': 'Comparaison de texte côte à côte avec différences colorées', 'de': 'Textvergleich nebeneinander mit farbcodierten Unterschieden', 'pt': 'Comparação de texto lado a lado com diferenças codificadas por cor', 'ru': 'Сравнение текста бок о бок с цветовой маркировкой различий' },
  },
  {
    slug: 'markdown-editor', icon: '📝', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Markdown Editor', 'zh-cn': 'Markdown 编辑器', 'zh-tw': 'Markdown 編輯器', 'ja': 'Markdownエディター', 'ko': 'Markdown 편집기', 'es': 'Editor Markdown', 'fr': 'Éditeur Markdown', 'de': 'Markdown-Editor', 'pt': 'Editor Markdown', 'ru': 'Редактор Markdown' },
    description: { 'en': 'Split-view Markdown editor with live preview', 'zh-cn': '左右分栏 Markdown 编辑器，实时预览', 'zh-tw': '左右分欄 Markdown 編輯器，即時預覽', 'ja': '分割ビューMarkdownエディター、リアルタイムプレビュー', 'ko': '분할 뷰 Markdown 편집기, 실시간 미리보기', 'es': 'Editor Markdown con vista dividida y vista previa en vivo', 'fr': 'Éditeur Markdown en vue partagée avec aperçu en direct', 'de': 'Markdown-Editor mit geteilter Ansicht und Live-Vorschau', 'pt': 'Editor Markdown com visualização dividida e pré-visualização ao vivo', 'ru': 'Редактор Markdown с разделённым видом и предпросмотром' },
  },
  {
    slug: 'cron-generator', icon: '⏲️', category: 'misc', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Cron Generator', 'zh-cn': 'Cron 表达式生成器', 'zh-tw': 'Cron 表達式產生器', 'ja': 'Cron式ジェネレーター', 'ko': 'Cron 표현식 생성기', 'es': 'Generador Cron', 'fr': 'Générateur Cron', 'de': 'Cron-Generator', 'pt': 'Gerador Cron', 'ru': 'Генератор Cron' },
    description: { 'en': 'Build cron expressions with human-readable descriptions and next run times', 'zh-cn': '可视化 Cron 表达式构建器 + 人类可读描述 + 未来执行时间', 'zh-tw': '視覺化 Cron 表達式建構器 + 人類可讀描述 + 未來執行時間', 'ja': 'Cron式ビルダー、人間が読める説明と次回実行時刻', 'ko': 'Cron 표현식 빌더, 사람이 읽을 수 있는 설명 및 다음 실행 시간', 'es': 'Construye expresiones cron con descripciones legibles y próximas ejecuciones', 'fr': 'Construisez des expressions cron avec descriptions lisibles et prochaines exécutions', 'de': 'Cron-Ausdrücke mit lesbaren Beschreibungen und nächsten Ausführungszeiten erstellen', 'pt': 'Construa expressões cron com descrições legíveis e próximas execuções', 'ru': 'Создание cron-выражений с описаниями и временем следующего запуска' },
  },
  {
    slug: 'unit-converter', icon: '📏', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Unit Converter', 'zh-cn': '单位换算器', 'zh-tw': '單位換算器', 'ja': '単位変換器', 'ko': '단위 변환기', 'es': 'Convertidor de unidades', 'fr': 'Convertisseur d\'unités', 'de': 'Einheitenrechner', 'pt': 'Conversor de unidades', 'ru': 'Конвертер единиц' },
    description: { 'en': 'Convert length, temperature, weight, volume, area, and speed units', 'zh-cn': '长度/温度/重量/体积/面积/速度单位换算', 'zh-tw': '長度/溫度/重量/體積/面積/速度單位換算', 'ja': '長さ・温度・重さ・体積・面積・速度の単位変換', 'ko': '길이/온도/무게/부피/면적/속도 단위 변환', 'es': 'Convierte unidades de longitud, temperatura, peso, volumen, área y velocidad', 'fr': 'Convertissez les unités de longueur, température, poids, volume, surface et vitesse', 'de': 'Länge, Temperatur, Gewicht, Volumen, Fläche und Geschwindigkeit umrechnen', 'pt': 'Converta unidades de comprimento, temperatura, peso, volume, área e velocidade', 'ru': 'Конвертация единиц длины, температуры, веса, объёма, площади и скорости' },
  },
  {
    slug: 'filesize-converter', icon: '💾', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'File Size Converter', 'zh-cn': '文件大小换算', 'zh-tw': '檔案大小換算', 'ja': 'ファイルサイズ変換', 'ko': '파일 크기 변환기', 'es': 'Convertidor de tamaño de archivo', 'fr': 'Convertisseur de taille de fichier', 'de': 'Dateigrößen-Konverter', 'pt': 'Conversor de tamanho de arquivo', 'ru': 'Конвертер размера файлов' },
    description: { 'en': 'Convert between B, KB, MB, GB, TB, PB in binary and decimal', 'zh-cn': 'B/KB/MB/GB/TB/PB 二进制和十进制换算', 'zh-tw': 'B/KB/MB/GB/TB/PB 二進制和十進制換算', 'ja': 'B/KB/MB/GB/TB/PBの2進数・10進数変換', 'ko': 'B/KB/MB/GB/TB/PB 이진 및 십진 변환', 'es': 'Convierte entre B, KB, MB, GB, TB, PB en binario y decimal', 'fr': 'Convertissez entre B, KB, MB, GB, TB, PB en binaire et décimal', 'de': 'Zwischen B, KB, MB, GB, TB, PB in Binär und Dezimal konvertieren', 'pt': 'Converta entre B, KB, MB, GB, TB, PB em binário e decimal', 'ru': 'Конвертация между B, KB, MB, GB, TB, PB в двоичной и десятичной системах' },
  },
  {
    slug: 'random-number', icon: '🎲', category: 'math', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Random Number Generator', 'zh-cn': '随机数生成器', 'zh-tw': '隨機數產生器', 'ja': '乱数ジェネレーター', 'ko': '난수 생성기', 'es': 'Generador de números aleatorios', 'fr': 'Générateur de nombres aléatoires', 'de': 'Zufallszahlengenerator', 'pt': 'Gerador de números aleatórios', 'ru': 'Генератор случайных чисел' },
    description: { 'en': 'Generate random integers or floats with range and batch options', 'zh-cn': '随机整数/浮点数生成，支持范围和批量', 'zh-tw': '隨機整數/浮點數產生，支援範圍和批次', 'ja': '範囲とバッチオプション付きランダム整数・浮動小数点数生成', 'ko': '범위 및 일괄 옵션으로 랜덤 정수/실수 생성', 'es': 'Genera enteros o decimales aleatorios con opciones de rango y lote', 'fr': 'Générez des entiers ou décimaux aléatoires avec options de plage et lot', 'de': 'Zufällige Ganzzahlen oder Gleitkommazahlen mit Bereichs- und Batch-Optionen generieren', 'pt': 'Gere inteiros ou decimais aleatórios com opções de intervalo e lote', 'ru': 'Генерация случайных целых или дробных чисел с диапазоном и пакетными опциями' },
  },
  {
    slug: 'php-serialize', icon: '🐘', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'PHP Serialize/Unserialize', 'zh-cn': 'PHP 序列化', 'zh-tw': 'PHP 序列化', 'ja': 'PHPシリアライズ', 'ko': 'PHP 직렬화', 'es': 'Serializar/Deserializar PHP', 'fr': 'Sérialiser/Désérialiser PHP', 'de': 'PHP-Serialisierung', 'pt': 'Serializar/Desserializar PHP', 'ru': 'PHP сериализация' },
    description: { 'en': 'Convert between PHP serialized format and JSON', 'zh-cn': 'PHP 序列化格式与 JSON 互转', 'zh-tw': 'PHP 序列化格式與 JSON 互轉', 'ja': 'PHPシリアライズ形式とJSONを相互変換', 'ko': 'PHP 직렬화 형식과 JSON 간 변환', 'es': 'Convierte entre formato serializado PHP y JSON', 'fr': 'Convertissez entre le format sérialisé PHP et JSON', 'de': 'Zwischen PHP-serialisiertem Format und JSON konvertieren', 'pt': 'Converta entre formato serializado PHP e JSON', 'ru': 'Конвертация между сериализованным форматом PHP и JSON' },
  },
  // P2 CSS Tools
  {
    slug: 'css-gradient', icon: '🌈', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'CSS Gradient Generator', 'zh-cn': 'CSS 渐变生成器', 'zh-tw': 'CSS 漸層產生器', 'ja': 'CSSグラデーション生成', 'ko': 'CSS 그라디언트 생성기', 'es': 'Generador de Gradientes CSS', 'fr': 'Générateur de Dégradés CSS', 'de': 'CSS-Gradient-Generator', 'pt': 'Gerador de Gradientes CSS', 'ru': 'Генератор CSS-градиентов' },
    description: { 'en': 'Create linear and radial CSS gradients with visual editor', 'zh-cn': '可视化创建线性和径向 CSS 渐变', 'zh-tw': '視覺化建立線性和徑向 CSS 漸層', 'ja': 'ビジュアルエディターでCSS線形・放射グラデーションを作成', 'ko': '비주얼 에디터로 CSS 선형/방사형 그라디언트 생성', 'es': 'Crea gradientes CSS lineales y radiales con editor visual', 'fr': 'Créez des dégradés CSS linéaires et radiaux avec éditeur visuel', 'de': 'Lineare und radiale CSS-Gradienten mit visuellem Editor erstellen', 'pt': 'Crie gradientes CSS lineares e radiais com editor visual', 'ru': 'Создание линейных и радиальных CSS-градиентов с визуальным редактором' },
  },
  {
    slug: 'css-bezier', icon: '📈', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'CSS Bezier Curve Editor', 'zh-cn': 'CSS 贝塞尔曲线编辑器', 'zh-tw': 'CSS 貝茲曲線編輯器', 'ja': 'CSSベジェ曲線エディター', 'ko': 'CSS 베지어 곡선 편집기', 'es': 'Editor de Curvas Bézier CSS', 'fr': 'Éditeur de Courbes de Bézier CSS', 'de': 'CSS-Bézierkurven-Editor', 'pt': 'Editor de Curvas Bézier CSS', 'ru': 'Редактор кривых Безье CSS' },
    description: { 'en': 'Edit cubic-bezier curves with presets and animation preview', 'zh-cn': '编辑三次贝塞尔曲线，预设曲线和动画预览', 'zh-tw': '編輯三次貝茲曲線，預設曲線和動畫預覽', 'ja': 'プリセットとアニメーションプレビュー付きベジェ曲線編集', 'ko': '프리셋과 애니메이션 미리보기로 베지어 곡선 편집', 'es': 'Edita curvas cubic-bezier con presets y vista previa de animación', 'fr': 'Éditez des courbes cubic-bezier avec préréglages et aperçu d\'animation', 'de': 'Cubic-Bezier-Kurven mit Presets und Animationsvorschau bearbeiten', 'pt': 'Edite curvas cubic-bezier com presets e pré-visualização de animação', 'ru': 'Редактирование кривых cubic-bezier с пресетами и предпросмотром анимации' },
  },
  {
    slug: 'css-flex', icon: '📐', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'CSS Flexbox Editor', 'zh-cn': 'CSS Flex 布局编辑器', 'zh-tw': 'CSS Flex 佈局編輯器', 'ja': 'CSS Flexboxエディター', 'ko': 'CSS Flexbox 편집기', 'es': 'Editor CSS Flexbox', 'fr': 'Éditeur CSS Flexbox', 'de': 'CSS-Flexbox-Editor', 'pt': 'Editor CSS Flexbox', 'ru': 'Редактор CSS Flexbox' },
    description: { 'en': 'Visual Flexbox layout editor with live preview', 'zh-cn': '可视化 Flexbox 布局编辑器，实时预览', 'zh-tw': '視覺化 Flexbox 佈局編輯器，即時預覽', 'ja': 'ライブプレビュー付きFlexboxレイアウトエディター', 'ko': '실시간 미리보기가 있는 Flexbox 레이아웃 편집기', 'es': 'Editor visual de diseño Flexbox con vista previa en vivo', 'fr': 'Éditeur visuel de mise en page Flexbox avec aperçu en direct', 'de': 'Visueller Flexbox-Layout-Editor mit Live-Vorschau', 'pt': 'Editor visual de layout Flexbox com pré-visualização ao vivo', 'ru': 'Визуальный редактор Flexbox-макета с предпросмотром' },
  },
  {
    slug: 'css-glassmorphism', icon: '🪟', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Glassmorphism Generator', 'zh-cn': '毛玻璃效果生成器', 'zh-tw': '毛玻璃效果產生器', 'ja': 'グラスモーフィズム生成', 'ko': '글래스모피즘 생성기', 'es': 'Generador Glassmorphism', 'fr': 'Générateur Glassmorphism', 'de': 'Glassmorphism-Generator', 'pt': 'Gerador Glassmorphism', 'ru': 'Генератор Glassmorphism' },
    description: { 'en': 'Create glassmorphism effects with blur, opacity and color controls', 'zh-cn': '创建毛玻璃效果，调整模糊度、透明度和颜色', 'zh-tw': '建立毛玻璃效果，調整模糊度、透明度和顏色', 'ja': 'ぼかし・透明度・色のコントロールでグラスモーフィズム効果を作成', 'ko': '블러, 불투명도, 색상 조절로 글래스모피즘 효과 생성', 'es': 'Crea efectos glassmorphism con controles de desenfoque, opacidad y color', 'fr': 'Créez des effets glassmorphism avec contrôles de flou, opacité et couleur', 'de': 'Glassmorphism-Effekte mit Unschärfe-, Deckkraft- und Farbsteuerung erstellen', 'pt': 'Crie efeitos glassmorphism com controles de desfoque, opacidade e cor', 'ru': 'Создание эффектов glassmorphism с контролем размытия, прозрачности и цвета' },
  },
  {
    slug: 'css-neumorphism', icon: '🔘', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Neumorphism Generator', 'zh-cn': '新拟态风格生成器', 'zh-tw': '新擬態風格產生器', 'ja': 'ニューモーフィズム生成', 'ko': '뉴모피즘 생성기', 'es': 'Generador Neumorphism', 'fr': 'Générateur Neumorphism', 'de': 'Neumorphism-Generator', 'pt': 'Gerador Neumorphism', 'ru': 'Генератор Neumorphism' },
    description: { 'en': 'Create neumorphism effects with shadow distance, blur and intensity', 'zh-cn': '创建新拟态效果，调整阴影距离、模糊和强度', 'zh-tw': '建立新擬態效果，調整陰影距離、模糊和強度', 'ja': '影の距離・ぼかし・強度でニューモーフィズム効果を作成', 'ko': '그림자 거리, 블러, 강도로 뉴모피즘 효과 생성', 'es': 'Crea efectos neumorphism con distancia de sombra, desenfoque e intensidad', 'fr': 'Créez des effets neumorphism avec distance d\'ombre, flou et intensité', 'de': 'Neumorphism-Effekte mit Schattenabstand, Unschärfe und Intensität erstellen', 'pt': 'Crie efeitos neumorphism com distância de sombra, desfoque e intensidade', 'ru': 'Создание эффектов neumorphism с расстоянием тени, размытием и интенсивностью' },
  },
  {
    slug: 'css-border-radius', icon: '⬜', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Border Radius Editor', 'zh-cn': 'CSS 圆角生成器', 'zh-tw': 'CSS 圓角產生器', 'ja': 'CSS角丸エディター', 'ko': 'CSS 테두리 반경 편집기', 'es': 'Editor de Border Radius', 'fr': 'Éditeur de Border Radius', 'de': 'Border-Radius-Editor', 'pt': 'Editor de Border Radius', 'ru': 'Редактор Border Radius' },
    description: { 'en': 'Edit CSS border-radius with independent corner controls', 'zh-cn': '编辑 CSS 圆角，四角独立/联动调整', 'zh-tw': '編輯 CSS 圓角，四角獨立/聯動調整', 'ja': '各角独立制御でCSS角丸を編集', 'ko': '각 모서리 독립 제어로 CSS 테두리 반경 편집', 'es': 'Edita border-radius CSS con controles independientes por esquina', 'fr': 'Éditez le border-radius CSS avec contrôles indépendants par coin', 'de': 'CSS-Border-Radius mit unabhängigen Eckensteuerungen bearbeiten', 'pt': 'Edite border-radius CSS com controles independentes por canto', 'ru': 'Редактирование CSS border-radius с независимым управлением углами' },
  },
  {
    slug: 'px-converter', icon: '📏', category: 'css', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'PX/EM/REM Converter', 'zh-cn': 'px/em/rem 互转', 'zh-tw': 'px/em/rem 互轉', 'ja': 'px/em/rem変換', 'ko': 'px/em/rem 변환기', 'es': 'Convertidor PX/EM/REM', 'fr': 'Convertisseur PX/EM/REM', 'de': 'PX/EM/REM-Konverter', 'pt': 'Conversor PX/EM/REM', 'ru': 'Конвертер PX/EM/REM' },
    description: { 'en': 'Convert between px, em, rem, pt and % with custom base font size', 'zh-cn': 'px/em/rem/pt/% 互转，自定义基准字体大小', 'zh-tw': 'px/em/rem/pt/% 互轉，自訂基準字體大小', 'ja': 'px/em/rem/pt/%を相互変換、カスタムベースフォントサイズ', 'ko': 'px/em/rem/pt/% 간 변환, 사용자 정의 기본 글꼴 크기', 'es': 'Convierte entre px, em, rem, pt y % con tamaño de fuente base personalizado', 'fr': 'Convertissez entre px, em, rem, pt et % avec taille de police de base personnalisée', 'de': 'Zwischen px, em, rem, pt und % mit benutzerdefinierter Basisschriftgröße konvertieren', 'pt': 'Converta entre px, em, rem, pt e % com tamanho de fonte base personalizado', 'ru': 'Конвертация между px, em, rem, pt и % с настраиваемым базовым размером шрифта' },
  },
  // P2 Color Tools
  { slug: 'gradient-collection', icon: '🎨', category: 'color', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Gradient Collection', 'zh-cn': '渐变色集合', 'zh-tw': '漸層色集合', 'ja': 'グラデーションコレクション', 'ko': '그라디언트 컬렉션', 'es': 'Colección de Gradientes', 'fr': 'Collection de Dégradés', 'de': 'Gradient-Sammlung', 'pt': 'Coleção de Gradientes', 'ru': 'Коллекция градиентов' },
    description: { 'en': '100+ preset gradient cards with CSS copy', 'zh-cn': '100+ 精选渐变色方案，一键复制 CSS', 'zh-tw': '100+ 精選漸層色方案，一鍵複製 CSS', 'ja': '100以上のプリセットグラデーションカード、CSSコピー対応', 'ko': '100개 이상의 프리셋 그라디언트 카드, CSS 복사', 'es': '100+ tarjetas de gradientes preestablecidos con copia CSS', 'fr': '100+ cartes de dégradés prédéfinis avec copie CSS', 'de': '100+ voreingestellte Gradient-Karten mit CSS-Kopie', 'pt': '100+ cartões de gradientes predefinidos com cópia CSS', 'ru': '100+ карточек предустановленных градиентов с копированием CSS' },
  },
  { slug: 'color-palette', icon: '🎯', category: 'color', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Color Palette Generator', 'zh-cn': '配色工具', 'zh-tw': '配色工具', 'ja': 'カラーパレット生成', 'ko': '색상 팔레트 생성기', 'es': 'Generador de Paleta de Colores', 'fr': 'Générateur de Palette de Couleurs', 'de': 'Farbpaletten-Generator', 'pt': 'Gerador de Paleta de Cores', 'ru': 'Генератор цветовых палитр' },
    description: { 'en': 'Generate color harmonies: complementary, analogous, triadic and more', 'zh-cn': '生成互补色、类似色、三角色等配色方案', 'zh-tw': '產生互補色、類似色、三角色等配色方案', 'ja': '補色・類似色・三色配色などのカラーハーモニーを生成', 'ko': '보색, 유사색, 삼색 등 색상 조화 생성', 'es': 'Genera armonías de color: complementario, análogo, triádico y más', 'fr': 'Générez des harmonies de couleurs : complémentaire, analogue, triadique et plus', 'de': 'Farbharmonien generieren: Komplementär, Analog, Triadisch und mehr', 'pt': 'Gere harmonias de cores: complementar, análoga, triádica e mais', 'ru': 'Генерация цветовых гармоний: комплементарные, аналогичные, триадные и другие' },
  },
  { slug: 'traditional-colors', icon: '🏮', category: 'color', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Traditional Colors', 'zh-cn': '中日传统色彩', 'zh-tw': '中日傳統色彩', 'ja': '伝統色', 'ko': '전통 색상', 'es': 'Colores Tradicionales', 'fr': 'Couleurs Traditionnelles', 'de': 'Traditionelle Farben', 'pt': 'Cores Tradicionais', 'ru': 'Традиционные цвета' },
    description: { 'en': 'Chinese and Japanese traditional color palettes with 100+ colors each', 'zh-cn': '中国和日本传统色彩，各 100+ 种', 'zh-tw': '中國和日本傳統色彩，各 100+ 種', 'ja': '中国と日本の伝統色、各100色以上', 'ko': '중국 및 일본 전통 색상, 각 100개 이상', 'es': 'Paletas de colores tradicionales chinos y japoneses con 100+ colores cada una', 'fr': 'Palettes de couleurs traditionnelles chinoises et japonaises avec 100+ couleurs chacune', 'de': 'Chinesische und japanische traditionelle Farbpaletten mit je 100+ Farben', 'pt': 'Paletas de cores tradicionais chinesas e japonesas com 100+ cores cada', 'ru': 'Китайские и японские традиционные цветовые палитры, 100+ цветов каждая' },
  },
  // P2 Image Tools
  { slug: 'image-crop', icon: '✂️', category: 'image', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Image Crop', 'zh-cn': '图片裁剪', 'zh-tw': '圖片裁剪', 'ja': '画像切り抜き', 'ko': '이미지 자르기', 'es': 'Recortar Imagen', 'fr': 'Recadrer Image', 'de': 'Bild zuschneiden', 'pt': 'Recortar Imagem', 'ru': 'Обрезка изображения' },
    description: { 'en': 'Crop images with custom dimensions using Canvas API', 'zh-cn': '使用 Canvas API 裁剪图片，自定义尺寸', 'zh-tw': '使用 Canvas API 裁剪圖片，自訂尺寸', 'ja': 'Canvas APIでカスタムサイズの画像切り抜き', 'ko': 'Canvas API로 사용자 정의 크기 이미지 자르기', 'es': 'Recorta imágenes con dimensiones personalizadas usando Canvas API', 'fr': 'Recadrez des images avec des dimensions personnalisées via Canvas API', 'de': 'Bilder mit benutzerdefinierten Abmessungen über Canvas API zuschneiden', 'pt': 'Recorte imagens com dimensões personalizadas usando Canvas API', 'ru': 'Обрезка изображений с пользовательскими размерами через Canvas API' },
  },
  { slug: 'image-compress', icon: '📦', category: 'image', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Image Compress', 'zh-cn': '图片压缩', 'zh-tw': '圖片壓縮', 'ja': '画像圧縮', 'ko': '이미지 압축', 'es': 'Comprimir Imagen', 'fr': 'Compresser Image', 'de': 'Bild komprimieren', 'pt': 'Comprimir Imagem', 'ru': 'Сжатие изображения' },
    description: { 'en': 'Compress images with adjustable quality using Canvas API', 'zh-cn': '使用 Canvas API 压缩图片，可调节质量', 'zh-tw': '使用 Canvas API 壓縮圖片，可調節品質', 'ja': 'Canvas APIで品質調整可能な画像圧縮', 'ko': 'Canvas API로 품질 조절 가능한 이미지 압축', 'es': 'Comprime imágenes con calidad ajustable usando Canvas API', 'fr': 'Compressez des images avec qualité ajustable via Canvas API', 'de': 'Bilder mit einstellbarer Qualität über Canvas API komprimieren', 'pt': 'Comprima imagens com qualidade ajustável usando Canvas API', 'ru': 'Сжатие изображений с настраиваемым качеством через Canvas API' },
  },
  { slug: 'image-converter', icon: '🔄', category: 'image', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Image Format Converter', 'zh-cn': '图片格式转换', 'zh-tw': '圖片格式轉換', 'ja': '画像形式変換', 'ko': '이미지 형식 변환', 'es': 'Convertidor de Formato de Imagen', 'fr': 'Convertisseur de Format d\'Image', 'de': 'Bildformat-Konverter', 'pt': 'Conversor de Formato de Imagem', 'ru': 'Конвертер формата изображений' },
    description: { 'en': 'Convert images between PNG, JPEG, WebP and BMP formats', 'zh-cn': '在 PNG、JPEG、WebP、BMP 格式之间转换图片', 'zh-tw': '在 PNG、JPEG、WebP、BMP 格式之間轉換圖片', 'ja': 'PNG、JPEG、WebP、BMP形式間で画像を変換', 'ko': 'PNG, JPEG, WebP, BMP 형식 간 이미지 변환', 'es': 'Convierte imágenes entre formatos PNG, JPEG, WebP y BMP', 'fr': 'Convertissez des images entre les formats PNG, JPEG, WebP et BMP', 'de': 'Bilder zwischen PNG-, JPEG-, WebP- und BMP-Formaten konvertieren', 'pt': 'Converta imagens entre formatos PNG, JPEG, WebP e BMP', 'ru': 'Конвертация изображений между форматами PNG, JPEG, WebP и BMP' },
  },
  { slug: 'image-resize', icon: '📐', category: 'image', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Image Resize', 'zh-cn': '图片缩放', 'zh-tw': '圖片縮放', 'ja': '画像リサイズ', 'ko': '이미지 크기 조정', 'es': 'Redimensionar Imagen', 'fr': 'Redimensionner Image', 'de': 'Bildgröße ändern', 'pt': 'Redimensionar Imagem', 'ru': 'Изменение размера изображения' },
    description: { 'en': 'Resize images with lock aspect ratio option', 'zh-cn': '缩放图片，支持锁定宽高比', 'zh-tw': '縮放圖片，支援鎖定寬高比', 'ja': 'アスペクト比ロック付き画像リサイズ', 'ko': '종횡비 잠금 옵션으로 이미지 크기 조정', 'es': 'Redimensiona imágenes con opción de bloqueo de relación de aspecto', 'fr': 'Redimensionnez des images avec option de verrouillage du rapport d\'aspect', 'de': 'Bildgröße mit Seitenverhältnis-Sperre ändern', 'pt': 'Redimensione imagens com opção de bloqueio de proporção', 'ru': 'Изменение размера изображений с блокировкой соотношения сторон' },
  },
  // P2 Network Tools
  { slug: 'curl-converter', icon: '🔧', category: 'network', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'cURL Converter', 'zh-cn': 'cURL 转代码', 'zh-tw': 'cURL 轉程式碼', 'ja': 'cURL変換', 'ko': 'cURL 변환기', 'es': 'Convertidor cURL', 'fr': 'Convertisseur cURL', 'de': 'cURL-Konverter', 'pt': 'Conversor cURL', 'ru': 'Конвертер cURL' },
    description: { 'en': 'Convert curl commands to JavaScript and Python code', 'zh-cn': '将 curl 命令转换为 JavaScript 和 Python 代码', 'zh-tw': '將 curl 命令轉換為 JavaScript 和 Python 程式碼', 'ja': 'curlコマンドをJavaScript・Pythonコードに変換', 'ko': 'curl 명령을 JavaScript 및 Python 코드로 변환', 'es': 'Convierte comandos curl a código JavaScript y Python', 'fr': 'Convertissez des commandes curl en code JavaScript et Python', 'de': 'curl-Befehle in JavaScript- und Python-Code konvertieren', 'pt': 'Converta comandos curl para código JavaScript e Python', 'ru': 'Конвертация команд curl в код JavaScript и Python' },
  },
  { slug: 'url-parser', icon: '🔗', category: 'network', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'URL Parser', 'zh-cn': 'URL 地址解析', 'zh-tw': 'URL 地址解析', 'ja': 'URLパーサー', 'ko': 'URL 파서', 'es': 'Analizador de URL', 'fr': 'Analyseur d\'URL', 'de': 'URL-Parser', 'pt': 'Analisador de URL', 'ru': 'Парсер URL' },
    description: { 'en': 'Parse URL into protocol, host, port, path, query and hash', 'zh-cn': '解析 URL 各部分：协议、主机、端口、路径、查询、哈希', 'zh-tw': '解析 URL 各部分：協議、主機、連接埠、路徑、查詢、雜湊', 'ja': 'URLをプロトコル・ホスト・ポート・パス・クエリ・ハッシュに分解', 'ko': 'URL을 프로토콜, 호스트, 포트, 경로, 쿼리, 해시로 분석', 'es': 'Analiza URL en protocolo, host, puerto, ruta, consulta y hash', 'fr': 'Analysez l\'URL en protocole, hôte, port, chemin, requête et hash', 'de': 'URL in Protokoll, Host, Port, Pfad, Query und Hash analysieren', 'pt': 'Analise URL em protocolo, host, porta, caminho, consulta e hash', 'ru': 'Разбор URL на протокол, хост, порт, путь, запрос и хеш' },
  },
  { slug: 'browser-info', icon: '🌐', category: 'network', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Browser Info', 'zh-cn': '浏览器信息检测', 'zh-tw': '瀏覽器資訊檢測', 'ja': 'ブラウザ情報', 'ko': '브라우저 정보', 'es': 'Info del Navegador', 'fr': 'Info Navigateur', 'de': 'Browser-Info', 'pt': 'Info do Navegador', 'ru': 'Информация о браузере' },
    description: { 'en': 'Detect browser, OS, screen, viewport and API support', 'zh-cn': '检测浏览器、操作系统、屏幕、视口和 API 支持', 'zh-tw': '檢測瀏覽器、作業系統、螢幕、視口和 API 支援', 'ja': 'ブラウザ・OS・画面・ビューポート・API対応を検出', 'ko': '브라우저, OS, 화면, 뷰포트, API 지원 감지', 'es': 'Detecta navegador, SO, pantalla, viewport y soporte de API', 'fr': 'Détectez navigateur, OS, écran, viewport et support API', 'de': 'Browser, OS, Bildschirm, Viewport und API-Unterstützung erkennen', 'pt': 'Detecte navegador, SO, tela, viewport e suporte a API', 'ru': 'Определение браузера, ОС, экрана, viewport и поддержки API' },
  },
  { slug: 'meta-generator', icon: '🏷️', category: 'network', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Meta Tag Generator', 'zh-cn': 'Meta 标签生成器', 'zh-tw': 'Meta 標籤產生器', 'ja': 'Metaタグ生成', 'ko': 'Meta 태그 생성기', 'es': 'Generador de Meta Tags', 'fr': 'Générateur de Meta Tags', 'de': 'Meta-Tag-Generator', 'pt': 'Gerador de Meta Tags', 'ru': 'Генератор Meta-тегов' },
    description: { 'en': 'Generate HTML meta tags for SEO, Open Graph and Twitter Cards', 'zh-cn': '生成 SEO、Open Graph 和 Twitter Card 的 HTML meta 标签', 'zh-tw': '產生 SEO、Open Graph 和 Twitter Card 的 HTML meta 標籤', 'ja': 'SEO・Open Graph・Twitter Card用HTMLメタタグを生成', 'ko': 'SEO, Open Graph, Twitter Card용 HTML meta 태그 생성', 'es': 'Genera meta tags HTML para SEO, Open Graph y Twitter Cards', 'fr': 'Générez des meta tags HTML pour SEO, Open Graph et Twitter Cards', 'de': 'HTML-Meta-Tags für SEO, Open Graph und Twitter Cards generieren', 'pt': 'Gere meta tags HTML para SEO, Open Graph e Twitter Cards', 'ru': 'Генерация HTML meta-тегов для SEO, Open Graph и Twitter Cards' },
  },
  { slug: 'htaccess-nginx', icon: '⚙️', category: 'network', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': '.htaccess to Nginx', 'zh-cn': 'htaccess 转 Nginx', 'zh-tw': 'htaccess 轉 Nginx', 'ja': '.htaccess→Nginx変換', 'ko': '.htaccess → Nginx 변환', 'es': '.htaccess a Nginx', 'fr': '.htaccess vers Nginx', 'de': '.htaccess zu Nginx', 'pt': '.htaccess para Nginx', 'ru': '.htaccess в Nginx' },
    description: { 'en': 'Convert Apache .htaccess rules to Nginx configuration', 'zh-cn': '将 Apache .htaccess 规则转换为 Nginx 配置', 'zh-tw': '將 Apache .htaccess 規則轉換為 Nginx 設定', 'ja': 'Apache .htaccessルールをNginx設定に変換', 'ko': 'Apache .htaccess 규칙을 Nginx 설정으로 변환', 'es': 'Convierte reglas Apache .htaccess a configuración Nginx', 'fr': 'Convertissez les règles Apache .htaccess en configuration Nginx', 'de': 'Apache .htaccess-Regeln in Nginx-Konfiguration konvertieren', 'pt': 'Converta regras Apache .htaccess para configuração Nginx', 'ru': 'Конвертация правил Apache .htaccess в конфигурацию Nginx' },
  },
  // P2 Converter Tools
  { slug: 'html-to-markdown', icon: '📝', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'HTML to Markdown', 'zh-cn': 'HTML 转 Markdown', 'zh-tw': 'HTML 轉 Markdown', 'ja': 'HTML→Markdown変換', 'ko': 'HTML → Markdown 변환', 'es': 'HTML a Markdown', 'fr': 'HTML vers Markdown', 'de': 'HTML zu Markdown', 'pt': 'HTML para Markdown', 'ru': 'HTML в Markdown' }, description: { 'en': 'Convert HTML to Markdown format', 'zh-cn': '将 HTML 转换为 Markdown 格式', 'zh-tw': '將 HTML 轉換為 Markdown 格式', 'ja': 'HTMLをMarkdown形式に変換', 'ko': 'HTML을 Markdown 형식으로 변환', 'es': 'Convierte HTML a formato Markdown', 'fr': 'Convertissez HTML en format Markdown', 'de': 'HTML in Markdown-Format konvertieren', 'pt': 'Converta HTML para formato Markdown', 'ru': 'Конвертация HTML в формат Markdown' } },
  { slug: 'pinyin', icon: '🔤', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Chinese to Pinyin', 'zh-cn': '汉字转拼音', 'zh-tw': '漢字轉拼音', 'ja': '漢字→ピンイン変換', 'ko': '한자 → 병음 변환', 'es': 'Chino a Pinyin', 'fr': 'Chinois vers Pinyin', 'de': 'Chinesisch zu Pinyin', 'pt': 'Chinês para Pinyin', 'ru': 'Китайский в пиньинь' }, description: { 'en': 'Convert Chinese characters to pinyin with tone marks', 'zh-cn': '将汉字转换为拼音，支持声调标记', 'zh-tw': '將漢字轉換為拼音，支援聲調標記', 'ja': '漢字をピンインに変換、声調記号対応', 'ko': '한자를 병음으로 변환, 성조 표시 지원', 'es': 'Convierte caracteres chinos a pinyin con marcas de tono', 'fr': 'Convertissez les caractères chinois en pinyin avec marques de ton', 'de': 'Chinesische Zeichen in Pinyin mit Tonzeichen konvertieren', 'pt': 'Converta caracteres chineses para pinyin com marcas de tom', 'ru': 'Конвертация китайских иероглифов в пиньинь с тональными знаками' } },
  { slug: 'simplified-traditional', icon: '繁', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Simplified ↔ Traditional', 'zh-cn': '简繁体互转', 'zh-tw': '簡繁體互轉', 'ja': '簡体字↔繁体字変換', 'ko': '간체 ↔ 번체 변환', 'es': 'Simplificado ↔ Tradicional', 'fr': 'Simplifié ↔ Traditionnel', 'de': 'Vereinfacht ↔ Traditionell', 'pt': 'Simplificado ↔ Tradicional', 'ru': 'Упрощённый ↔ Традиционный' }, description: { 'en': 'Convert between Simplified and Traditional Chinese', 'zh-cn': '简体中文和繁体中文互转', 'zh-tw': '簡體中文和繁體中文互轉', 'ja': '簡体字と繁体字を相互変換', 'ko': '간체자와 번체자 간 변환', 'es': 'Convierte entre chino simplificado y tradicional', 'fr': 'Convertissez entre chinois simplifié et traditionnel', 'de': 'Zwischen vereinfachtem und traditionellem Chinesisch konvertieren', 'pt': 'Converta entre chinês simplificado e tradicional', 'ru': 'Конвертация между упрощённым и традиционным китайским' } },
  { slug: 'number-to-chinese', icon: '🀄', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Number to Chinese', 'zh-cn': '数字转中文', 'zh-tw': '數字轉中文', 'ja': '数字→中国語変換', 'ko': '숫자 → 중국어 변환', 'es': 'Número a Chino', 'fr': 'Nombre vers Chinois', 'de': 'Zahl zu Chinesisch', 'pt': 'Número para Chinês', 'ru': 'Число в китайский' }, description: { 'en': 'Convert numbers to Chinese characters and uppercase amount', 'zh-cn': '数字转中文（普通/大写金额）', 'zh-tw': '數字轉中文（普通/大寫金額）', 'ja': '数字を中国語文字と大文字金額に変換', 'ko': '숫자를 중국어 문자 및 대문자 금액으로 변환', 'es': 'Convierte números a caracteres chinos y monto en mayúsculas', 'fr': 'Convertissez des nombres en caractères chinois et montant en majuscules', 'de': 'Zahlen in chinesische Zeichen und Großbuchstaben-Betrag konvertieren', 'pt': 'Converta números para caracteres chineses e valor em maiúsculas', 'ru': 'Конвертация чисел в китайские иероглифы и сумму прописью' } },
  { slug: 'image-base64', icon: '🖼️', category: 'encoding', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Image to Base64', 'zh-cn': '图片转 Base64', 'zh-tw': '圖片轉 Base64', 'ja': '画像→Base64変換', 'ko': '이미지 → Base64 변환', 'es': 'Imagen a Base64', 'fr': 'Image vers Base64', 'de': 'Bild zu Base64', 'pt': 'Imagem para Base64', 'ru': 'Изображение в Base64' }, description: { 'en': 'Convert images to Base64 and Data URI', 'zh-cn': '图片上传转 Base64 和 Data URI', 'zh-tw': '圖片上傳轉 Base64 和 Data URI', 'ja': '画像をBase64・Data URIに変換', 'ko': '이미지를 Base64 및 Data URI로 변환', 'es': 'Convierte imágenes a Base64 y Data URI', 'fr': 'Convertissez des images en Base64 et Data URI', 'de': 'Bilder in Base64 und Data URI konvertieren', 'pt': 'Converta imagens para Base64 e Data URI', 'ru': 'Конвертация изображений в Base64 и Data URI' } },
  { slug: 'csv-to-json', icon: '📊', category: 'json', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'CSV to JSON', 'zh-cn': 'CSV 转 JSON', 'zh-tw': 'CSV 轉 JSON', 'ja': 'CSV→JSON変換', 'ko': 'CSV → JSON 변환', 'es': 'CSV a JSON', 'fr': 'CSV vers JSON', 'de': 'CSV zu JSON', 'pt': 'CSV para JSON', 'ru': 'CSV в JSON' }, description: { 'en': 'Convert CSV to JSON with custom delimiter', 'zh-cn': 'CSV 转 JSON，自定义分隔符', 'zh-tw': 'CSV 轉 JSON，自訂分隔符', 'ja': 'カスタム区切り文字でCSVをJSONに変換', 'ko': '사용자 정의 구분자로 CSV를 JSON으로 변환', 'es': 'Convierte CSV a JSON con delimitador personalizado', 'fr': 'Convertissez CSV en JSON avec délimiteur personnalisé', 'de': 'CSV in JSON mit benutzerdefiniertem Trennzeichen konvertieren', 'pt': 'Converta CSV para JSON com delimitador personalizado', 'ru': 'Конвертация CSV в JSON с пользовательским разделителем' } },
  { slug: 'time-converter', icon: '🕐', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Time Format Converter', 'zh-cn': '时间格式转换', 'zh-tw': '時間格式轉換', 'ja': '時間形式変換', 'ko': '시간 형식 변환기', 'es': 'Convertidor de Formato de Tiempo', 'fr': 'Convertisseur de Format de Temps', 'de': 'Zeitformat-Konverter', 'pt': 'Conversor de Formato de Tempo', 'ru': 'Конвертер формата времени' }, description: { 'en': 'Convert between ISO 8601, RFC 2822, Unix timestamp and timezones', 'zh-cn': 'ISO 8601/RFC 2822/Unix 时间戳/时区转换', 'zh-tw': 'ISO 8601/RFC 2822/Unix 時間戳/時區轉換', 'ja': 'ISO 8601/RFC 2822/Unixタイムスタンプ/タイムゾーン変換', 'ko': 'ISO 8601/RFC 2822/Unix 타임스탬프/시간대 변환', 'es': 'Convierte entre ISO 8601, RFC 2822, timestamp Unix y zonas horarias', 'fr': 'Convertissez entre ISO 8601, RFC 2822, timestamp Unix et fuseaux horaires', 'de': 'Zwischen ISO 8601, RFC 2822, Unix-Zeitstempel und Zeitzonen konvertieren', 'pt': 'Converta entre ISO 8601, RFC 2822, timestamp Unix e fusos horários', 'ru': 'Конвертация между ISO 8601, RFC 2822, Unix timestamp и часовыми поясами' } },
  { slug: 'image-to-pdf', icon: '📄', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Image to PDF', 'zh-cn': '图片转 PDF', 'zh-tw': '圖片轉 PDF', 'ja': '画像→PDF変換', 'ko': '이미지 → PDF 변환', 'es': 'Imagen a PDF', 'fr': 'Image vers PDF', 'de': 'Bild zu PDF', 'pt': 'Imagem para PDF', 'ru': 'Изображение в PDF' }, description: { 'en': 'Convert images to PDF (coming soon - requires jspdf)', 'zh-cn': '图片转 PDF（即将推出 - 需要 jspdf）', 'zh-tw': '圖片轉 PDF（即將推出 - 需要 jspdf）', 'ja': '画像→PDF変換（近日公開 - jspdf必要）', 'ko': '이미지 → PDF 변환 (곧 출시 - jspdf 필요)', 'es': 'Convierte imágenes a PDF (próximamente - requiere jspdf)', 'fr': 'Convertissez des images en PDF (bientôt - nécessite jspdf)', 'de': 'Bilder in PDF konvertieren (demnächst - erfordert jspdf)', 'pt': 'Converta imagens para PDF (em breve - requer jspdf)', 'ru': 'Конвертация изображений в PDF (скоро - требуется jspdf)' } },
  { slug: 'pdf-to-image', icon: '🖼️', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'PDF to Image', 'zh-cn': 'PDF 转图片', 'zh-tw': 'PDF 轉圖片', 'ja': 'PDF→画像変換', 'ko': 'PDF → 이미지 변환', 'es': 'PDF a Imagen', 'fr': 'PDF vers Image', 'de': 'PDF zu Bild', 'pt': 'PDF para Imagem', 'ru': 'PDF в изображение' }, description: { 'en': 'Convert PDF pages to images (coming soon - requires pdf.js)', 'zh-cn': 'PDF 页面转图片（即将推出 - 需要 pdf.js）', 'zh-tw': 'PDF 頁面轉圖片（即將推出 - 需要 pdf.js）', 'ja': 'PDFページを画像に変換（近日公開 - pdf.js必要）', 'ko': 'PDF 페이지를 이미지로 변환 (곧 출시 - pdf.js 필요)', 'es': 'Convierte páginas PDF a imágenes (próximamente - requiere pdf.js)', 'fr': 'Convertissez des pages PDF en images (bientôt - nécessite pdf.js)', 'de': 'PDF-Seiten in Bilder konvertieren (demnächst - erfordert pdf.js)', 'pt': 'Converta páginas PDF para imagens (em breve - requer pdf.js)', 'ru': 'Конвертация страниц PDF в изображения (скоро - требуется pdf.js)' } },
  { slug: 'image-to-svg', icon: '✏️', category: 'converter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Image to SVG', 'zh-cn': '图片转 SVG', 'zh-tw': '圖片轉 SVG', 'ja': '画像→SVG変換', 'ko': '이미지 → SVG 변환', 'es': 'Imagen a SVG', 'fr': 'Image vers SVG', 'de': 'Bild zu SVG', 'pt': 'Imagem para SVG', 'ru': 'Изображение в SVG' }, description: { 'en': 'Trace bitmap to SVG (coming soon - requires potrace)', 'zh-cn': '位图追踪转 SVG（即将推出 - 需要 potrace）', 'zh-tw': '點陣圖追蹤轉 SVG（即將推出 - 需要 potrace）', 'ja': 'ビットマップをSVGにトレース（近日公開 - potrace必要）', 'ko': '비트맵을 SVG로 추적 (곧 출시 - potrace 필요)', 'es': 'Traza bitmap a SVG (próximamente - requiere potrace)', 'fr': 'Tracez bitmap en SVG (bientôt - nécessite potrace)', 'de': 'Bitmap zu SVG tracen (demnächst - erfordert potrace)', 'pt': 'Trace bitmap para SVG (em breve - requer potrace)', 'ru': 'Трассировка растра в SVG (скоро - требуется potrace)' } },
  // P2 Text/Formatter Tools
  { slug: 'html-strip', icon: '🧹', category: 'text', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'HTML Tag Stripper', 'zh-cn': '去除 HTML 格式', 'zh-tw': '去除 HTML 格式', 'ja': 'HTMLタグ除去', 'ko': 'HTML 태그 제거', 'es': 'Eliminador de Tags HTML', 'fr': 'Suppresseur de Tags HTML', 'de': 'HTML-Tag-Entferner', 'pt': 'Removedor de Tags HTML', 'ru': 'Удаление HTML-тегов' }, description: { 'en': 'Strip HTML tags and keep text structure', 'zh-cn': '去除 HTML 标签，保留文本结构', 'zh-tw': '去除 HTML 標籤，保留文字結構', 'ja': 'HTMLタグを除去してテキスト構造を保持', 'ko': 'HTML 태그를 제거하고 텍스트 구조 유지', 'es': 'Elimina tags HTML y mantiene la estructura del texto', 'fr': 'Supprimez les tags HTML et gardez la structure du texte', 'de': 'HTML-Tags entfernen und Textstruktur beibehalten', 'pt': 'Remova tags HTML e mantenha a estrutura do texto', 'ru': 'Удаление HTML-тегов с сохранением структуры текста' } },
  { slug: 'auto-typeset', icon: '📐', category: 'text', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Auto Typeset', 'zh-cn': '自动排版工具', 'zh-tw': '自動排版工具', 'ja': '自動組版', 'ko': '자동 조판', 'es': 'Auto Composición', 'fr': 'Composition Auto', 'de': 'Auto-Satz', 'pt': 'Composição Auto', 'ru': 'Автоматическая вёрстка' }, description: { 'en': 'Add spaces between CJK and Latin characters automatically', 'zh-cn': '中英文之间自动添加空格', 'zh-tw': '中英文之間自動添加空格', 'ja': 'CJKとラテン文字の間に自動でスペースを追加', 'ko': 'CJK와 라틴 문자 사이에 자동으로 공백 추가', 'es': 'Agrega espacios entre caracteres CJK y latinos automáticamente', 'fr': 'Ajoutez des espaces entre caractères CJK et latins automatiquement', 'de': 'Automatisch Leerzeichen zwischen CJK- und lateinischen Zeichen einfügen', 'pt': 'Adicione espaços entre caracteres CJK e latinos automaticamente', 'ru': 'Автоматическое добавление пробелов между CJK и латинскими символами' } },
  { slug: 'text-filter', icon: '🔍', category: 'text', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Text Filter', 'zh-cn': '文本过滤器', 'zh-tw': '文字過濾器', 'ja': 'テキストフィルター', 'ko': '텍스트 필터', 'es': 'Filtro de Texto', 'fr': 'Filtre de Texte', 'de': 'Textfilter', 'pt': 'Filtro de Texto', 'ru': 'Фильтр текста' }, description: { 'en': 'Keep or remove Chinese, English, digits and punctuation selectively', 'zh-cn': '选择性保留/清除中文、英文、数字、标点', 'zh-tw': '選擇性保留/清除中文、英文、數字、標點', 'ja': '中国語・英語・数字・句読点を選択的に保持/削除', 'ko': '중국어, 영어, 숫자, 구두점을 선택적으로 유지/제거', 'es': 'Mantén o elimina chino, inglés, dígitos y puntuación selectivamente', 'fr': 'Gardez ou supprimez chinois, anglais, chiffres et ponctuation sélectivement', 'de': 'Chinesisch, Englisch, Ziffern und Satzzeichen selektiv behalten oder entfernen', 'pt': 'Mantenha ou remova chinês, inglês, dígitos e pontuação seletivamente', 'ru': 'Выборочное сохранение/удаление китайского, английского, цифр и пунктуации' } },
  { slug: 'python-formatter', icon: '🐍', category: 'formatter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Python Formatter', 'zh-cn': 'Python 格式化', 'zh-tw': 'Python 格式化', 'ja': 'Pythonフォーマッター', 'ko': 'Python 포매터', 'es': 'Formateador Python', 'fr': 'Formateur Python', 'de': 'Python-Formatierer', 'pt': 'Formatador Python', 'ru': 'Форматировщик Python' }, description: { 'en': 'Basic Python code indent formatting', 'zh-cn': 'Python 代码基本缩进格式化', 'zh-tw': 'Python 程式碼基本縮排格式化', 'ja': 'Pythonコードの基本インデント整形', 'ko': 'Python 코드 기본 들여쓰기 포맷', 'es': 'Formateo básico de indentación de código Python', 'fr': 'Formatage basique d\'indentation de code Python', 'de': 'Grundlegende Python-Code-Einrückungsformatierung', 'pt': 'Formatação básica de indentação de código Python', 'ru': 'Базовое форматирование отступов кода Python' } },
  { slug: 'java-formatter', icon: '☕', category: 'formatter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Java Formatter', 'zh-cn': 'Java 格式化', 'zh-tw': 'Java 格式化', 'ja': 'Javaフォーマッター', 'ko': 'Java 포매터', 'es': 'Formateador Java', 'fr': 'Formateur Java', 'de': 'Java-Formatierer', 'pt': 'Formatador Java', 'ru': 'Форматировщик Java' }, description: { 'en': 'Basic Java code indent formatting', 'zh-cn': 'Java 代码基本缩进格式化', 'zh-tw': 'Java 程式碼基本縮排格式化', 'ja': 'Javaコードの基本インデント整形', 'ko': 'Java 코드 기본 들여쓰기 포맷', 'es': 'Formateo básico de indentación de código Java', 'fr': 'Formatage basique d\'indentation de code Java', 'de': 'Grundlegende Java-Code-Einrückungsformatierung', 'pt': 'Formatação básica de indentação de código Java', 'ru': 'Базовое форматирование отступов кода Java' } },
  { slug: 'php-formatter', icon: '🐘', category: 'formatter', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'PHP Formatter', 'zh-cn': 'PHP 格式化', 'zh-tw': 'PHP 格式化', 'ja': 'PHPフォーマッター', 'ko': 'PHP 포매터', 'es': 'Formateador PHP', 'fr': 'Formateur PHP', 'de': 'PHP-Formatierer', 'pt': 'Formatador PHP', 'ru': 'Форматировщик PHP' }, description: { 'en': 'Basic PHP code indent formatting', 'zh-cn': 'PHP 代码基本缩进格式化', 'zh-tw': 'PHP 程式碼基本縮排格式化', 'ja': 'PHPコードの基本インデント整形', 'ko': 'PHP 코드 기본 들여쓰기 포맷', 'es': 'Formateo básico de indentación de código PHP', 'fr': 'Formatage basique d\'indentation de code PHP', 'de': 'Grundlegende PHP-Code-Einrückungsformatierung', 'pt': 'Formatação básica de indentação de código PHP', 'ru': 'Базовое форматирование отступов кода PHP' } },
  { slug: 'subnet-calculator', icon: '🌐', category: 'network', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Subnet Calculator', 'zh-cn': '子网掩码换算器', 'zh-tw': '子網路遮罩換算器', 'ja': 'サブネット計算機', 'ko': '서브넷 계산기', 'es': 'Calculadora de Subred', 'fr': 'Calculateur de Sous-réseau', 'de': 'Subnetz-Rechner', 'pt': 'Calculadora de Sub-rede', 'ru': 'Калькулятор подсетей' }, description: { 'en': 'CIDR to subnet mask conversion table', 'zh-cn': 'CIDR 与子网掩码互转表', 'zh-tw': 'CIDR 與子網路遮罩互轉表', 'ja': 'CIDRとサブネットマスク変換表', 'ko': 'CIDR ↔ 서브넷 마스크 변환 표', 'es': 'Tabla de conversión CIDR a máscara de subred', 'fr': 'Table de conversion CIDR vers masque de sous-réseau', 'de': 'CIDR-zu-Subnetzmaske-Konvertierungstabelle', 'pt': 'Tabela de conversão CIDR para máscara de sub-rede', 'ru': 'Таблица конвертации CIDR в маску подсети' } },
  { slug: 'color-schemes', icon: '🎨', category: 'color', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Color Schemes', 'zh-cn': '配色方案集', 'zh-tw': '配色方案集', 'ja': 'カラースキーム', 'ko': '색상 스킴', 'es': 'Esquemas de Color', 'fr': 'Schémas de Couleurs', 'de': 'Farbschemata', 'pt': 'Esquemas de Cores', 'ru': 'Цветовые схемы' }, description: { 'en': '50+ preset web design color scheme cards', 'zh-cn': '50+ 精选网页设计配色方案', 'zh-tw': '50+ 精選網頁設計配色方案', 'ja': '50以上のWebデザインカラースキームカード', 'ko': '50개 이상의 웹 디자인 색상 스킴 카드', 'es': '50+ tarjetas de esquemas de color para diseño web', 'fr': '50+ cartes de schémas de couleurs pour le design web', 'de': '50+ voreingestellte Webdesign-Farbschemata-Karten', 'pt': '50+ cartões de esquemas de cores para design web', 'ru': '50+ карточек цветовых схем для веб-дизайна' } },
  // P2 Misc Tools
  { slug: 'barcode', icon: '📊', category: 'misc', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Barcode Generator', 'zh-cn': '条形码生成器', 'zh-tw': '條碼產生器', 'ja': 'バーコード生成', 'ko': '바코드 생성기', 'es': 'Generador de Código de Barras', 'fr': 'Générateur de Code-barres', 'de': 'Barcode-Generator', 'pt': 'Gerador de Código de Barras', 'ru': 'Генератор штрих-кодов' }, description: { 'en': 'Generate Code128 barcodes from text', 'zh-cn': '从文本生成 Code128 条形码', 'zh-tw': '從文字產生 Code128 條碼', 'ja': 'テキストからCode128バーコードを生成', 'ko': '텍스트에서 Code128 바코드 생성', 'es': 'Genera códigos de barras Code128 desde texto', 'fr': 'Générez des codes-barres Code128 à partir de texte', 'de': 'Code128-Barcodes aus Text generieren', 'pt': 'Gere códigos de barras Code128 a partir de texto', 'ru': 'Генерация штрих-кодов Code128 из текста' } },
  { slug: 'chart-generator', icon: '📈', category: 'misc', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Chart Generator', 'zh-cn': '图表生成器', 'zh-tw': '圖表產生器', 'ja': 'チャート生成', 'ko': '차트 생성기', 'es': 'Generador de Gráficos', 'fr': 'Générateur de Graphiques', 'de': 'Diagramm-Generator', 'pt': 'Gerador de Gráficos', 'ru': 'Генератор диаграмм' }, description: { 'en': 'Create bar, pie and line charts using Canvas', 'zh-cn': '使用 Canvas 创建柱状图、饼图和折线图', 'zh-tw': '使用 Canvas 建立柱狀圖、圓餅圖和折線圖', 'ja': 'Canvasで棒グラフ・円グラフ・折れ線グラフを作成', 'ko': 'Canvas로 막대, 파이, 라인 차트 생성', 'es': 'Crea gráficos de barras, circulares y de líneas usando Canvas', 'fr': 'Créez des graphiques en barres, circulaires et en lignes avec Canvas', 'de': 'Balken-, Kreis- und Liniendiagramme mit Canvas erstellen', 'pt': 'Crie gráficos de barras, pizza e linhas usando Canvas', 'ru': 'Создание столбчатых, круговых и линейных диаграмм с помощью Canvas' } },
  { slug: 'keycode', icon: '⌨️', category: 'misc', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Keycode Viewer', 'zh-cn': '键盘按键值查询', 'zh-tw': '鍵盤按鍵值查詢', 'ja': 'キーコードビューア', 'ko': '키코드 뷰어', 'es': 'Visor de Keycode', 'fr': 'Visualiseur de Keycode', 'de': 'Keycode-Viewer', 'pt': 'Visualizador de Keycode', 'ru': 'Просмотр кодов клавиш' }, description: { 'en': 'Real-time keypress event display showing key, keyCode, code and which', 'zh-cn': '实时显示按键事件的 key/keyCode/code/which', 'zh-tw': '即時顯示按鍵事件的 key/keyCode/code/which', 'ja': 'キー押下イベントをリアルタイム表示（key/keyCode/code/which）', 'ko': '키 누름 이벤트 실시간 표시 (key/keyCode/code/which)', 'es': 'Muestra eventos de tecla en tiempo real: key, keyCode, code y which', 'fr': 'Affichage en temps réel des événements de touche : key, keyCode, code et which', 'de': 'Echtzeit-Anzeige von Tastenereignissen: key, keyCode, code und which', 'pt': 'Exibição em tempo real de eventos de tecla: key, keyCode, code e which', 'ru': 'Отображение событий нажатия клавиш в реальном времени: key, keyCode, code, which' } },
  { slug: 'shield-badge', icon: '🛡️', category: 'misc', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'Shield Badge Generator', 'zh-cn': 'Shield 徽章生成器', 'zh-tw': 'Shield 徽章產生器', 'ja': 'シールドバッジ生成', 'ko': '쉴드 배지 생성기', 'es': 'Generador de Insignias Shield', 'fr': 'Générateur de Badges Shield', 'de': 'Shield-Badge-Generator', 'pt': 'Gerador de Badges Shield', 'ru': 'Генератор Shield-бейджей' }, description: { 'en': 'Generate GitHub-style shield badges with custom label, message and color', 'zh-cn': '生成 GitHub 风格的 Shield 徽章', 'zh-tw': '產生 GitHub 風格的 Shield 徽章', 'ja': 'GitHub風シールドバッジをカスタム生成', 'ko': 'GitHub 스타일 쉴드 배지 생성', 'es': 'Genera insignias shield estilo GitHub con etiqueta, mensaje y color personalizados', 'fr': 'Générez des badges shield style GitHub avec étiquette, message et couleur personnalisés', 'de': 'GitHub-Style Shield-Badges mit benutzerdefiniertem Label, Nachricht und Farbe generieren', 'pt': 'Gere badges shield estilo GitHub com rótulo, mensagem e cor personalizados', 'ru': 'Генерация Shield-бейджей в стиле GitHub с настраиваемыми метками, сообщениями и цветами' } },
  { slug: 'gif-maker', icon: '🎬', category: 'image', enabled: true, supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'], name: { 'en': 'GIF Maker', 'zh-cn': 'GIF 生成器', 'zh-tw': 'GIF 產生器', 'ja': 'GIF作成', 'ko': 'GIF 생성기', 'es': 'Creador de GIF', 'fr': 'Créateur de GIF', 'de': 'GIF-Ersteller', 'pt': 'Criador de GIF', 'ru': 'Создатель GIF' }, description: { 'en': 'Create GIF from multiple images (coming soon - requires gif.js)', 'zh-cn': '多图合成 GIF（即将推出 - 需要 gif.js）', 'zh-tw': '多圖合成 GIF（即將推出 - 需要 gif.js）', 'ja': '複数画像からGIF作成（近日公開 - gif.js必要）', 'ko': '여러 이미지로 GIF 생성 (곧 출시 - gif.js 필요)', 'es': 'Crea GIF desde múltiples imágenes (próximamente - requiere gif.js)', 'fr': 'Créez des GIF à partir de plusieurs images (bientôt - nécessite gif.js)', 'de': 'GIF aus mehreren Bildern erstellen (demnächst - erfordert gif.js)', 'pt': 'Crie GIF a partir de múltiplas imagens (em breve - requer gif.js)', 'ru': 'Создание GIF из нескольких изображений (скоро - требуется gif.js)' } },
  // P3 Tools
  ...P3_TOOLS,
];

// Query functions

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return TOOL_REGISTRY.find((tool) => tool.slug === slug);
}

export function getEnabledTools(): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.enabled);
}

export function getToolsByCategory(category: ToolCategory): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.category === category && tool.enabled);
}

export function getFeaturedTools(): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.featured === true && tool.enabled);
}

export function getToolPath(slug: string): string {
  return `/tools/${slug}`;
}

export function validateRegistry(tools: ToolMeta[]): void {
  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const tool of tools) {
    if (seen.has(tool.slug)) {
      duplicates.push(tool.slug);
    } else {
      seen.add(tool.slug);
    }
  }
  if (duplicates.length > 0) {
    throw new Error(`Duplicate slugs found in registry: ${duplicates.join(', ')}`);
  }
}
