export type ToolCategory = 'text' | 'json' | 'encoding' | 'color' | 'network' | 'math' | 'converter' | 'formatter' | 'image' | 'css' | 'misc';
export type Locale = 'en' | 'zh-cn' | 'zh-tw' | 'ja' | 'ko' | 'es' | 'fr' | 'de' | 'pt' | 'ru';

export interface ToolMeta {
  slug: string;
  icon: string;
  category: ToolCategory;
  enabled: boolean;
  featured?: boolean;
  supportedLocales: Locale[];
  name: Record<Locale, string>;
  description: Record<Locale, string>;
}

export const TOOL_REGISTRY: ToolMeta[] = [
  {
    slug: 'json-formatter',
    icon: '{}',
    category: 'json',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Formatter',
      'zh-cn': 'JSON 格式化',
      'zh-tw': 'JSON 格式化',
      'ja': 'JSON フォーマッター',
      'ko': 'JSON 포매터',
      'es': 'Formateador JSON',
      'fr': 'Formateur JSON',
      'de': 'JSON-Formatierer',
      'pt': 'Formatador JSON',
      'ru': 'Форматировщик JSON',
    },
    description: {
      'en': 'Format and validate JSON data with syntax highlighting',
      'zh-cn': '格式化并验证 JSON 数据，支持语法高亮',
      'zh-tw': '格式化並驗證 JSON 資料，支援語法高亮',
      'ja': 'JSONデータをフォーマットして検証し、シンタックスハイライトを表示',
      'ko': '구문 강조와 함께 JSON 데이터를 포맷하고 유효성 검사',
      'es': 'Formatea y valida datos JSON con resaltado de sintaxis',
      'fr': 'Formatez et validez des données JSON avec coloration syntaxique',
      'de': 'JSON-Daten formatieren und validieren mit Syntaxhervorhebung',
      'pt': 'Formate e valide dados JSON com destaque de sintaxe',
      'ru': 'Форматирование и проверка данных JSON с подсветкой синтаксиса',
    },
  },
  {
    slug: 'base64',
    icon: '🔐',
    category: 'encoding',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Base64 Encoder/Decoder',
      'zh-cn': 'Base64 编码解码',
      'zh-tw': 'Base64 編碼解碼',
      'ja': 'Base64 エンコード/デコード',
      'ko': 'Base64 인코더/디코더',
      'es': 'Codificador/Decodificador Base64',
      'fr': 'Encodeur/Décodeur Base64',
      'de': 'Base64-Encoder/Decoder',
      'pt': 'Codificador/Decodificador Base64',
      'ru': 'Кодировщик/Декодировщик Base64',
    },
    description: {
      'en': 'Encode and decode text using Base64 with URL-safe variant support',
      'zh-cn': '使用 Base64 对文本进行编码和解码，支持 URL 安全变体',
      'zh-tw': '使用 Base64 對文字進行編碼和解碼，支援 URL 安全變體',
      'ja': 'Base64でテキストをエンコード・デコード、URLセーフ変換対応',
      'ko': 'Base64로 텍스트를 인코딩 및 디코딩, URL 안전 변환 지원',
      'es': 'Codifica y decodifica texto usando Base64 con soporte de variante segura para URL',
      'fr': 'Encodez et décodez du texte en Base64 avec prise en charge de la variante URL-safe',
      'de': 'Text mit Base64 kodieren und dekodieren, mit URL-sicherer Variante',
      'pt': 'Codifique e decodifique texto usando Base64 com suporte a variante segura para URL',
      'ru': 'Кодирование и декодирование текста в Base64 с поддержкой URL-безопасного варианта',
    },
  },
  {
    slug: 'word-counter',
    icon: 'Aa',
    category: 'text',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Word Counter',
      'zh-cn': '字符统计',
      'zh-tw': '字元統計',
      'ja': '文字カウンター',
      'ko': '단어 카운터',
      'es': 'Contador de palabras',
      'fr': 'Compteur de mots',
      'de': 'Wortzähler',
      'pt': 'Contador de palavras',
      'ru': 'Счётчик слов',
    },
    description: {
      'en': 'Count characters, words, and lines in your text',
      'zh-cn': '统计文本中的字符数、单词数和行数',
      'zh-tw': '統計文字中的字元數、單詞數和行數',
      'ja': 'テキストの文字数、単語数、行数をカウント',
      'ko': '텍스트의 문자 수, 단어 수, 줄 수를 계산',
      'es': 'Cuenta caracteres, palabras y líneas en tu texto',
      'fr': 'Comptez les caractères, mots et lignes dans votre texte',
      'de': 'Zeichen, Wörter und Zeilen in Ihrem Text zählen',
      'pt': 'Conte caracteres, palavras e linhas no seu texto',
      'ru': 'Подсчёт символов, слов и строк в тексте',
    },
  },
  {
    slug: 'url-encoder',
    icon: '🔗',
    category: 'encoding',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'URL Encoder/Decoder',
      'zh-cn': 'URL 编码解码',
      'zh-tw': 'URL 編碼解碼',
      'ja': 'URLエンコード/デコード',
      'ko': 'URL 인코더/디코더',
      'es': 'Codificador/Decodificador URL',
      'fr': 'Encodeur/Décodeur URL',
      'de': 'URL-Encoder/Decoder',
      'pt': 'Codificador/Decodificador URL',
      'ru': 'Кодировщик/Декодировщик URL',
    },
    description: {
      'en': 'Encode and decode URLs with encodeURIComponent and encodeURI modes',
      'zh-cn': '使用 encodeURIComponent 和 encodeURI 模式对 URL 进行编码和解码',
      'zh-tw': '使用 encodeURIComponent 和 encodeURI 模式對 URL 進行編碼和解碼',
      'ja': 'encodeURIComponentとencodeURIモードでURLをエンコード・デコード',
      'ko': 'encodeURIComponent 및 encodeURI 모드로 URL 인코딩 및 디코딩',
      'es': 'Codifica y decodifica URLs con modos encodeURIComponent y encodeURI',
      'fr': 'Encodez et décodez des URLs avec les modes encodeURIComponent et encodeURI',
      'de': 'URLs mit encodeURIComponent- und encodeURI-Modi kodieren und dekodieren',
      'pt': 'Codifique e decodifique URLs com modos encodeURIComponent e encodeURI',
      'ru': 'Кодирование и декодирование URL с режимами encodeURIComponent и encodeURI',
    },
  },
  {
    slug: 'timestamp',
    icon: '⏰',
    category: 'converter',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Unix Timestamp Converter',
      'zh-cn': 'Unix 时间戳转换',
      'zh-tw': 'Unix 時間戳轉換',
      'ja': 'Unixタイムスタンプ変換',
      'ko': 'Unix 타임스탬프 변환',
      'es': 'Convertidor de marca de tiempo Unix',
      'fr': 'Convertisseur de timestamp Unix',
      'de': 'Unix-Zeitstempel-Konverter',
      'pt': 'Conversor de timestamp Unix',
      'ru': 'Конвертер временных меток Unix',
    },
    description: {
      'en': 'Convert between Unix timestamps and human-readable dates with timezone support',
      'zh-cn': '在 Unix 时间戳和可读日期之间互转，支持时区选择',
      'zh-tw': '在 Unix 時間戳和可讀日期之間互轉，支援時區選擇',
      'ja': 'Unixタイムスタンプと日付を相互変換、タイムゾーン対応',
      'ko': 'Unix 타임스탬프와 날짜 간 변환, 시간대 지원',
      'es': 'Convierte entre marcas de tiempo Unix y fechas legibles con soporte de zona horaria',
      'fr': 'Convertissez entre les timestamps Unix et les dates lisibles avec prise en charge des fuseaux horaires',
      'de': 'Konvertieren Sie zwischen Unix-Zeitstempeln und lesbaren Daten mit Zeitzonen-Unterstützung',
      'pt': 'Converta entre timestamps Unix e datas legíveis com suporte a fuso horário',
      'ru': 'Конвертация между временными метками Unix и читаемыми датами с поддержкой часовых поясов',
    },
  },
  {
    slug: 'json-minify',
    icon: '📦',
    category: 'json',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Minify & Escape',
      'zh-cn': 'JSON 压缩与转义',
      'zh-tw': 'JSON 壓縮與轉義',
      'ja': 'JSON圧縮・エスケープ',
      'ko': 'JSON 압축 및 이스케이프',
      'es': 'Minificar y escapar JSON',
      'fr': 'Minifier et échapper JSON',
      'de': 'JSON-Minifizierung & Escape',
      'pt': 'Minificar e escapar JSON',
      'ru': 'Минификация и экранирование JSON',
    },
    description: {
      'en': 'Minify, escape, and unescape JSON data',
      'zh-cn': '压缩、转义和反转义 JSON 数据',
      'zh-tw': '壓縮、轉義和反轉義 JSON 資料',
      'ja': 'JSONデータの圧縮・エスケープ・アンエスケープ',
      'ko': 'JSON 데이터 압축, 이스케이프 및 언이스케이프',
      'es': 'Minifica, escapa y desescapa datos JSON',
      'fr': 'Minifiez, échappez et désechappez des données JSON',
      'de': 'JSON-Daten minifizieren, escapen und unescapen',
      'pt': 'Minifique, escape e unescape dados JSON',
      'ru': 'Минификация, экранирование и деэкранирование данных JSON',
    },
  },
  {
    slug: 'uuid-generator',
    icon: '🆔',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'UUID/GUID Generator',
      'zh-cn': 'UUID/GUID 生成器',
      'zh-tw': 'UUID/GUID 產生器',
      'ja': 'UUID/GUIDジェネレーター',
      'ko': 'UUID/GUID 생성기',
      'es': 'Generador UUID/GUID',
      'fr': 'Générateur UUID/GUID',
      'de': 'UUID/GUID-Generator',
      'pt': 'Gerador UUID/GUID',
      'ru': 'Генератор UUID/GUID',
    },
    description: {
      'en': 'Generate UUID v4 with batch and format options',
      'zh-cn': '生成 UUID v4，支持批量生成和格式选项',
      'zh-tw': '產生 UUID v4，支援批次產生和格式選項',
      'ja': 'UUID v4を生成、一括生成とフォーマットオプション対応',
      'ko': 'UUID v4 생성, 일괄 생성 및 형식 옵션 지원',
      'es': 'Genera UUID v4 con opciones de lote y formato',
      'fr': 'Générez des UUID v4 avec options de lot et de format',
      'de': 'UUID v4 generieren mit Batch- und Formatoptionen',
      'pt': 'Gere UUID v4 com opções de lote e formato',
      'ru': 'Генерация UUID v4 с пакетными и форматными опциями',
    },
  },
  {
    slug: 'hash-calculator',
    icon: '#️⃣',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Hash Calculator',
      'zh-cn': '哈希计算器',
      'zh-tw': '雜湊計算器',
      'ja': 'ハッシュ計算機',
      'ko': '해시 계산기',
      'es': 'Calculadora de Hash',
      'fr': 'Calculateur de Hash',
      'de': 'Hash-Rechner',
      'pt': 'Calculadora de Hash',
      'ru': 'Калькулятор хешей',
    },
    description: {
      'en': 'Calculate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes',
      'zh-cn': '计算 MD5、SHA-1、SHA-256、SHA-384、SHA-512 哈希值',
      'zh-tw': '計算 MD5、SHA-1、SHA-256、SHA-384、SHA-512 雜湊值',
      'ja': 'MD5、SHA-1、SHA-256、SHA-384、SHA-512ハッシュを計算',
      'ko': 'MD5, SHA-1, SHA-256, SHA-384, SHA-512 해시 계산',
      'es': 'Calcula hashes MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'fr': 'Calculez les hachages MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'de': 'MD5-, SHA-1-, SHA-256-, SHA-384-, SHA-512-Hashes berechnen',
      'pt': 'Calcule hashes MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'ru': 'Вычисление хешей MD5, SHA-1, SHA-256, SHA-384, SHA-512',
    },
  },
  {
    slug: 'color-converter',
    icon: '🎨',
    category: 'color',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Color Converter',
      'zh-cn': '颜色格式转换',
      'zh-tw': '顏色格式轉換',
      'ja': 'カラーコンバーター',
      'ko': '색상 변환기',
      'es': 'Convertidor de Color',
      'fr': 'Convertisseur de Couleur',
      'de': 'Farbkonverter',
      'pt': 'Conversor de Cor',
      'ru': 'Конвертер цветов',
    },
    description: {
      'en': 'Convert between HEX, RGB, HSL, HSV, and CMYK color formats',
      'zh-cn': '在 HEX、RGB、HSL、HSV 和 CMYK 颜色格式之间转换',
      'zh-tw': '在 HEX、RGB、HSL、HSV 和 CMYK 顏色格式之間轉換',
      'ja': 'HEX、RGB、HSL、HSV、CMYKカラー形式を相互変換',
      'ko': 'HEX, RGB, HSL, HSV, CMYK 색상 형식 간 변환',
      'es': 'Convierte entre formatos de color HEX, RGB, HSL, HSV y CMYK',
      'fr': 'Convertissez entre les formats de couleur HEX, RGB, HSL, HSV et CMYK',
      'de': 'Zwischen HEX-, RGB-, HSL-, HSV- und CMYK-Farbformaten konvertieren',
      'pt': 'Converta entre formatos de cor HEX, RGB, HSL, HSV e CMYK',
      'ru': 'Конвертация между форматами цветов HEX, RGB, HSL, HSV и CMYK',
    },
  },
  {
    slug: 'radix-converter',
    icon: '🔢',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Radix Converter',
      'zh-cn': '进制转换',
      'zh-tw': '進制轉換',
      'ja': '基数変換',
      'ko': '진법 변환기',
      'es': 'Convertidor de Base',
      'fr': 'Convertisseur de Base',
      'de': 'Zahlensystem-Konverter',
      'pt': 'Conversor de Base',
      'ru': 'Конвертер систем счисления',
    },
    description: {
      'en': 'Convert between binary, octal, decimal, and hexadecimal',
      'zh-cn': '在二进制、八进制、十进制和十六进制之间转换',
      'zh-tw': '在二進制、八進制、十進制和十六進制之間轉換',
      'ja': '2進数、8進数、10進数、16進数を相互変換',
      'ko': '2진수, 8진수, 10진수, 16진수 간 변환',
      'es': 'Convierte entre binario, octal, decimal y hexadecimal',
      'fr': 'Convertissez entre binaire, octal, décimal et hexadécimal',
      'de': 'Zwischen Binär, Oktal, Dezimal und Hexadezimal konvertieren',
      'pt': 'Converta entre binário, octal, decimal e hexadecimal',
      'ru': 'Конвертация между двоичной, восьмеричной, десятичной и шестнадцатеричной системами',
    },
  },
  {
    slug: 'case-converter',
    icon: 'Aa',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Case Converter',
      'zh-cn': '大小写转换',
      'zh-tw': '大小寫轉換',
      'ja': '大文字小文字変換',
      'ko': '대소문자 변환기',
      'es': 'Convertidor de Mayúsculas',
      'fr': 'Convertisseur de Casse',
      'de': 'Groß-/Kleinschreibung',
      'pt': 'Conversor de Maiúsculas',
      'ru': 'Конвертер регистра',
    },
    description: {
      'en': 'Convert text between uppercase, lowercase, title case, and more',
      'zh-cn': '在大写、小写、标题大小写等格式之间转换文本',
      'zh-tw': '在大寫、小寫、標題大小寫等格式之間轉換文字',
      'ja': 'テキストを大文字、小文字、タイトルケースなどに変換',
      'ko': '텍스트를 대문자, 소문자, 제목 대소문자 등으로 변환',
      'es': 'Convierte texto entre mayúsculas, minúsculas, título y más',
      'fr': 'Convertissez le texte entre majuscules, minuscules, casse de titre et plus',
      'de': 'Text zwischen Groß-, Klein-, Titelschreibung und mehr konvertieren',
      'pt': 'Converta texto entre maiúsculas, minúsculas, título e mais',
      'ru': 'Конвертация текста между верхним, нижним регистром, заглавными и другими',
    },
  },
  {
    slug: 'password-generator',
    icon: '🔑',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Password Generator',
      'zh-cn': '随机密码生成器',
      'zh-tw': '隨機密碼產生器',
      'ja': 'パスワードジェネレーター',
      'ko': '비밀번호 생성기',
      'es': 'Generador de Contraseñas',
      'fr': 'Générateur de Mots de Passe',
      'de': 'Passwort-Generator',
      'pt': 'Gerador de Senhas',
      'ru': 'Генератор паролей',
    },
    description: {
      'en': 'Generate secure random passwords with customizable options',
      'zh-cn': '生成安全的随机密码，支持自定义选项',
      'zh-tw': '產生安全的隨機密碼，支援自訂選項',
      'ja': 'カスタマイズ可能なオプションで安全なランダムパスワードを生成',
      'ko': '사용자 정의 옵션으로 안전한 랜덤 비밀번호 생성',
      'es': 'Genera contraseñas aleatorias seguras con opciones personalizables',
      'fr': 'Générez des mots de passe aléatoires sécurisés avec des options personnalisables',
      'de': 'Sichere zufällige Passwörter mit anpassbaren Optionen generieren',
      'pt': 'Gere senhas aleatórias seguras com opções personalizáveis',
      'ru': 'Генерация безопасных случайных паролей с настраиваемыми параметрами',
    },
  },
  {
    slug: 'json-sort',
    icon: '🔤',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Sort',
      'zh-cn': 'JSON 排序',
      'zh-tw': 'JSON 排序',
      'ja': 'JSONソート',
      'ko': 'JSON 정렬',
      'es': 'Ordenar JSON',
      'fr': 'Tri JSON',
      'de': 'JSON-Sortierung',
      'pt': 'Ordenar JSON',
      'ru': 'Сортировка JSON',
    },
    description: {
      'en': 'Sort JSON object keys alphabetically in ascending or descending order',
      'zh-cn': '按字母顺序对 JSON 对象键进行升序或降序排序',
      'zh-tw': '按字母順序對 JSON 物件鍵進行升序或降序排序',
      'ja': 'JSONオブジェクトのキーをアルファベット順に昇順または降順でソート',
      'ko': 'JSON 객체 키를 알파벳순으로 오름차순 또는 내림차순 정렬',
      'es': 'Ordena las claves de objetos JSON alfabéticamente en orden ascendente o descendente',
      'fr': 'Triez les clés des objets JSON par ordre alphabétique croissant ou décroissant',
      'de': 'JSON-Objektschlüssel alphabetisch aufsteigend oder absteigend sortieren',
      'pt': 'Ordene as chaves de objetos JSON alfabeticamente em ordem crescente ou decrescente',
      'ru': 'Сортировка ключей объектов JSON по алфавиту в порядке возрастания или убывания',
    },
  },
  {
    slug: 'regex-tester',
    icon: '🔍',
    category: 'misc',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Regex Tester',
      'zh-cn': '正则表达式测试器',
      'zh-tw': '正規表達式測試器',
      'ja': '正規表現テスター',
      'ko': '정규식 테스터',
      'es': 'Probador de Regex',
      'fr': 'Testeur de Regex',
      'de': 'Regex-Tester',
      'pt': 'Testador de Regex',
      'ru': 'Тестер регулярных выражений',
    },
    description: {
      'en': 'Test regular expressions with real-time matching and highlighting',
      'zh-cn': '实时匹配和高亮显示测试正则表达式',
      'zh-tw': '即時匹配和高亮顯示測試正規表達式',
      'ja': 'リアルタイムマッチングとハイライトで正規表現をテスト',
      'ko': '실시간 매칭 및 하이라이트로 정규식 테스트',
      'es': 'Prueba expresiones regulares con coincidencia y resaltado en tiempo real',
      'fr': 'Testez des expressions régulières avec correspondance et surlignage en temps réel',
      'de': 'Reguläre Ausdrücke mit Echtzeit-Matching und Hervorhebung testen',
      'pt': 'Teste expressões regulares com correspondência e destaque em tempo real',
      'ru': 'Тестирование регулярных выражений с сопоставлением и подсветкой в реальном времени',
    },
  },
  {
    slug: 'qrcode',
    icon: '📱',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'QR Code Generator',
      'zh-cn': '二维码生成器',
      'zh-tw': 'QR Code 產生器',
      'ja': 'QRコードジェネレーター',
      'ko': 'QR 코드 생성기',
      'es': 'Generador de Código QR',
      'fr': 'Générateur de QR Code',
      'de': 'QR-Code-Generator',
      'pt': 'Gerador de QR Code',
      'ru': 'Генератор QR-кодов',
    },
    description: {
      'en': 'Generate QR codes from text with customizable size and colors',
      'zh-cn': '从文本生成二维码，支持自定义大小和颜色',
      'zh-tw': '從文字產生 QR Code，支援自訂大小和顏色',
      'ja': 'テキストからQRコードを生成、サイズと色のカスタマイズ対応',
      'ko': '텍스트에서 QR 코드 생성, 크기 및 색상 사용자 정의 지원',
      'es': 'Genera códigos QR desde texto con tamaño y colores personalizables',
      'fr': 'Générez des QR codes à partir de texte avec taille et couleurs personnalisables',
      'de': 'QR-Codes aus Text mit anpassbarer Größe und Farben generieren',
      'pt': 'Gere QR codes a partir de texto com tamanho e cores personalizáveis',
      'ru': 'Генерация QR-кодов из текста с настраиваемым размером и цветами',
    },
  },
  {
    slug: 'json-converter',
    icon: '🔄',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Converter',
      'zh-cn': 'JSON 格式互转',
      'zh-tw': 'JSON 格式互轉',
      'ja': 'JSON コンバーター',
      'ko': 'JSON 변환기',
      'es': 'Convertidor JSON',
      'fr': 'Convertisseur JSON',
      'de': 'JSON-Konverter',
      'pt': 'Conversor JSON',
      'ru': 'Конвертер JSON',
    },
    description: {
      'en': 'Convert between JSON, YAML, XML, TOML, and CSV formats',
      'zh-cn': '在 JSON、YAML、XML、TOML 和 CSV 格式之间互相转换',
      'zh-tw': '在 JSON、YAML、XML、TOML 和 CSV 格式之間互相轉換',
      'ja': 'JSON、YAML、XML、TOML、CSV形式を相互変換',
      'ko': 'JSON, YAML, XML, TOML, CSV 형식 간 변환',
      'es': 'Convierte entre formatos JSON, YAML, XML, TOML y CSV',
      'fr': 'Convertissez entre les formats JSON, YAML, XML, TOML et CSV',
      'de': 'Zwischen JSON-, YAML-, XML-, TOML- und CSV-Formaten konvertieren',
      'pt': 'Converta entre formatos JSON, YAML, XML, TOML e CSV',
      'ru': 'Конвертация между форматами JSON, YAML, XML, TOML и CSV',
    },
  },
  {
    slug: 'json-to-class',
    icon: '📝',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON to Class',
      'zh-cn': 'JSON 转实体类',
      'zh-tw': 'JSON 轉實體類',
      'ja': 'JSON → クラス変換',
      'ko': 'JSON → 클래스 변환',
      'es': 'JSON a Clase',
      'fr': 'JSON vers Classe',
      'de': 'JSON zu Klasse',
      'pt': 'JSON para Classe',
      'ru': 'JSON в класс',
    },
    description: {
      'en': 'Generate TypeScript, Java, Go, Python, and C# classes from JSON',
      'zh-cn': '从 JSON 生成 TypeScript、Java、Go、Python、C# 类型定义',
      'zh-tw': '從 JSON 產生 TypeScript、Java、Go、Python、C# 型別定義',
      'ja': 'JSONからTypeScript、Java、Go、Python、C#のクラスを生成',
      'ko': 'JSON에서 TypeScript, Java, Go, Python, C# 클래스 생성',
      'es': 'Genera clases TypeScript, Java, Go, Python y C# desde JSON',
      'fr': 'Générez des classes TypeScript, Java, Go, Python et C# à partir de JSON',
      'de': 'TypeScript-, Java-, Go-, Python- und C#-Klassen aus JSON generieren',
      'pt': 'Gere classes TypeScript, Java, Go, Python e C# a partir de JSON',
      'ru': 'Генерация классов TypeScript, Java, Go, Python и C# из JSON',
    },
  },
  {
    slug: 'jwt-decoder',
    icon: '🔓',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JWT Decoder',
      'zh-cn': 'JWT 解码器',
      'zh-tw': 'JWT 解碼器',
      'ja': 'JWT デコーダー',
      'ko': 'JWT 디코더',
      'es': 'Decodificador JWT',
      'fr': 'Décodeur JWT',
      'de': 'JWT-Decoder',
      'pt': 'Decodificador JWT',
      'ru': 'Декодер JWT',
    },
    description: {
      'en': 'Decode JWT tokens to view header, payload, and signature',
      'zh-cn': '解码 JWT Token，查看 Header、Payload 和 Signature',
      'zh-tw': '解碼 JWT Token，查看 Header、Payload 和 Signature',
      'ja': 'JWTトークンをデコードしてヘッダー、ペイロード、署名を表示',
      'ko': 'JWT 토큰을 디코딩하여 헤더, 페이로드, 서명 확인',
      'es': 'Decodifica tokens JWT para ver encabezado, carga útil y firma',
      'fr': 'Décodez les tokens JWT pour voir l\'en-tête, la charge utile et la signature',
      'de': 'JWT-Token dekodieren, um Header, Payload und Signatur anzuzeigen',
      'pt': 'Decodifique tokens JWT para ver cabeçalho, payload e assinatura',
      'ru': 'Декодирование JWT-токенов для просмотра заголовка, полезной нагрузки и подписи',
    },
  },
  {
    slug: 'json-schema',
    icon: '📋',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Schema Generator',
      'zh-cn': 'JSON Schema 生成器',
      'zh-tw': 'JSON Schema 產生器',
      'ja': 'JSON Schema ジェネレーター',
      'ko': 'JSON Schema 생성기',
      'es': 'Generador de JSON Schema',
      'fr': 'Générateur de JSON Schema',
      'de': 'JSON-Schema-Generator',
      'pt': 'Gerador de JSON Schema',
      'ru': 'Генератор JSON Schema',
    },
    description: {
      'en': 'Generate JSON Schema (Draft-07) from JSON data',
      'zh-cn': '从 JSON 数据自动生成 JSON Schema（Draft-07）',
      'zh-tw': '從 JSON 資料自動產生 JSON Schema（Draft-07）',
      'ja': 'JSONデータからJSON Schema（Draft-07）を自動生成',
      'ko': 'JSON 데이터에서 JSON Schema(Draft-07) 자동 생성',
      'es': 'Genera JSON Schema (Draft-07) a partir de datos JSON',
      'fr': 'Générez un JSON Schema (Draft-07) à partir de données JSON',
      'de': 'JSON Schema (Draft-07) aus JSON-Daten generieren',
      'pt': 'Gere JSON Schema (Draft-07) a partir de dados JSON',
      'ru': 'Генерация JSON Schema (Draft-07) из данных JSON',
    },
  },
  {
    slug: 'unicode-converter', icon: '🔤', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Unicode Converter', 'zh-cn': 'Unicode 转换', 'zh-tw': 'Unicode 轉換', 'ja': 'Unicode変換', 'ko': 'Unicode 변환기', 'es': 'Convertidor Unicode', 'fr': 'Convertisseur Unicode', 'de': 'Unicode-Konverter', 'pt': 'Conversor Unicode', 'ru': 'Конвертер Unicode' },
    description: { 'en': 'Convert between Unicode escape sequences and text', 'zh-cn': 'Unicode \\uXXXX 转义与文本互转', 'zh-tw': 'Unicode \\uXXXX 轉義與文字互轉', 'ja': 'Unicodeエスケープシーケンスとテキストを相互変換', 'ko': 'Unicode 이스케이프 시퀀스와 텍스트 간 변환', 'es': 'Convierte entre secuencias de escape Unicode y texto', 'fr': 'Convertissez entre séquences d\'échappement Unicode et texte', 'de': 'Zwischen Unicode-Escape-Sequenzen und Text konvertieren', 'pt': 'Converta entre sequências de escape Unicode e texto', 'ru': 'Конвертация между escape-последовательностями Unicode и текстом' },
  },
  {
    slug: 'symmetric-cipher', icon: '🔒', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'AES Encrypt/Decrypt', 'zh-cn': 'AES 加密解密', 'zh-tw': 'AES 加密解密', 'ja': 'AES暗号化/復号化', 'ko': 'AES 암호화/복호화', 'es': 'Cifrado/Descifrado AES', 'fr': 'Chiffrement/Déchiffrement AES', 'de': 'AES-Verschlüsselung/Entschlüsselung', 'pt': 'Criptografia/Descriptografia AES', 'ru': 'AES шифрование/дешифрование' },
    description: { 'en': 'Encrypt and decrypt text using AES-CBC with Web Crypto API', 'zh-cn': '使用 AES-CBC 和 Web Crypto API 加密解密文本', 'zh-tw': '使用 AES-CBC 和 Web Crypto API 加密解密文字', 'ja': 'Web Crypto APIを使用したAES-CBCテキスト暗号化/復号化', 'ko': 'Web Crypto API를 사용한 AES-CBC 텍스트 암호화/복호화', 'es': 'Cifra y descifra texto usando AES-CBC con Web Crypto API', 'fr': 'Chiffrez et déchiffrez du texte avec AES-CBC via Web Crypto API', 'de': 'Text mit AES-CBC über Web Crypto API verschlüsseln und entschlüsseln', 'pt': 'Criptografe e descriptografe texto usando AES-CBC com Web Crypto API', 'ru': 'Шифрование и дешифрование текста с помощью AES-CBC через Web Crypto API' },
  },
  {
    slug: 'html-escape', icon: '🏷️', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'HTML Escape/Unescape', 'zh-cn': 'HTML 转义', 'zh-tw': 'HTML 轉義', 'ja': 'HTMLエスケープ', 'ko': 'HTML 이스케이프', 'es': 'Escape/Unescape HTML', 'fr': 'Échappement HTML', 'de': 'HTML-Escape', 'pt': 'Escape HTML', 'ru': 'HTML экранирование' },
    description: { 'en': 'Encode and decode HTML entities like &lt; &gt; &amp;', 'zh-cn': 'HTML 实体编码解码（&lt; &gt; &amp; 等）', 'zh-tw': 'HTML 實體編碼解碼（&lt; &gt; &amp; 等）', 'ja': 'HTMLエンティティのエンコード・デコード（&lt; &gt; &amp;など）', 'ko': 'HTML 엔티티 인코딩/디코딩 (&lt; &gt; &amp; 등)', 'es': 'Codifica y decodifica entidades HTML como &lt; &gt; &amp;', 'fr': 'Encodez et décodez les entités HTML comme &lt; &gt; &amp;', 'de': 'HTML-Entitäten wie &lt; &gt; &amp; kodieren und dekodieren', 'pt': 'Codifique e decodifique entidades HTML como &lt; &gt; &amp;', 'ru': 'Кодирование и декодирование HTML-сущностей (&lt; &gt; &amp; и др.)' },
  },
  {
    slug: 'file-base64', icon: '📁', category: 'encoding', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'File to Base64', 'zh-cn': '文件转 Base64', 'zh-tw': '檔案轉 Base64', 'ja': 'ファイル→Base64変換', 'ko': '파일 → Base64 변환', 'es': 'Archivo a Base64', 'fr': 'Fichier vers Base64', 'de': 'Datei zu Base64', 'pt': 'Arquivo para Base64', 'ru': 'Файл в Base64' },
    description: { 'en': 'Convert files to Base64 and Data URI, or decode Base64 to file', 'zh-cn': '文件上传转 Base64 + Data URI，Base64 还原文件下载', 'zh-tw': '檔案上傳轉 Base64 + Data URI，Base64 還原檔案下載', 'ja': 'ファイルをBase64・Data URIに変換、Base64からファイルに復元', 'ko': '파일을 Base64 및 Data URI로 변환, Base64에서 파일 복원', 'es': 'Convierte archivos a Base64 y Data URI, o decodifica Base64 a archivo', 'fr': 'Convertissez des fichiers en Base64 et Data URI, ou décodez Base64 en fichier', 'de': 'Dateien in Base64 und Data URI konvertieren oder Base64 in Datei dekodieren', 'pt': 'Converta arquivos para Base64 e Data URI, ou decodifique Base64 para arquivo', 'ru': 'Конвертация файлов в Base64 и Data URI, или декодирование Base64 в файл' },
  },
  {
    slug: 'text-dedup', icon: '🔃', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Text Deduplicator', 'zh-cn': '文本去重', 'zh-tw': '文字去重', 'ja': 'テキスト重複削除', 'ko': '텍스트 중복 제거', 'es': 'Deduplicador de texto', 'fr': 'Dédoublonneur de texte', 'de': 'Text-Deduplizierer', 'pt': 'Deduplicador de texto', 'ru': 'Удаление дубликатов текста' },
    description: { 'en': 'Remove duplicate lines with case sensitive/insensitive options', 'zh-cn': '去除重复行，支持大小写敏感/不敏感，显示行数对比', 'zh-tw': '去除重複行，支援大小寫敏感/不敏感，顯示行數對比', 'ja': '重複行を削除、大文字小文字の区別オプション付き', 'ko': '중복 줄 제거, 대소문자 구분/무시 옵션 지원', 'es': 'Elimina líneas duplicadas con opciones de distinción de mayúsculas', 'fr': 'Supprimez les lignes en double avec options de sensibilité à la casse', 'de': 'Doppelte Zeilen entfernen mit Groß-/Kleinschreibungsoptionen', 'pt': 'Remova linhas duplicadas com opções de distinção de maiúsculas', 'ru': 'Удаление дублирующихся строк с учётом/без учёта регистра' },
  },
  {
    slug: 'text-sort', icon: '📊', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Text Sorter', 'zh-cn': '文本排序', 'zh-tw': '文字排序', 'ja': 'テキストソート', 'ko': '텍스트 정렬', 'es': 'Ordenador de texto', 'fr': 'Trieur de texte', 'de': 'Text-Sortierer', 'pt': 'Ordenador de texto', 'ru': 'Сортировка текста' },
    description: { 'en': 'Sort lines alphabetically, numerically, by length, or randomly', 'zh-cn': '按字母/数字/长度/随机排序文本行，支持升序降序', 'zh-tw': '按字母/數字/長度/隨機排序文字行，支援升序降序', 'ja': 'テキスト行をアルファベット順・数値順・長さ順・ランダムにソート', 'ko': '텍스트 줄을 알파벳/숫자/길이/랜덤으로 정렬', 'es': 'Ordena líneas alfabéticamente, numéricamente, por longitud o aleatoriamente', 'fr': 'Triez les lignes par ordre alphabétique, numérique, longueur ou aléatoire', 'de': 'Zeilen alphabetisch, numerisch, nach Länge oder zufällig sortieren', 'pt': 'Ordene linhas alfabeticamente, numericamente, por comprimento ou aleatoriamente', 'ru': 'Сортировка строк по алфавиту, числам, длине или случайно' },
  },
  {
    slug: 'text-trim', icon: '✂️', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Text Trimmer', 'zh-cn': '空行空白处理', 'zh-tw': '空行空白處理', 'ja': 'テキストトリマー', 'ko': '텍스트 트리머', 'es': 'Recortador de texto', 'fr': 'Nettoyeur de texte', 'de': 'Text-Trimmer', 'pt': 'Aparador de texto', 'ru': 'Очистка текста' },
    description: { 'en': 'Remove empty lines, trim whitespace, merge blank lines, or join to one line', 'zh-cn': '去空行、trim 空白、合并空行、合并为一行', 'zh-tw': '去空行、trim 空白、合併空行、合併為一行', 'ja': '空行削除、空白トリム、空行マージ、一行に結合', 'ko': '빈 줄 제거, 공백 제거, 빈 줄 병합, 한 줄로 합치기', 'es': 'Elimina líneas vacías, recorta espacios, fusiona líneas en blanco o une en una línea', 'fr': 'Supprimez les lignes vides, coupez les espaces, fusionnez les lignes blanches ou joignez en une ligne', 'de': 'Leere Zeilen entfernen, Leerzeichen trimmen, Leerzeilen zusammenführen oder in eine Zeile verbinden', 'pt': 'Remova linhas vazias, apare espaços, mescle linhas em branco ou junte em uma linha', 'ru': 'Удаление пустых строк, обрезка пробелов, объединение пустых строк или в одну строку' },
  },
  {
    slug: 'naming-converter', icon: '🐫', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Naming Converter', 'zh-cn': '变量命名转换', 'zh-tw': '變數命名轉換', 'ja': '命名規則変換', 'ko': '네이밍 변환기', 'es': 'Convertidor de nombres', 'fr': 'Convertisseur de nommage', 'de': 'Namenskonverter', 'pt': 'Conversor de nomes', 'ru': 'Конвертер именования' },
    description: { 'en': 'Convert between camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'zh-cn': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKE 互转', 'zh-tw': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKE 互轉', 'ja': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKEを相互変換', 'ko': 'camelCase/PascalCase/snake_case/kebab-case/SCREAMING_SNAKE 간 변환', 'es': 'Convierte entre camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'fr': 'Convertissez entre camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'de': 'Zwischen camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE konvertieren', 'pt': 'Converta entre camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE', 'ru': 'Конвертация между camelCase, PascalCase, snake_case, kebab-case, SCREAMING_SNAKE' },
  },
  {
    slug: 'js-formatter', icon: '📄', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'JS/HTML Formatter', 'zh-cn': 'JS/HTML 格式化', 'zh-tw': 'JS/HTML 格式化', 'ja': 'JS/HTMLフォーマッター', 'ko': 'JS/HTML 포매터', 'es': 'Formateador JS/HTML', 'fr': 'Formateur JS/HTML', 'de': 'JS/HTML-Formatierer', 'pt': 'Formatador JS/HTML', 'ru': 'Форматировщик JS/HTML' },
    description: { 'en': 'Beautify and minify JavaScript and HTML code', 'zh-cn': 'JavaScript/HTML 代码格式化和压缩', 'zh-tw': 'JavaScript/HTML 程式碼格式化和壓縮', 'ja': 'JavaScript/HTMLコードの整形と圧縮', 'ko': 'JavaScript/HTML 코드 정리 및 압축', 'es': 'Embellece y minifica código JavaScript y HTML', 'fr': 'Embellissez et minifiez le code JavaScript et HTML', 'de': 'JavaScript- und HTML-Code verschönern und minifizieren', 'pt': 'Embeleze e minifique código JavaScript e HTML', 'ru': 'Форматирование и минификация кода JavaScript и HTML' },
  },
  {
    slug: 'css-formatter', icon: '🎨', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'CSS Formatter', 'zh-cn': 'CSS 格式化', 'zh-tw': 'CSS 格式化', 'ja': 'CSSフォーマッター', 'ko': 'CSS 포매터', 'es': 'Formateador CSS', 'fr': 'Formateur CSS', 'de': 'CSS-Formatierer', 'pt': 'Formatador CSS', 'ru': 'Форматировщик CSS' },
    description: { 'en': 'Beautify and minify CSS code', 'zh-cn': 'CSS 代码格式化和压缩', 'zh-tw': 'CSS 程式碼格式化和壓縮', 'ja': 'CSSコードの整形と圧縮', 'ko': 'CSS 코드 정리 및 압축', 'es': 'Embellece y minifica código CSS', 'fr': 'Embellissez et minifiez le code CSS', 'de': 'CSS-Code verschönern und minifizieren', 'pt': 'Embeleze e minifique código CSS', 'ru': 'Форматирование и минификация кода CSS' },
  },
  {
    slug: 'sql-formatter', icon: '🗃️', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'SQL Formatter', 'zh-cn': 'SQL 格式化', 'zh-tw': 'SQL 格式化', 'ja': 'SQLフォーマッター', 'ko': 'SQL 포매터', 'es': 'Formateador SQL', 'fr': 'Formateur SQL', 'de': 'SQL-Formatierer', 'pt': 'Formatador SQL', 'ru': 'Форматировщик SQL' },
    description: { 'en': 'Format SQL with keyword uppercasing and indentation', 'zh-cn': 'SQL 关键词大写 + 缩进格式化', 'zh-tw': 'SQL 關鍵詞大寫 + 縮排格式化', 'ja': 'SQLキーワード大文字化とインデント整形', 'ko': 'SQL 키워드 대문자화 및 들여쓰기 포맷', 'es': 'Formatea SQL con palabras clave en mayúsculas e indentación', 'fr': 'Formatez SQL avec mots-clés en majuscules et indentation', 'de': 'SQL mit Schlüsselwort-Großschreibung und Einrückung formatieren', 'pt': 'Formate SQL com palavras-chave em maiúsculas e indentação', 'ru': 'Форматирование SQL с заглавными ключевыми словами и отступами' },
  },
  {
    slug: 'xml-formatter', icon: '📰', category: 'formatter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'XML Formatter', 'zh-cn': 'XML 格式化', 'zh-tw': 'XML 格式化', 'ja': 'XMLフォーマッター', 'ko': 'XML 포매터', 'es': 'Formateador XML', 'fr': 'Formateur XML', 'de': 'XML-Formatierer', 'pt': 'Formatador XML', 'ru': 'Форматировщик XML' },
    description: { 'en': 'Format and minify XML documents', 'zh-cn': 'XML 文档格式化和压缩', 'zh-tw': 'XML 文件格式化和壓縮', 'ja': 'XMLドキュメントの整形と圧縮', 'ko': 'XML 문서 정리 및 압축', 'es': 'Formatea y minifica documentos XML', 'fr': 'Formatez et minifiez des documents XML', 'de': 'XML-Dokumente formatieren und minifizieren', 'pt': 'Formate e minifique documentos XML', 'ru': 'Форматирование и минификация XML-документов' },
  },
  {
    slug: 'properties-yaml', icon: '⚙️', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Properties ↔ YAML', 'zh-cn': 'Properties 转 YAML', 'zh-tw': 'Properties 轉 YAML', 'ja': 'Properties ↔ YAML変換', 'ko': 'Properties ↔ YAML 변환', 'es': 'Properties ↔ YAML', 'fr': 'Properties ↔ YAML', 'de': 'Properties ↔ YAML', 'pt': 'Properties ↔ YAML', 'ru': 'Properties ↔ YAML' },
    description: { 'en': 'Convert between .properties and YAML formats with nested key support', 'zh-cn': '.properties 与 YAML 格式互转，支持嵌套键', 'zh-tw': '.properties 與 YAML 格式互轉，支援巢狀鍵', 'ja': '.propertiesとYAML形式を相互変換、ネストキー対応', 'ko': '.properties와 YAML 형식 간 변환, 중첩 키 지원', 'es': 'Convierte entre formatos .properties y YAML con soporte de claves anidadas', 'fr': 'Convertissez entre les formats .properties et YAML avec support des clés imbriquées', 'de': 'Zwischen .properties- und YAML-Formaten mit verschachtelten Schlüsseln konvertieren', 'pt': 'Converta entre formatos .properties e YAML com suporte a chaves aninhadas', 'ru': 'Конвертация между форматами .properties и YAML с поддержкой вложенных ключей' },
  },
  {
    slug: 'json-to-sql', icon: '💾', category: 'json', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'JSON to SQL', 'zh-cn': 'JSON 转 SQL', 'zh-tw': 'JSON 轉 SQL', 'ja': 'JSON → SQL変換', 'ko': 'JSON → SQL 변환', 'es': 'JSON a SQL', 'fr': 'JSON vers SQL', 'de': 'JSON zu SQL', 'pt': 'JSON para SQL', 'ru': 'JSON в SQL' },
    description: { 'en': 'Convert JSON arrays to SQL INSERT statements', 'zh-cn': 'JSON 数组转 SQL INSERT 语句', 'zh-tw': 'JSON 陣列轉 SQL INSERT 語句', 'ja': 'JSON配列をSQL INSERT文に変換', 'ko': 'JSON 배열을 SQL INSERT 문으로 변환', 'es': 'Convierte arrays JSON a sentencias SQL INSERT', 'fr': 'Convertissez des tableaux JSON en instructions SQL INSERT', 'de': 'JSON-Arrays in SQL INSERT-Anweisungen konvertieren', 'pt': 'Converta arrays JSON em instruções SQL INSERT', 'ru': 'Конвертация массивов JSON в SQL INSERT-запросы' },
  },
  {
    slug: 'diff-viewer', icon: '📊', category: 'misc', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Diff Viewer', 'zh-cn': '文本对比', 'zh-tw': '文字對比', 'ja': 'テキスト差分ビューア', 'ko': '텍스트 비교', 'es': 'Visor de diferencias', 'fr': 'Visualiseur de différences', 'de': 'Diff-Viewer', 'pt': 'Visualizador de diferenças', 'ru': 'Просмотр различий' },
    description: { 'en': 'Side-by-side text comparison with color-coded differences', 'zh-cn': '并排文本对比，颜色标注差异', 'zh-tw': '並排文字對比，顏色標註差異', 'ja': 'テキストを並べて比較、色分けで差異を表示', 'ko': '텍스트를 나란히 비교하고 색상으로 차이 표시', 'es': 'Comparación de texto lado a lado con diferencias codificadas por color', 'fr': 'Comparaison de texte côte à côte avec différences colorées', 'de': 'Textvergleich nebeneinander mit farbcodierten Unterschieden', 'pt': 'Comparação de texto lado a lado com diferenças codificadas por cor', 'ru': 'Сравнение текста бок о бок с цветовой маркировкой различий' },
  },
  {
    slug: 'markdown-editor', icon: '📝', category: 'text', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Markdown Editor', 'zh-cn': 'Markdown 编辑器', 'zh-tw': 'Markdown 編輯器', 'ja': 'Markdownエディター', 'ko': 'Markdown 편집기', 'es': 'Editor Markdown', 'fr': 'Éditeur Markdown', 'de': 'Markdown-Editor', 'pt': 'Editor Markdown', 'ru': 'Редактор Markdown' },
    description: { 'en': 'Split-view Markdown editor with live preview', 'zh-cn': '左右分栏 Markdown 编辑器，实时预览', 'zh-tw': '左右分欄 Markdown 編輯器，即時預覽', 'ja': '分割ビューMarkdownエディター、リアルタイムプレビュー', 'ko': '분할 뷰 Markdown 편집기, 실시간 미리보기', 'es': 'Editor Markdown con vista dividida y vista previa en vivo', 'fr': 'Éditeur Markdown en vue partagée avec aperçu en direct', 'de': 'Markdown-Editor mit geteilter Ansicht und Live-Vorschau', 'pt': 'Editor Markdown com visualização dividida e pré-visualização ao vivo', 'ru': 'Редактор Markdown с разделённым видом и предпросмотром' },
  },
  {
    slug: 'cron-generator', icon: '⏲️', category: 'misc', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Cron Generator', 'zh-cn': 'Cron 表达式生成器', 'zh-tw': 'Cron 表達式產生器', 'ja': 'Cron式ジェネレーター', 'ko': 'Cron 표현식 생성기', 'es': 'Generador Cron', 'fr': 'Générateur Cron', 'de': 'Cron-Generator', 'pt': 'Gerador Cron', 'ru': 'Генератор Cron' },
    description: { 'en': 'Build cron expressions with human-readable descriptions and next run times', 'zh-cn': '可视化 Cron 表达式构建器 + 人类可读描述 + 未来执行时间', 'zh-tw': '視覺化 Cron 表達式建構器 + 人類可讀描述 + 未來執行時間', 'ja': 'Cron式ビルダー、人間が読める説明と次回実行時刻', 'ko': 'Cron 표현식 빌더, 사람이 읽을 수 있는 설명 및 다음 실행 시간', 'es': 'Construye expresiones cron con descripciones legibles y próximas ejecuciones', 'fr': 'Construisez des expressions cron avec descriptions lisibles et prochaines exécutions', 'de': 'Cron-Ausdrücke mit lesbaren Beschreibungen und nächsten Ausführungszeiten erstellen', 'pt': 'Construa expressões cron com descrições legíveis e próximas execuções', 'ru': 'Создание cron-выражений с описаниями и временем следующего запуска' },
  },
  {
    slug: 'unit-converter', icon: '📏', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Unit Converter', 'zh-cn': '单位换算器', 'zh-tw': '單位換算器', 'ja': '単位変換器', 'ko': '단위 변환기', 'es': 'Convertidor de unidades', 'fr': 'Convertisseur d\'unités', 'de': 'Einheitenrechner', 'pt': 'Conversor de unidades', 'ru': 'Конвертер единиц' },
    description: { 'en': 'Convert length, temperature, weight, volume, area, and speed units', 'zh-cn': '长度/温度/重量/体积/面积/速度单位换算', 'zh-tw': '長度/溫度/重量/體積/面積/速度單位換算', 'ja': '長さ・温度・重さ・体積・面積・速度の単位変換', 'ko': '길이/온도/무게/부피/면적/속도 단위 변환', 'es': 'Convierte unidades de longitud, temperatura, peso, volumen, área y velocidad', 'fr': 'Convertissez les unités de longueur, température, poids, volume, surface et vitesse', 'de': 'Länge, Temperatur, Gewicht, Volumen, Fläche und Geschwindigkeit umrechnen', 'pt': 'Converta unidades de comprimento, temperatura, peso, volume, área e velocidade', 'ru': 'Конвертация единиц длины, температуры, веса, объёма, площади и скорости' },
  },
  {
    slug: 'filesize-converter', icon: '💾', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'File Size Converter', 'zh-cn': '文件大小换算', 'zh-tw': '檔案大小換算', 'ja': 'ファイルサイズ変換', 'ko': '파일 크기 변환기', 'es': 'Convertidor de tamaño de archivo', 'fr': 'Convertisseur de taille de fichier', 'de': 'Dateigrößen-Konverter', 'pt': 'Conversor de tamanho de arquivo', 'ru': 'Конвертер размера файлов' },
    description: { 'en': 'Convert between B, KB, MB, GB, TB, PB in binary and decimal', 'zh-cn': 'B/KB/MB/GB/TB/PB 二进制和十进制换算', 'zh-tw': 'B/KB/MB/GB/TB/PB 二進制和十進制換算', 'ja': 'B/KB/MB/GB/TB/PBの2進数・10進数変換', 'ko': 'B/KB/MB/GB/TB/PB 이진 및 십진 변환', 'es': 'Convierte entre B, KB, MB, GB, TB, PB en binario y decimal', 'fr': 'Convertissez entre B, KB, MB, GB, TB, PB en binaire et décimal', 'de': 'Zwischen B, KB, MB, GB, TB, PB in Binär und Dezimal konvertieren', 'pt': 'Converta entre B, KB, MB, GB, TB, PB em binário e decimal', 'ru': 'Конвертация между B, KB, MB, GB, TB, PB в двоичной и десятичной системах' },
  },
  {
    slug: 'random-number', icon: '🎲', category: 'math', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'Random Number Generator', 'zh-cn': '随机数生成器', 'zh-tw': '隨機數產生器', 'ja': '乱数ジェネレーター', 'ko': '난수 생성기', 'es': 'Generador de números aleatorios', 'fr': 'Générateur de nombres aléatoires', 'de': 'Zufallszahlengenerator', 'pt': 'Gerador de números aleatórios', 'ru': 'Генератор случайных чисел' },
    description: { 'en': 'Generate random integers or floats with range and batch options', 'zh-cn': '随机整数/浮点数生成，支持范围和批量', 'zh-tw': '隨機整數/浮點數產生，支援範圍和批次', 'ja': '範囲とバッチオプション付きランダム整数・浮動小数点数生成', 'ko': '범위 및 일괄 옵션으로 랜덤 정수/실수 생성', 'es': 'Genera enteros o decimales aleatorios con opciones de rango y lote', 'fr': 'Générez des entiers ou décimaux aléatoires avec options de plage et lot', 'de': 'Zufällige Ganzzahlen oder Gleitkommazahlen mit Bereichs- und Batch-Optionen generieren', 'pt': 'Gere inteiros ou decimais aleatórios com opções de intervalo e lote', 'ru': 'Генерация случайных целых или дробных чисел с диапазоном и пакетными опциями' },
  },
  {
    slug: 'php-serialize', icon: '🐘', category: 'converter', enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: { 'en': 'PHP Serialize/Unserialize', 'zh-cn': 'PHP 序列化', 'zh-tw': 'PHP 序列化', 'ja': 'PHPシリアライズ', 'ko': 'PHP 직렬화', 'es': 'Serializar/Deserializar PHP', 'fr': 'Sérialiser/Désérialiser PHP', 'de': 'PHP-Serialisierung', 'pt': 'Serializar/Desserializar PHP', 'ru': 'PHP сериализация' },
    description: { 'en': 'Convert between PHP serialized format and JSON', 'zh-cn': 'PHP 序列化格式与 JSON 互转', 'zh-tw': 'PHP 序列化格式與 JSON 互轉', 'ja': 'PHPシリアライズ形式とJSONを相互変換', 'ko': 'PHP 직렬화 형식과 JSON 간 변환', 'es': 'Convierte entre formato serializado PHP y JSON', 'fr': 'Convertissez entre le format sérialisé PHP et JSON', 'de': 'Zwischen PHP-serialisiertem Format und JSON konvertieren', 'pt': 'Converta entre formato serializado PHP e JSON', 'ru': 'Конвертация между сериализованным форматом PHP и JSON' },
  },
];

// Query functions

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return TOOL_REGISTRY.find((tool) => tool.slug === slug);
}

export function getEnabledTools(): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.enabled);
}

export function getToolsByCategory(category: ToolCategory): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.category === category && tool.enabled);
}

export function getFeaturedTools(): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.featured === true && tool.enabled);
}

export function getToolPath(slug: string): string {
  return `/tools/${slug}`;
}

export function validateRegistry(tools: ToolMeta[]): void {
  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const tool of tools) {
    if (seen.has(tool.slug)) {
      duplicates.push(tool.slug);
    } else {
      seen.add(tool.slug);
    }
  }
  if (duplicates.length > 0) {
    throw new Error(`Duplicate slugs found in registry: ${duplicates.join(', ')}`);
  }
}
