export type ToolCategory = 'text' | 'json' | 'encoding' | 'color' | 'network' | 'math' | 'converter' | 'formatter' | 'image' | 'css' | 'misc';
export type Locale = 'en' | 'zh-cn' | 'zh-tw' | 'ja' | 'ko' | 'es' | 'fr' | 'de' | 'pt' | 'ru';

export interface ToolMeta {
  slug: string;
  icon: string;
  category: ToolCategory;
  enabled: boolean;
  featured?: boolean;
  supportedLocales: Locale[];
  name: Record<Locale, string>;
  description: Record<Locale, string>;
}

export const TOOL_REGISTRY: ToolMeta[] = [
  {
    slug: 'json-formatter',
    icon: '{}',
    category: 'json',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Formatter',
      'zh-cn': 'JSON 格式化',
      'zh-tw': 'JSON 格式化',
      'ja': 'JSON フォーマッター',
      'ko': 'JSON 포매터',
      'es': 'Formateador JSON',
      'fr': 'Formateur JSON',
      'de': 'JSON-Formatierer',
      'pt': 'Formatador JSON',
      'ru': 'Форматировщик JSON',
    },
    description: {
      'en': 'Format and validate JSON data with syntax highlighting',
      'zh-cn': '格式化并验证 JSON 数据，支持语法高亮',
      'zh-tw': '格式化並驗證 JSON 資料，支援語法高亮',
      'ja': 'JSONデータをフォーマットして検証し、シンタックスハイライトを表示',
      'ko': '구문 강조와 함께 JSON 데이터를 포맷하고 유효성 검사',
      'es': 'Formatea y valida datos JSON con resaltado de sintaxis',
      'fr': 'Formatez et validez des données JSON avec coloration syntaxique',
      'de': 'JSON-Daten formatieren und validieren mit Syntaxhervorhebung',
      'pt': 'Formate e valide dados JSON com destaque de sintaxe',
      'ru': 'Форматирование и проверка данных JSON с подсветкой синтаксиса',
    },
  },
  {
    slug: 'base64',
    icon: '🔐',
    category: 'encoding',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Base64 Encoder/Decoder',
      'zh-cn': 'Base64 编码解码',
      'zh-tw': 'Base64 編碼解碼',
      'ja': 'Base64 エンコード/デコード',
      'ko': 'Base64 인코더/디코더',
      'es': 'Codificador/Decodificador Base64',
      'fr': 'Encodeur/Décodeur Base64',
      'de': 'Base64-Encoder/Decoder',
      'pt': 'Codificador/Decodificador Base64',
      'ru': 'Кодировщик/Декодировщик Base64',
    },
    description: {
      'en': 'Encode and decode text using Base64 with URL-safe variant support',
      'zh-cn': '使用 Base64 对文本进行编码和解码，支持 URL 安全变体',
      'zh-tw': '使用 Base64 對文字進行編碼和解碼，支援 URL 安全變體',
      'ja': 'Base64でテキストをエンコード・デコード、URLセーフ変換対応',
      'ko': 'Base64로 텍스트를 인코딩 및 디코딩, URL 안전 변환 지원',
      'es': 'Codifica y decodifica texto usando Base64 con soporte de variante segura para URL',
      'fr': 'Encodez et décodez du texte en Base64 avec prise en charge de la variante URL-safe',
      'de': 'Text mit Base64 kodieren und dekodieren, mit URL-sicherer Variante',
      'pt': 'Codifique e decodifique texto usando Base64 com suporte a variante segura para URL',
      'ru': 'Кодирование и декодирование текста в Base64 с поддержкой URL-безопасного варианта',
    },
  },
  {
    slug: 'word-counter',
    icon: 'Aa',
    category: 'text',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Word Counter',
      'zh-cn': '字符统计',
      'zh-tw': '字元統計',
      'ja': '文字カウンター',
      'ko': '단어 카운터',
      'es': 'Contador de palabras',
      'fr': 'Compteur de mots',
      'de': 'Wortzähler',
      'pt': 'Contador de palavras',
      'ru': 'Счётчик слов',
    },
    description: {
      'en': 'Count characters, words, and lines in your text',
      'zh-cn': '统计文本中的字符数、单词数和行数',
      'zh-tw': '統計文字中的字元數、單詞數和行數',
      'ja': 'テキストの文字数、単語数、行数をカウント',
      'ko': '텍스트의 문자 수, 단어 수, 줄 수를 계산',
      'es': 'Cuenta caracteres, palabras y líneas en tu texto',
      'fr': 'Comptez les caractères, mots et lignes dans votre texte',
      'de': 'Zeichen, Wörter und Zeilen in Ihrem Text zählen',
      'pt': 'Conte caracteres, palavras e linhas no seu texto',
      'ru': 'Подсчёт символов, слов и строк в тексте',
    },
  },
  {
    slug: 'url-encoder',
    icon: '🔗',
    category: 'encoding',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'URL Encoder/Decoder',
      'zh-cn': 'URL 编码解码',
      'zh-tw': 'URL 編碼解碼',
      'ja': 'URLエンコード/デコード',
      'ko': 'URL 인코더/디코더',
      'es': 'Codificador/Decodificador URL',
      'fr': 'Encodeur/Décodeur URL',
      'de': 'URL-Encoder/Decoder',
      'pt': 'Codificador/Decodificador URL',
      'ru': 'Кодировщик/Декодировщик URL',
    },
    description: {
      'en': 'Encode and decode URLs with encodeURIComponent and encodeURI modes',
      'zh-cn': '使用 encodeURIComponent 和 encodeURI 模式对 URL 进行编码和解码',
      'zh-tw': '使用 encodeURIComponent 和 encodeURI 模式對 URL 進行編碼和解碼',
      'ja': 'encodeURIComponentとencodeURIモードでURLをエンコード・デコード',
      'ko': 'encodeURIComponent 및 encodeURI 모드로 URL 인코딩 및 디코딩',
      'es': 'Codifica y decodifica URLs con modos encodeURIComponent y encodeURI',
      'fr': 'Encodez et décodez des URLs avec les modes encodeURIComponent et encodeURI',
      'de': 'URLs mit encodeURIComponent- und encodeURI-Modi kodieren und dekodieren',
      'pt': 'Codifique e decodifique URLs com modos encodeURIComponent e encodeURI',
      'ru': 'Кодирование и декодирование URL с режимами encodeURIComponent и encodeURI',
    },
  },
  {
    slug: 'timestamp',
    icon: '⏰',
    category: 'converter',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Unix Timestamp Converter',
      'zh-cn': 'Unix 时间戳转换',
      'zh-tw': 'Unix 時間戳轉換',
      'ja': 'Unixタイムスタンプ変換',
      'ko': 'Unix 타임스탬프 변환',
      'es': 'Convertidor de marca de tiempo Unix',
      'fr': 'Convertisseur de timestamp Unix',
      'de': 'Unix-Zeitstempel-Konverter',
      'pt': 'Conversor de timestamp Unix',
      'ru': 'Конвертер временных меток Unix',
    },
    description: {
      'en': 'Convert between Unix timestamps and human-readable dates with timezone support',
      'zh-cn': '在 Unix 时间戳和可读日期之间互转，支持时区选择',
      'zh-tw': '在 Unix 時間戳和可讀日期之間互轉，支援時區選擇',
      'ja': 'Unixタイムスタンプと日付を相互変換、タイムゾーン対応',
      'ko': 'Unix 타임스탬프와 날짜 간 변환, 시간대 지원',
      'es': 'Convierte entre marcas de tiempo Unix y fechas legibles con soporte de zona horaria',
      'fr': 'Convertissez entre les timestamps Unix et les dates lisibles avec prise en charge des fuseaux horaires',
      'de': 'Konvertieren Sie zwischen Unix-Zeitstempeln und lesbaren Daten mit Zeitzonen-Unterstützung',
      'pt': 'Converta entre timestamps Unix e datas legíveis com suporte a fuso horário',
      'ru': 'Конвертация между временными метками Unix и читаемыми датами с поддержкой часовых поясов',
    },
  },
  {
    slug: 'json-minify',
    icon: '📦',
    category: 'json',
    enabled: true,
    featured: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Minify & Escape',
      'zh-cn': 'JSON 压缩与转义',
      'zh-tw': 'JSON 壓縮與轉義',
      'ja': 'JSON圧縮・エスケープ',
      'ko': 'JSON 압축 및 이스케이프',
      'es': 'Minificar y escapar JSON',
      'fr': 'Minifier et échapper JSON',
      'de': 'JSON-Minifizierung & Escape',
      'pt': 'Minificar e escapar JSON',
      'ru': 'Минификация и экранирование JSON',
    },
    description: {
      'en': 'Minify, escape, and unescape JSON data',
      'zh-cn': '压缩、转义和反转义 JSON 数据',
      'zh-tw': '壓縮、轉義和反轉義 JSON 資料',
      'ja': 'JSONデータの圧縮・エスケープ・アンエスケープ',
      'ko': 'JSON 데이터 압축, 이스케이프 및 언이스케이프',
      'es': 'Minifica, escapa y desescapa datos JSON',
      'fr': 'Minifiez, échappez et désechappez des données JSON',
      'de': 'JSON-Daten minifizieren, escapen und unescapen',
      'pt': 'Minifique, escape e unescape dados JSON',
      'ru': 'Минификация, экранирование и деэкранирование данных JSON',
    },
  },
  {
    slug: 'uuid-generator',
    icon: '🆔',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'UUID/GUID Generator',
      'zh-cn': 'UUID/GUID 生成器',
      'zh-tw': 'UUID/GUID 產生器',
      'ja': 'UUID/GUIDジェネレーター',
      'ko': 'UUID/GUID 생성기',
      'es': 'Generador UUID/GUID',
      'fr': 'Générateur UUID/GUID',
      'de': 'UUID/GUID-Generator',
      'pt': 'Gerador UUID/GUID',
      'ru': 'Генератор UUID/GUID',
    },
    description: {
      'en': 'Generate UUID v4 with batch and format options',
      'zh-cn': '生成 UUID v4，支持批量生成和格式选项',
      'zh-tw': '產生 UUID v4，支援批次產生和格式選項',
      'ja': 'UUID v4を生成、一括生成とフォーマットオプション対応',
      'ko': 'UUID v4 생성, 일괄 생성 및 형식 옵션 지원',
      'es': 'Genera UUID v4 con opciones de lote y formato',
      'fr': 'Générez des UUID v4 avec options de lot et de format',
      'de': 'UUID v4 generieren mit Batch- und Formatoptionen',
      'pt': 'Gere UUID v4 com opções de lote e formato',
      'ru': 'Генерация UUID v4 с пакетными и форматными опциями',
    },
  },
  {
    slug: 'hash-calculator',
    icon: '#️⃣',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Hash Calculator',
      'zh-cn': '哈希计算器',
      'zh-tw': '雜湊計算器',
      'ja': 'ハッシュ計算機',
      'ko': '해시 계산기',
      'es': 'Calculadora de Hash',
      'fr': 'Calculateur de Hash',
      'de': 'Hash-Rechner',
      'pt': 'Calculadora de Hash',
      'ru': 'Калькулятор хешей',
    },
    description: {
      'en': 'Calculate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes',
      'zh-cn': '计算 MD5、SHA-1、SHA-256、SHA-384、SHA-512 哈希值',
      'zh-tw': '計算 MD5、SHA-1、SHA-256、SHA-384、SHA-512 雜湊值',
      'ja': 'MD5、SHA-1、SHA-256、SHA-384、SHA-512ハッシュを計算',
      'ko': 'MD5, SHA-1, SHA-256, SHA-384, SHA-512 해시 계산',
      'es': 'Calcula hashes MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'fr': 'Calculez les hachages MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'de': 'MD5-, SHA-1-, SHA-256-, SHA-384-, SHA-512-Hashes berechnen',
      'pt': 'Calcule hashes MD5, SHA-1, SHA-256, SHA-384, SHA-512',
      'ru': 'Вычисление хешей MD5, SHA-1, SHA-256, SHA-384, SHA-512',
    },
  },
  {
    slug: 'color-converter',
    icon: '🎨',
    category: 'color',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Color Converter',
      'zh-cn': '颜色格式转换',
      'zh-tw': '顏色格式轉換',
      'ja': 'カラーコンバーター',
      'ko': '색상 변환기',
      'es': 'Convertidor de Color',
      'fr': 'Convertisseur de Couleur',
      'de': 'Farbkonverter',
      'pt': 'Conversor de Cor',
      'ru': 'Конвертер цветов',
    },
    description: {
      'en': 'Convert between HEX, RGB, HSL, HSV, and CMYK color formats',
      'zh-cn': '在 HEX、RGB、HSL、HSV 和 CMYK 颜色格式之间转换',
      'zh-tw': '在 HEX、RGB、HSL、HSV 和 CMYK 顏色格式之間轉換',
      'ja': 'HEX、RGB、HSL、HSV、CMYKカラー形式を相互変換',
      'ko': 'HEX, RGB, HSL, HSV, CMYK 색상 형식 간 변환',
      'es': 'Convierte entre formatos de color HEX, RGB, HSL, HSV y CMYK',
      'fr': 'Convertissez entre les formats de couleur HEX, RGB, HSL, HSV et CMYK',
      'de': 'Zwischen HEX-, RGB-, HSL-, HSV- und CMYK-Farbformaten konvertieren',
      'pt': 'Converta entre formatos de cor HEX, RGB, HSL, HSV e CMYK',
      'ru': 'Конвертация между форматами цветов HEX, RGB, HSL, HSV и CMYK',
    },
  },
  {
    slug: 'radix-converter',
    icon: '🔢',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Radix Converter',
      'zh-cn': '进制转换',
      'zh-tw': '進制轉換',
      'ja': '基数変換',
      'ko': '진법 변환기',
      'es': 'Convertidor de Base',
      'fr': 'Convertisseur de Base',
      'de': 'Zahlensystem-Konverter',
      'pt': 'Conversor de Base',
      'ru': 'Конвертер систем счисления',
    },
    description: {
      'en': 'Convert between binary, octal, decimal, and hexadecimal',
      'zh-cn': '在二进制、八进制、十进制和十六进制之间转换',
      'zh-tw': '在二進制、八進制、十進制和十六進制之間轉換',
      'ja': '2進数、8進数、10進数、16進数を相互変換',
      'ko': '2진수, 8진수, 10진수, 16진수 간 변환',
      'es': 'Convierte entre binario, octal, decimal y hexadecimal',
      'fr': 'Convertissez entre binaire, octal, décimal et hexadécimal',
      'de': 'Zwischen Binär, Oktal, Dezimal und Hexadezimal konvertieren',
      'pt': 'Converta entre binário, octal, decimal e hexadecimal',
      'ru': 'Конвертация между двоичной, восьмеричной, десятичной и шестнадцатеричной системами',
    },
  },
  {
    slug: 'case-converter',
    icon: 'Aa',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Case Converter',
      'zh-cn': '大小写转换',
      'zh-tw': '大小寫轉換',
      'ja': '大文字小文字変換',
      'ko': '대소문자 변환기',
      'es': 'Convertidor de Mayúsculas',
      'fr': 'Convertisseur de Casse',
      'de': 'Groß-/Kleinschreibung',
      'pt': 'Conversor de Maiúsculas',
      'ru': 'Конвертер регистра',
    },
    description: {
      'en': 'Convert text between uppercase, lowercase, title case, and more',
      'zh-cn': '在大写、小写、标题大小写等格式之间转换文本',
      'zh-tw': '在大寫、小寫、標題大小寫等格式之間轉換文字',
      'ja': 'テキストを大文字、小文字、タイトルケースなどに変換',
      'ko': '텍스트를 대문자, 소문자, 제목 대소문자 등으로 변환',
      'es': 'Convierte texto entre mayúsculas, minúsculas, título y más',
      'fr': 'Convertissez le texte entre majuscules, minuscules, casse de titre et plus',
      'de': 'Text zwischen Groß-, Klein-, Titelschreibung und mehr konvertieren',
      'pt': 'Converta texto entre maiúsculas, minúsculas, título e mais',
      'ru': 'Конвертация текста между верхним, нижним регистром, заглавными и другими',
    },
  },
  {
    slug: 'password-generator',
    icon: '🔑',
    category: 'encoding',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Password Generator',
      'zh-cn': '随机密码生成器',
      'zh-tw': '隨機密碼產生器',
      'ja': 'パスワードジェネレーター',
      'ko': '비밀번호 생성기',
      'es': 'Generador de Contraseñas',
      'fr': 'Générateur de Mots de Passe',
      'de': 'Passwort-Generator',
      'pt': 'Gerador de Senhas',
      'ru': 'Генератор паролей',
    },
    description: {
      'en': 'Generate secure random passwords with customizable options',
      'zh-cn': '生成安全的随机密码，支持自定义选项',
      'zh-tw': '產生安全的隨機密碼，支援自訂選項',
      'ja': 'カスタマイズ可能なオプションで安全なランダムパスワードを生成',
      'ko': '사용자 정의 옵션으로 안전한 랜덤 비밀번호 생성',
      'es': 'Genera contraseñas aleatorias seguras con opciones personalizables',
      'fr': 'Générez des mots de passe aléatoires sécurisés avec des options personnalisables',
      'de': 'Sichere zufällige Passwörter mit anpassbaren Optionen generieren',
      'pt': 'Gere senhas aleatórias seguras com opções personalizáveis',
      'ru': 'Генерация безопасных случайных паролей с настраиваемыми параметрами',
    },
  },
  {
    slug: 'json-sort',
    icon: '🔤',
    category: 'json',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'JSON Sort',
      'zh-cn': 'JSON 排序',
      'zh-tw': 'JSON 排序',
      'ja': 'JSONソート',
      'ko': 'JSON 정렬',
      'es': 'Ordenar JSON',
      'fr': 'Tri JSON',
      'de': 'JSON-Sortierung',
      'pt': 'Ordenar JSON',
      'ru': 'Сортировка JSON',
    },
    description: {
      'en': 'Sort JSON object keys alphabetically in ascending or descending order',
      'zh-cn': '按字母顺序对 JSON 对象键进行升序或降序排序',
      'zh-tw': '按字母順序對 JSON 物件鍵進行升序或降序排序',
      'ja': 'JSONオブジェクトのキーをアルファベット順に昇順または降順でソート',
      'ko': 'JSON 객체 키를 알파벳순으로 오름차순 또는 내림차순 정렬',
      'es': 'Ordena las claves de objetos JSON alfabéticamente en orden ascendente o descendente',
      'fr': 'Triez les clés des objets JSON par ordre alphabétique croissant ou décroissant',
      'de': 'JSON-Objektschlüssel alphabetisch aufsteigend oder absteigend sortieren',
      'pt': 'Ordene as chaves de objetos JSON alfabeticamente em ordem crescente ou decrescente',
      'ru': 'Сортировка ключей объектов JSON по алфавиту в порядке возрастания или убывания',
    },
  },
  {
    slug: 'regex-tester',
    icon: '🔍',
    category: 'misc',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'Regex Tester',
      'zh-cn': '正则表达式测试器',
      'zh-tw': '正規表達式測試器',
      'ja': '正規表現テスター',
      'ko': '정규식 테스터',
      'es': 'Probador de Regex',
      'fr': 'Testeur de Regex',
      'de': 'Regex-Tester',
      'pt': 'Testador de Regex',
      'ru': 'Тестер регулярных выражений',
    },
    description: {
      'en': 'Test regular expressions with real-time matching and highlighting',
      'zh-cn': '实时匹配和高亮显示测试正则表达式',
      'zh-tw': '即時匹配和高亮顯示測試正規表達式',
      'ja': 'リアルタイムマッチングとハイライトで正規表現をテスト',
      'ko': '실시간 매칭 및 하이라이트로 정규식 테스트',
      'es': 'Prueba expresiones regulares con coincidencia y resaltado en tiempo real',
      'fr': 'Testez des expressions régulières avec correspondance et surlignage en temps réel',
      'de': 'Reguläre Ausdrücke mit Echtzeit-Matching und Hervorhebung testen',
      'pt': 'Teste expressões regulares com correspondência e destaque em tempo real',
      'ru': 'Тестирование регулярных выражений с сопоставлением и подсветкой в реальном времени',
    },
  },
  {
    slug: 'qrcode',
    icon: '📱',
    category: 'converter',
    enabled: true,
    supportedLocales: ['en', 'zh-cn', 'zh-tw', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
    name: {
      'en': 'QR Code Generator',
      'zh-cn': '二维码生成器',
      'zh-tw': 'QR Code 產生器',
      'ja': 'QRコードジェネレーター',
      'ko': 'QR 코드 생성기',
      'es': 'Generador de Código QR',
      'fr': 'Générateur de QR Code',
      'de': 'QR-Code-Generator',
      'pt': 'Gerador de QR Code',
      'ru': 'Генератор QR-кодов',
    },
    description: {
      'en': 'Generate QR codes from text with customizable size and colors',
      'zh-cn': '从文本生成二维码，支持自定义大小和颜色',
      'zh-tw': '從文字產生 QR Code，支援自訂大小和顏色',
      'ja': 'テキストからQRコードを生成、サイズと色のカスタマイズ対応',
      'ko': '텍스트에서 QR 코드 생성, 크기 및 색상 사용자 정의 지원',
      'es': 'Genera códigos QR desde texto con tamaño y colores personalizables',
      'fr': 'Générez des QR codes à partir de texte avec taille et couleurs personnalisables',
      'de': 'QR-Codes aus Text mit anpassbarer Größe und Farben generieren',
      'pt': 'Gere QR codes a partir de texto com tamanho e cores personalizáveis',
      'ru': 'Генерация QR-кодов из текста с настраиваемым размером и цветами',
    },
  },
];

// Query functions

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return TOOL_REGISTRY.find((tool) => tool.slug === slug);
}

export function getEnabledTools(): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.enabled);
}

export function getToolsByCategory(category: ToolCategory): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.category === category && tool.enabled);
}

export function getFeaturedTools(): ToolMeta[] {
  return TOOL_REGISTRY.filter((tool) => tool.featured === true && tool.enabled);
}

export function getToolPath(slug: string): string {
  return `/tools/${slug}`;
}

export function validateRegistry(tools: ToolMeta[]): void {
  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const tool of tools) {
    if (seen.has(tool.slug)) {
      duplicates.push(tool.slug);
    } else {
      seen.add(tool.slug);
    }
  }
  if (duplicates.length > 0) {
    throw new Error(`Duplicate slugs found in registry: ${duplicates.join(', ')}`);
  }
}
